### PR TITLE
Move three existing packages under the SpeciesDistributionToolkit monorepo

### PR DESCRIPTION
**Pull request by tpoisot**
This updates `G/GBIF/Package.toml` to point to a subdir within a new repo. I will open a PR for a new release after this one is merged?

### CODE REVIEW

**Comment by giordano** [comment]
Are all previous versions of this package available in the history of the new repository?

**Comment by tpoisot** [comment]
No, only the new versions will. There's still a repo with all the previous releases/history.

**Review by giordano — CHANGES_REQUESTED** [review]
Then this change breaks the package

**Comment by tpoisot** [comment]
@t-bltg thanks for the feedback - I've done a bit of work since the move, do you think the `git-filter-repo` recipe would work still?

**Comment by tpoisot** [comment]
@giordano I have applied the fix suggested by @t-bltg -- here is the output of the sanity check for the three packages affected by the change.

~~~
GBIF
0.1.4 found
0.2.0 found
0.2.1 found
0.2.2 found
0.2.3 found
0.2.4 found
0.3.0 found
0.3.1 found
0.3.2 found
0.3.3 found
Fauxcurrences
0.0.1 found
SimpleSDMLayers
0.0.1 found
0.1.0 found
0.2.0 found
0.2.1 found
0.2.2 found
0.3.0 found
0.3.1 found
0.3.2 found
0.3.3 found
0.3.4 found
0.3.5 found
0.3.6 found
0.4.0 found
0.4.1 found
0.4.2 found
0.4.3 found
0.4.4 found
0.4.5 found
0.4.6 found
0.4.7 found
0.4.8 found
0.5.0 found
0.6.0 found
0.7.0 found
0.8.0 found
0.8.1 found
0.8.2 found
0.8.3 found
~~~

**Comment by tpoisot** [comment]
This isn't ready to be merged yet, I am waiting for the tests to run.

**Comment by tpoisot** [comment]
@giordano all clear on my side, but please let me know if you see additional steps

**Review by giordano — APPROVED** [review]
On this branch I was now able to install those packages:
```
(jl_BuvnMt) pkg> st
Status `/tmp/jl_BuvnMt/Project.toml`
  [a2d61402] Fauxcurrences v0.0.1
  [ee291a33] GBIF v0.3.3
  [2c645270] SimpleSDMLayers v0.8.3
```

Thanks for doing it! :+1:

**Pull request merged**
