### PR TITLE
RetroCap SciML

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
```julia
using GitHub
using RetroCap

orgrepos, page_data = GitHub.repos("SciML")

pkgs = RetroCap.Package[]
for r in orgrepos
    name = r.name
    if endswith(name, ".jl")
        push!(pkgs, RetroCap.Package(name[1:end-3]))
    end
end
unique!(pkgs)

pkg_to_path,
    pkg_to_num_versions,
    pkg_to_latest_version,
    pkg_to_latest_zero_version = RetroCap.parse_registry(String[pwd()])

for pkg in pkgs
    try
        add_caps(MonotonicUpperBound(),    # or use `UpperBound()`
                 CapLatestVersion(),
                 String[pwd()],
                 pkg_to_latest_version,
                 pkg_to_latest_zero_version,
                 pkg,
                 pkg_to_path[pkg])
    catch
        println("Package $(pkg) not affected")
    end
end
```

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Did you make this from the latest master?

**Comment by ChrisRackauckas** [comment]
Yes

**Comment by DilumAluthge** [comment]
> This branch is [1 commit ahead](https://github.com/ChrisRackauckas/General/compare/JuliaRegistries:master...retrocap_sciml), [54477 commits behind](https://github.com/ChrisRackauckas/General/compare/retrocap_sciml...JuliaRegistries:master) JuliaRegistries:master.

**Comment by DilumAluthge** [comment]
Can you try pulling the latest upstream master, and then rerunning your script?

**Pull request closed without merging**
