### PR TITLE
Restrict LibCURL v7.71+ to Julia v1.6

### LINKED ISSUE #2051: LibCURL_jll broken on windows
```
(@v1.5) pkg> add LibCURL_jll
   Updating registry at `C:\Users\avik\.julia\registries\General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
Updating `C:\Users\avik\.julia\environments\v1.5\Project.toml`
  [deac9b47] + LibCURL_jll v7.71.1+0
Updating `C:\Users\avik\.julia\environments\v1.5\Manifest.toml`
  [deac9b47] + LibCURL_jll v7.71.1+0
  [29816b5a] + LibSSH2_jll v1.9.0+3
  [c8ffd9c3] + MbedTLS_jll v2.16.8+1
  [8e850ede] + nghttp2_jll v1.40.0+2

julia> using LibCURL_jll
ERROR: InitError: could not load library "C:\Users\avik\.julia\artifacts\93a125a1f028ecc90665616e44072e4da65aea23\bin\libcurl-4.dll"
The specified procedure could not be found.
Stacktrace:
 [1] dlopen(::String, ::UInt32; throw_error::Bool) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Libdl\src\Libdl.jl:109
 [2] dlopen at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Libdl\src\Libdl.jl:109 [inlined] (repeats 2 times)
 [3] __init__() at C:\Users\avik\.julia\packages\LibCURL_jll\yitNc\src\wrappers\x86_64-w64-mingw32.jl:79
 [4] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:697
 [5] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:782
 [6] _require(::Base.PkgId) at .\loading.jl:1007
 [7] require(::Base.PkgId) at .\loading.jl:928
 [8] require(::Module, ::Symbol) at .\loading.jl:923
during initialization of module LibCURL_jll
```

*Windows 10* 
*Julia v1.5.2*

### PR DESCRIPTION
**Pull request by staticfloat**
This prevents newer versions of LibCURL from being installed on older
Julia's that have an incompatible version of libmbedtls installed.

Fixes https://github.com/JuliaPackaging/Yggdrasil/issues/2051

### CODE REVIEW

**Comment by DilumAluthge** [comment]
cc: @StefanKarpinski

**Comment by StefanKarpinski** [comment]
On this commit, I get:
```
ERROR: Unknown package JLLWrappers found in the compatibility requirements
of LibCURL_jll [deac9b47]
```

**Comment by StefanKarpinski** [comment]
Which doesn't really make sense since the package is clearly present.

**Comment by staticfloat** [comment]
Perhaps the registry is borked somehow?

**Comment by StefanKarpinski** [comment]
It looks fine, I just cloned it. I have no idea what is going on.

**Comment by StefanKarpinski** [comment]
No, it's correct that this is wrong: you have compat on a non-dependency for LibCURL_jll here. The error message sucks, but this is a broken registry configuration. You need to make sure that everything that's in compat is also a dependency or the resolver has no idea what it refers to.

**Comment by staticfloat** [comment]
Ah!  I see!  JLLWrappers wasn't added until the later version.  @DilumAluthge @fredrikekre can we catch that in the Travis CI run?

**Comment by StefanKarpinski** [comment]
Ok, both Downloads and LibCURL_jll work with this state of the registry.

**Pull request merged**
