### PR TITLE
New version: libLLVM_assert_jll v12.0.0+0

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package libLLVM_assert_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl
* Version: v12.0.0+0
* Commit: 93be3b123ecc20f16dd992162f23967d77a0f7cc
* Revision on Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/commit/dd6dedc516a6629ea5052d3772ff50bc80b44ef3

### CODE REVIEW

**Comment by DilumAluthge** [comment]
It's kind of weird that this passed, but https://github.com/JuliaRegistries/General/pull/36384 failed.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaRegistries/General/pull/36384 requires Julia 1.7.

Should this PR also require Julia 1.7?

**Comment by giordano** [comment]
> Should this PR also require Julia 1.7?

Yes

**Comment by DilumAluthge** [comment]
> > Should this PR also require Julia 1.7?
> 
> Yes

I can open an issue. Should I file it on Ygg or BB?

**Comment by vchuravy** [comment]
Ah yes that is my bad, I forgot to set the compat for this correctly. Let's fix it in this PR

**Review by vchuravy — APPROVED** [review]

**Pull request merged**
