### PR TITLE
Remove Julia from the General registry

### PR DESCRIPTION
**Pull request by DilumAluthge**
We now have the https://julialang-s3.julialang.org/bin/versions.json file, which is auto-updated. So we don't need to have Julia in the General registry.

Closes #23334

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Have you tried using a registry that has `julia` removed? Great if it works.

**Comment by DilumAluthge** [comment]
Seems to work fine:

```julia
$ rm -rf ~/.julia
$ rm -rf General
$ git clone https://github.com/JuliaRegistries/General.git General
Cloning into 'General'...
remote: Enumerating objects: 90, done.
remote: Counting objects: 100% (90/90), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 371134 (delta 22), reused 37 (delta 9), pack-reused 371044
Receiving objects: 100% (371134/371134), 102.14 MiB | 8.94 MiB/s, done.
Resolving deltas: 100% (203372/203372), done.
Updating files: 100% (18433/18433), done.
$ cd General
$ git checkout dpa/remove-julia-from-general-registry
Branch 'dpa/remove-julia-from-general-registry' set up to track remote branch 'dpa/remove-julia-from-general-registry' from 'origin'.
Switched to a new branch 'dpa/remove-julia-from-general-registry'
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0-DEV.1506 (2020-11-16)
 _/ |\__'_|_|_|\__'_|  |  Commit 9b0232ead8 (2 days old master)
|__/                   |

julia> import Pkg

julia> Pkg.Registry.add(Pkg.RegistrySpec(path = pwd()))
     Copying registry from `~/Downloads/General`
       Added registry `General` to `~/.julia/registries/General`

julia> Pkg.add("DataFrames")
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
   Installed Missings ──────────────────── v0.4.4
   Installed Reexport ──────────────────── v0.2.0
   Installed Formatting ────────────────── v0.4.1
   Installed Crayons ───────────────────── v4.0.4
   Installed TableTraits ───────────────── v1.0.0
   Installed Parsers ───────────────────── v1.0.12
   Installed DataStructures ────────────── v0.18.8
   Installed DataFrames ────────────────── v0.22.0
   Installed SortingAlgorithms ─────────── v0.3.1
   Installed OrderedCollections ────────── v1.3.2
   Installed DataAPI ───────────────────── v1.4.0
   Installed StructTypes ───────────────── v1.1.0
   Installed DataValueInterfaces ───────── v1.0.0
   Installed Compat ────────────────────── v3.23.0
   Installed JSON ──────────────────────── v0.21.1
   Installed PooledArrays ──────────────── v0.5.3
   Installed IteratorInterfaceExtensions ─ v1.0.0
   Installed InvertedIndices ───────────── v1.0.0
   Installed Tables ────────────────────── v1.2.1
   Installed CategoricalArrays ─────────── v0.9.0
   Installed PrettyTables ──────────────── v0.10.1
  Downloaded artifact: LibCURL
  Downloaded artifact: MozillaCACerts
Updating `~/.julia/environments/v1.6/Project.toml`
  [a93c6f00] + DataFrames v0.22.0
Updating `~/.julia/environments/v1.6/Manifest.toml`
  [324d7699] + CategoricalArrays v0.9.0
  [34da2185] + Compat v3.23.0
  [a8cc5b0e] + Crayons v4.0.4
  [9a962f9c] + DataAPI v1.4.0
  [a93c6f00] + DataFrames v0.22.0
  [864edb3b] + DataStructures v0.18.8
  [e2d170a0] + DataValueInterfaces v1.0.0
  [59287772] + Formatting v0.4.1
  [41ab1584] + InvertedIndices v1.0.0
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [682c06a0] + JSON v0.21.1
  [e1d29d7a] + Missings v0.4.4
  [bac558e1] + OrderedCollections v1.3.2
  [69de0a69] + Parsers v1.0.12
  [2dfb63ee] + PooledArrays v0.5.3
  [08abe8d2] + PrettyTables v0.10.1
  [189a3867] + Reexport v0.2.0
  [a2af1166] + SortingAlgorithms v0.3.1
  [856f2bd8] + StructTypes v1.1.0
  [3783bdb8] + TableTraits v1.0.0
  [bd369af6] + Tables v1.2.1
  [0dad84c5] + ArgTools
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8bb1440f] + DelimitedFiles
  [8ba89e20] + Distributed
  [f43a241f] + Downloads
  [9fa8497b] + Future
  [b77e0a4c] + InteractiveUtils
  [b27032c2] + LibCURL
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [ca575930] + NetworkOptions
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [1a1011a3] + SharedArrays
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [fa267f1f] + TOML
  [a4e569a6] + Tar
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [deac9b47] + LibCURL_jll
  [14a3606d] + MozillaCACerts_jll
Precompiling project...
  Progress [========================================>]  21/21
21 dependencies successfully precompiled in 78 seconds

julia> import DataFrames
```

**Comment by DilumAluthge** [comment]
I guess there is one advantage to keeping Julia in the registry: it keeps people from registering a package named "Julia".

**Comment by DilumAluthge** [comment]
I think a better option is to keep Julia in the General registry, but just delete the list of versions, since we have the https://julialang-s3.julialang.org/bin/versions.json file.

That way, we prevent someone from accidentally registering a package named "julia".

**Comment by DilumAluthge** [comment]
Yep, still works fine:
```bash
$ rm -rf ~/.julia
$ rm -rf General
$ git clone https://github.com/JuliaRegistries/General.git General
Cloning into 'General'...
remote: Enumerating objects: 128, done.
remote: Counting objects: 100% (128/128), done.
remote: Compressing objects: 100% (114/114), done.
remote: Total 371156 (delta 35), reused 41 (delta 11), pack-reused 371028
Receiving objects: 100% (371156/371156), 102.15 MiB | 11.15 MiB/s, done.
Resolving deltas: 100% (203368/203368), done.
Updating files: 100% (18432/18432), done.
$ cd General
$ git checkout dpa/remove-julia-from-general-registry
Branch 'dpa/remove-julia-from-general-registry' set up to track remote branch 'dpa/remove-julia-from-general-registry' from 'origin'.
Switched to a new branch 'dpa/remove-julia-from-general-registry'
$ julia

               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0-DEV.1506 (2020-11-16)
 _/ |\__'_|_|_|\__'_|  |  Commit 9b0232ead8 (2 days old master)
|__/                   |

julia> import Pkg

julia> Pkg.Registry.add(Pkg.RegistrySpec(path = pwd()))
     Copying registry from `~/Downloads/General`
       Added registry `General` to `~/.julia/registries/General`

julia> Pkg.add("DataFrames")
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
   Installed Formatting ────────────────── v0.4.1
   Installed Crayons ───────────────────── v4.0.4
   Installed Reexport ──────────────────── v0.2.0
   Installed Missings ──────────────────── v0.4.4
   Installed Parsers ───────────────────── v1.0.12
   Installed TableTraits ───────────────── v1.0.0
   Installed DataStructures ────────────── v0.18.8
   Installed OrderedCollections ────────── v1.3.2
   Installed SortingAlgorithms ─────────── v0.3.1
   Installed StructTypes ───────────────── v1.1.0
   Installed DataAPI ───────────────────── v1.4.0
   Installed DataValueInterfaces ───────── v1.0.0
   Installed Compat ────────────────────── v3.23.0
   Installed JSON ──────────────────────── v0.21.1
   Installed DataFrames ────────────────── v0.22.0
   Installed PooledArrays ──────────────── v0.5.3
   Installed Tables ────────────────────── v1.2.1
   Installed IteratorInterfaceExtensions ─ v1.0.0
   Installed CategoricalArrays ─────────── v0.9.0
   Installed InvertedIndices ───────────── v1.0.0
   Installed PrettyTables ──────────────── v0.10.1
  Downloaded artifact: LibCURL
  Downloaded artifact: MozillaCACerts
Updating `~/.julia/environments/v1.6/Project.toml`
  [a93c6f00] + DataFrames v0.22.0
Updating `~/.julia/environments/v1.6/Manifest.toml`
  [324d7699] + CategoricalArrays v0.9.0
  [34da2185] + Compat v3.23.0
  [a8cc5b0e] + Crayons v4.0.4
  [9a962f9c] + DataAPI v1.4.0
  [a93c6f00] + DataFrames v0.22.0
  [864edb3b] + DataStructures v0.18.8
  [e2d170a0] + DataValueInterfaces v1.0.0
  [59287772] + Formatting v0.4.1
  [41ab1584] + InvertedIndices v1.0.0
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [682c06a0] + JSON v0.21.1
  [e1d29d7a] + Missings v0.4.4
  [bac558e1] + OrderedCollections v1.3.2
  [69de0a69] + Parsers v1.0.12
  [2dfb63ee] + PooledArrays v0.5.3
  [08abe8d2] + PrettyTables v0.10.1
  [189a3867] + Reexport v0.2.0
  [a2af1166] + SortingAlgorithms v0.3.1
  [856f2bd8] + StructTypes v1.1.0
  [3783bdb8] + TableTraits v1.0.0
  [bd369af6] + Tables v1.2.1
  [0dad84c5] + ArgTools
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8bb1440f] + DelimitedFiles
  [8ba89e20] + Distributed
  [f43a241f] + Downloads
  [9fa8497b] + Future
  [b77e0a4c] + InteractiveUtils
  [b27032c2] + LibCURL
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [ca575930] + NetworkOptions
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [1a1011a3] + SharedArrays
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [fa267f1f] + TOML
  [a4e569a6] + Tar
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [deac9b47] + LibCURL_jll
  [14a3606d] + MozillaCACerts_jll
Precompiling project...
  Progress [========================================>]  21/21
21 dependencies successfully precompiled in 49 seconds

julia> import DataFrames
```

**Comment by StefanKarpinski** [comment]
I guess in that case I'd favor deleting it and adding an explicit CI rule preventing registration of a package named Julia.

**Comment by DilumAluthge** [comment]
> I guess in that case I'd favor deleting it and adding an explicit CI rule preventing registration of a package named Julia.

It turns out we already have a CI rule that prevents AutoMerge of new packages that contain the word "julia" in their name (after lowercasing their name):
- https://github.com/JuliaRegistries/RegistryCI.jl/blob/081d95003f7deebcae12418278bf2c26286f8fc2/src/AutoMerge/new-package.jl#L117
- https://github.com/JuliaRegistries/RegistryCI.jl/blob/081d95003f7deebcae12418278bf2c26286f8fc2/src/AutoMerge/guidelines.jl#L117

I think that's sufficient, right?

**Review by fredrikekre — APPROVED** [review]

**Comment by KristofferC** [comment]
I'm going to revert this since I see reports that this breaks things. Nightly on Pkg might use this as well.

**Pull request merged**
