### PR TITLE
Revert "New version: Cairo_jll v1.18.0+0"

### PR DESCRIPTION
**Pull request by jeremiahpslewis**
Reverts JuliaRegistries/General#93022

### CODE REVIEW

**Comment by jeremiahpslewis** [comment]
See https://github.com/JuliaPackaging/Yggdrasil/issues/7508#issuecomment-1752602689

@giordano

**Comment by giordano** [comment]
Yank, not revert

**Comment by jeremiahpslewis** [comment]
@giordano What do I do to yank?

**Comment by giordano** [comment]
https://github.com/JuliaRegistries/General/pulls?q=is%3Apr+sort%3Aupdated-desc+label%3Ayank+is%3Aclosed

**Pull request closed without merging**
