### PR TITLE
New version: HelloWorldC_jll v1.0.7+0

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package HelloWorldC_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl
* Version: v1.0.7+0

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Do not merge this - I am using this for testing.

**Comment by DilumAluthge** [comment]
Automerge is failing because this PR was made from a fork. In order for us to enable automerging of JLL packages, we will need to give the @jlbuild user push access to the General repo.

**Comment by DilumAluthge** [comment]
@giordano This is going to fail automerge because it was made from a fork.

We can manually merge this, and then trigger a new registration that is made from the new system that works?

**Comment by giordano** [comment]
I thought that closing this confused BB and caused [this build](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=794&view=results) to register a new version of HellowWorldC, but probably the problem was something else.

**Comment by DilumAluthge** [comment]
I'm fine with reopening this and merging it if it will fix the problem!

**Pull request closed without merging**
