### PR TITLE
Yank GenomicFeatures version 1.0.1

### PR DESCRIPTION
**Pull request by DilumAluthge**
cc: @CiaranOMara 

Replaces #7590

### CODE REVIEW

**Comment by CiaranOMara** [comment]
@DilumAluthge, thank you. Is it true that v1.0.1 cannot be reused after this?

**Comment by DilumAluthge** [comment]
> Is it true that v1.0.1 cannot be reused after this?

Correct.

**Comment by DilumAluthge** [comment]
@CiaranOMara Let me know whether or not you want me to merge this.

**Comment by CiaranOMara** [comment]
@DilumAluthge, let’s merge. I’ve got a hotfix that will make v1.0.2.

**Pull request merged**
