### PR TITLE
Change repo URL because of change of ownership (from antonuccig to gi…

### PR DESCRIPTION
**Pull request by giancarloantonucci**
…ancarloantonucci)

### CODE REVIEW

**Comment by giancarloantonucci** [comment]
Can someone merge this?

**Comment by giancarloantonucci** [comment]
That's me, but I see that I have no way to prove it... Or have I? Is there a way to show you that I've changed username? (in particular, see this: https://discourse.julialang.org/t/can-i-change-my-username-so-that-it-matches-my-github-username/70173)

**Comment by ViralBShah** [comment]
I can verify it by going to the old URL and it redirects. However it redirects to https://github.com/giancarloantonucci/NSDETimeParallel.jl.

**Comment by giancarloantonucci** [comment]
Changed it back (I want to put a big deprecation note before submit a new package with the new name). Can you merge this now?

**Pull request merged**
