### PR TITLE
New package: IpoptMKL_jll v3.13.2+0

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package IpoptMKL_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/IpoptMKL_jll.jl
* Version: v3.13.2+0

### CODE REVIEW

**Comment by DilumAluthge** [comment]
[noblock]

@staticfloat @giordano @vchuravy

**Comment by DilumAluthge** [comment]
[noblock]

Let me know if you want me to merge this manually.

**Comment by vchuravy** [comment]
I will leave that to @giordano, it looks like he is looking into making MKL work better for this.

**Comment by DilumAluthge** [comment]
I'm going to close this. Feel free to re-register whenever you are ready.

**Pull request closed without merging**
