### PR TITLE
 New version: HDF5_jll v1.10.5+2

### PR DESCRIPTION
**Pull request by giordano**
Fixes conflicts in #6262.

### CODE REVIEW

**Comment by musm** [comment]
merge?

**Comment by musm** [comment]
@StefanKarpinski  can I ping you to merge this ? Or anyone else with permission  😄

**Comment by giordano** [comment]
Either this or #6262, they're the same

**Comment by StefanKarpinski** [comment]
I've given @giordano commit bit on this org, so feel free to merge as appropriate.

**Comment by ararslan** [comment]
#6262 has been merged.

**Pull request closed without merging**
