### PR TITLE
New package: SPIRV_LLVM_Translator_jll v10.0.0+0

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package SPIRV_LLVM_Translator_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl
* Version: v10.0.0+0

### CODE REVIEW

**Comment by vchuravy** [comment]
@maleadt I expected at least this one to be able to be loaded:
```
libLLVM-8jl.so: cannot open shared object file: No such file or directory
```

Merde, we messed up the official release and didn't suffix the LLVM version there.

**Comment by maleadt** [comment]
Looks like the 1.4.1 ship has also just sailed: https://github.com/JuliaLang/julia/pull/35229
Should we drop the suffix in libLLVM_jll v8 to keep it consistent?

**Comment by KristofferC** [comment]
> Looks like the 1.4.1 ship has also just sailed: JuliaLang/julia#35229

I mean, if there are reasons not to release it yet, we can just delay the release). Add a comment to https://github.com/JuliaLang/julia/pull/35467 in that case.

**Comment by vchuravy** [comment]
1.4.1 has the correct suffix. I made sure of that.

**Comment by maleadt** [comment]
OK, so they should be good to go then (assuming 1.4.1 ships a jl-suffixed libllvm). The others (LLVM 9, LLVM 10) are all going to be unloadable by the automerger's Julia version anyhow, so we can ignore its complaints.

**Pull request merged**
