### PR TITLE
Revert "Reintroduce DataStructures bound"

### PR DESCRIPTION
**Pull request by fredrikekre**
Reverts JuliaRegistries/General#20415

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
No

**Comment by fredrikekre** [comment]
You broke peoples environments.

**Comment by ChrisRackauckas** [comment]
So why not fix it?

**Comment by fredrikekre** [comment]
Sure, I just wanted to unbreak it and don't have time to look at it now.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaRegistries/General/pull/20419

**Comment by ChrisRackauckas** [comment]
I already opened a PR to fix it which is why I closed this

**Comment by MasonProtter** [comment]
Wouldn't it be reasonable to undo the damage until we're sure that #20419 is kosher? Right now I am possibly others are sitting here with broken environments.

**Pull request merged**
