### PR TITLE
Set Upper Bound for StatsModels

### PR DESCRIPTION
**Pull request by matthieugomez**

### CODE REVIEW

**Comment by fredrikekre** [comment]
You will have to do this for all versions, otherwise Pkg will just use an old version of the package.

**Comment by matthieugomez** [comment]
Thanks. Is that better?

**Comment by fredrikekre** [comment]
For versions pre 0.5.2? Maybe its not applicable there?

**Comment by matthieugomez** [comment]
I put StatsModels in the REQUIRE file starting from version 0.5.1 (before, it was part of DataFrames).
That's why the current Compat is bounding it starting from 0.5.1, so maybe that is enough?
Pinging @kleinschmidt

**Comment by kleinschmidt** [comment]
I'm preparing a big PR that will do this for all statsmodels dependents.

**Comment by matthieugomez** [comment]
Thanks @kleinschmidt

**Pull request closed without merging**
