### PR TITLE
New package: Deno_jll v1.9.2+0

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package Deno_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/Deno_jll.jl
* Version: v1.9.2+0
* Commit: 7c434aa3daceefa563b934d3a1883fa8edf13506
* Revision on Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/commit/23f05bca67366386187d7ae6cf66d6fb235abe34

### CODE REVIEW

**Comment by giordano** [comment]
@DilumAluthge any clue what's wrong with this one?

[noblock]

**Comment by DilumAluthge** [comment]
[noblock]

@ericphanson

**Comment by DilumAluthge** [comment]
[noblock]

For context, this check passed on a different JLL package (https://github.com/JuliaRegistries/General/pull/36391), although that was a new JLL version PR, whereas this is a new JLL package PR.

**Comment by giordano** [comment]
You're looking to the wrong job, this one opened the pull request: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=10826&view=results

**Comment by DilumAluthge** [comment]
[noblock]

Should be fixed by https://github.com/JuliaRegistries/RegistryCI.jl/pull/399

**Comment by giordano** [comment]
Thanks for the quick fix!

[noblock]

**Pull request merged**
