### PR TITLE
Add julia v1.5.0

### PR DESCRIPTION
**Pull request by vdayanand**

### CODE REVIEW

**Comment by fredrikekre** [comment]
What are those entries used for?

**Comment by StefanKarpinski** [comment]
There are some tools that use them. Pkg itself doesn't.

**Comment by fredrikekre** [comment]
Maybe those tools can keep this list then? Or just use Elliot's JSON file?

**Comment by StefanKarpinski** [comment]
If we're going to do that then I think we should just delete Julia from the registry entirely.

**Pull request merged**
