### PR TITLE
Changing repository address 

### PR DESCRIPTION
**Pull request by YongHee-Kim**
Hello,

I have two registered packages under the organization of my previous employer. And since I left the company, there is no maintainer for those packages.  
I asked them to transfer the github repo, but they instead told me to fork and do whatever I wanted to do with the fork.  

Thanks

### CODE REVIEW

**Comment by fredrikekre** [comment]
Just to get it on "paper", can you get anyone from https://github.com/orgs/devsisters/people to confirm that this is okay?

**Comment by YongHee-Kim** [comment]
Ok I will send a mail to my former colleague for confirmation. And ask them for comments on this PR. (It's nighttime in Korea, It will take a day or so.)

**Comment by JamesKim2998** [comment]
Hi, I'm former colleague of YongHee-Kim.

We discussed this earlier and I ask him to register forked repository as new package.

I cannot understand why he is trying to change ownership of registered name, cause we all agree to register as new package.

I cannot confirm this PR, since changing ownership to outsider can cause code injection attack using a “dependency confusion” vulnerability.

@fredrikekre @YongHee-Kim

**Comment by YongHee-Kim** [comment]
But julia registry is not there for a single company... I did't want to bloat the registry with duplicate packages. 
As I've said your internal package will be stable as long as don't change the version I've fixed on the `project.toml`

But I don't want to upset anyone here. I'm ok to register `XLSXasJSON2` or `XLSXtoJSON` as a new package. If @fredrikekre agrees on this.

**Comment by ViralBShah** [comment]
@JamesKim2998 Are you going to continue the maintenance of those packages? If not, it seems odd that they were registered. The registry does not grant ownership to anyone.

Speaking for myself from a company perspective, we at JuliaComputing have routinely transferred packages out to maintainers or orgs that maintain software - since the community benefits overall from that. The Manifest already allows for pinning packages to what you want - so I am not sure I follow your argument.

**Comment by YongHee-Kim** [comment]
I'm happy to continue the maintenance of those packages. If no further arguments are made for this, I think we are good to merge this.

**Comment by StefanKarpinski** [comment]
We do need to spell out an official General registry policy on this, but it seems to me that if @JamesKim2998 and company at @devsisters were active maintainers of this package and @YongHee-Kim had a different notion about the direction of development, then it would make sense to make a fork. That's not the case, however: @YongHee-Kim and @odow are the only people who have ever contributed to this package, so it makes sense for @YongHee-Kim to be able to continue doing that work.

**Comment by odow** [comment]
> We do need to spell out an official General registry policy on this

Yes. This is going to keep happening.

I'm okay with any decision. I'll note that `devsisters corp` has the copyright in the MIT license, but if they aren't going to continue maintenance, then it makes sense to move to @YongHee-Kim's fork.

**Comment by ViralBShah** [comment]
The copyright stays of the original owner, irrespective of who maintains going forward.

**Comment by odow** [comment]
Okay. I thought about this a bit more.

> The copyright of the original owner stays, irrespective of who maintains going forward

Sure. But in terms of an official policy, it isn't really @YongHee-Kim's decision if they conducted the work for an employer. What gives them more right to moving the package than `devsisters`?

What if the employer now employs someone to take up maintenance on the package? They now have to either set up a private registry, or submit PRs to the new repo.

The package hasn't been updated since last July, (8 months), and there are no outstanding PRs, so I wouldn't classify it as unmaintained or that the current permission structure is preventing maintenance.  The `devsisters` org can still allow people to submit PRs, and it's up to them if they want to merge.

If the original owner approves and the move is for simplifying maintenance, then great. But in this case, we didn't seem to get that:

> We discussed this earlier and I asked him to register forked repository as new package.
> I cannot understand why he is trying to change ownership of registered name, cause we all agreed to register this as new package.

It's useful to consider if this had been a different company. If the repo was under `/google` or `/microsoft`, with a single author, and that author left the company and tried to move the repository address to their private account against the wishes of the company, what would have happened?

**Comment by ViralBShah** [comment]
The fundamental question is - whether the package system is like a DNS. It is fundamentally a pointer - and not something any one person or entity owns. So a large company cannot prevent such a change - but your question is valid - would we have been less likely to make such a change.

We should definitely adopt a clear policy stance. I personally am in favour of contributors and maintainers, but it is absolutely possible that the original org continues development, and the maintainer who made the switch may stop development in the future.

There is another issue - who do we consider? The github repo account that is registered, or the person who made the registration PR?

**Comment by odow** [comment]
> We should definitely adopt a clear policy stance

Agreed.

 1. If the owner of the repository approves, then the change is okay.
 2. If the owner of the repository is uncontactable and unresponsive to PRs opened against the repository, open a PR to change the address, ping them weekly for X weeks. After X weeks of no response, merge the PR. The original owner has a right to dispute the change and revert the PR for Y months afterwards.
 3. If the owner of the repository is against the change. Do not merge the PR and wait for 2).

Who is an owner? The private account owner, or a consensus of members of the organization. Not the person with copyright or the person who made the registration PR.

**Pull request merged**
