### PR TITLE
New package: StandaloneIpopt v0.1.0

### PR DESCRIPTION
**Pull request by cgeoga**
Hello---

This code is not hosted on GitHub, but this PR was generated using `LocalRegistry.jl` and I tweaked the `repo` arg manually to be the URL instead of the ssh-based git clone address per guidance from @fredrikekre the last time I did this.

I understand there is a three day waiting period for new packages, so happy to wait. But this will need a manual merge after that.

Tangentially related, but is there any way to give me permission just to add the "needs manual merge" tag? I feel a bit guilty constantly @-ing people here, but considering that the format of my PRs is identical to the ones that get auto-merged it seems easy to overlook.

### CODE REVIEW

**Comment by cgeoga** [comment]
@giordano, could I bug you for a merge here? The 72 hour window has passed and everything looks green.

**Comment by cgeoga** [comment]
@fredrikekre, are you around? Looks like @giordano is on vacation, could I bug you for a merge here?

**Comment by GunnarFarneback** [comment]
> I tweaked the repo arg manually to be the URL instead of the ssh-based git clone address

You could use the `repo` argument of `LocalRegistry.register` to override the default taken from the git remote.

**Comment by cgeoga** [comment]
Nice, thanks! I will do that from now on. I really love the package, by the way---thank you for putting it together.

**Pull request merged**
