### PR TITLE
[PhysicalOceanography] update repo url

### PR DESCRIPTION
**Pull request by gaelforget**

### CODE REVIEW

**Comment by gaelforget** [comment]
Thanks. Does this, below, work?

https://github.com/JuliaRegistries/General/pull/70224

**Comment by gaelforget** [comment]
> Please read https://github.com/JuliaRegistries/General/blob/7785d79ab57d4a74031582a3b5a29808291c1236/README.md#how-do-i-transfer-a-package-to-an-organization-or-another-user

GitHub transfer via the settings is what I did first. Then I opened this PR. 

Based on your comment, I did the second part via _Manually_ which opened https://github.com/JuliaRegistries/General/pull/70224 

What I am missing?

**Comment by giordano** [comment]
#70224 was identical to this PR, there was no need to reopen another PR.  The fact is that you broke the redirect forking the repo at JuliaOcean to your personal account.

**Comment by gaelforget** [comment]
> #70224 was identical to this PR, there was no need to reopen another PR. The fact is that you broke the redirect forking the repo at JuliaOcean to your personal account.

So I need to do the URL change right away after transferring ownership. And only after the URL change is merged here should I create the fork to my account. 

Thanks!

**Pull request merged**
