### PR TITLE
transfer GraphNeuralNetworks.jl to JuliaGraphs org

### PR DESCRIPTION
**Pull request by CarloLucibello**
updating the repo after the transfer
https://github.com/JuliaGraphs/GraphNeuralNetworks.jl

### CODE REVIEW

**Comment by CarloLucibello** [comment]
@goerz could you merge this PR along with  #120436 and #120431 ?

**Comment by goerz** [comment]
I don't have merge permissions. You'll have to find a registry maintainer on Slack.

**Comment by ericphanson** [comment]
For old versions to remain installable, the history needs to contain all the old versions of the code. Please run this code to verify the old versions are present: https://github.com/JuliaRegistries/General/blob/master/CONTRIBUTING.md#appendix-checking-if-a-repository-contains-all-registered-versions-of-a-package

**Comment by CarloLucibello** [comment]
Thanks @ericphanson. I run the linked code and it seems to be fine for all the 3 packages I transferred:
```julia
julia> check_package_versions("GraphNeuralNetworks", "https://github.com/JuliaGraphs/GraphNeuralNetworks.jl.git");
Cloning into '/tmp/jl_vtb4pS'...
remote: Enumerating objects: 30296, done.
remote: Counting objects: 100% (6593/6593), done.
remote: Compressing objects: 100% (1701/1701), done.
remote: Total 30296 (delta 3130), reused 6239 (delta 2906), pack-reused 23703 (from 1)
Receiving objects: 100% (30296/30296), 47.65 MiB | 15.48 MiB/s, done.
Resolving deltas: 100% (15865/15865), done.
GraphNeuralNetworks: v0.1.0 found
GraphNeuralNetworks: v0.1.1 found
GraphNeuralNetworks: v0.1.2 found
GraphNeuralNetworks: v0.2.0 found
GraphNeuralNetworks: v0.2.1 found
GraphNeuralNetworks: v0.2.2 found
GraphNeuralNetworks: v0.2.3 found
GraphNeuralNetworks: v0.3.0 found
GraphNeuralNetworks: v0.3.1 found
GraphNeuralNetworks: v0.3.2 found
GraphNeuralNetworks: v0.3.3 found
GraphNeuralNetworks: v0.3.4 found
GraphNeuralNetworks: v0.3.5 found
GraphNeuralNetworks: v0.3.6 found
GraphNeuralNetworks: v0.3.7 found
GraphNeuralNetworks: v0.3.8 found
GraphNeuralNetworks: v0.3.9 found
GraphNeuralNetworks: v0.3.10 found
GraphNeuralNetworks: v0.3.11 found
GraphNeuralNetworks: v0.3.12 found
GraphNeuralNetworks: v0.3.13 found
GraphNeuralNetworks: v0.3.14 found
GraphNeuralNetworks: v0.3.15 found
GraphNeuralNetworks: v0.4.0 found
GraphNeuralNetworks: v0.4.1 found
GraphNeuralNetworks: v0.4.2 found
GraphNeuralNetworks: v0.4.3 found
GraphNeuralNetworks: v0.4.4 found
GraphNeuralNetworks: v0.4.5 found
GraphNeuralNetworks: v0.5.0 found
GraphNeuralNetworks: v0.5.1 found
GraphNeuralNetworks: v0.5.2 found
GraphNeuralNetworks: v0.6.0 found
GraphNeuralNetworks: v0.6.1 found
GraphNeuralNetworks: v0.6.2 found
GraphNeuralNetworks: v0.6.3 found
GraphNeuralNetworks: v0.6.4 found
GraphNeuralNetworks: v0.6.5 found
GraphNeuralNetworks: v0.6.6 found
GraphNeuralNetworks: v0.6.7 found
GraphNeuralNetworks: v0.6.8 found
GraphNeuralNetworks: v0.6.9 found
GraphNeuralNetworks: v0.6.10 found
GraphNeuralNetworks: v0.6.11 found
GraphNeuralNetworks: v0.6.12 found
GraphNeuralNetworks: v0.6.13 found
GraphNeuralNetworks: v0.6.14 found
GraphNeuralNetworks: v0.6.15 found
GraphNeuralNetworks: v0.6.16 found
GraphNeuralNetworks: v0.6.17 found
GraphNeuralNetworks: v0.6.18 found
GraphNeuralNetworks: v0.6.19 found
GraphNeuralNetworks: v0.6.20 found
GraphNeuralNetworks: v0.6.21 found

julia> check_package_versions("GNNlib", "https://github.com/JuliaGraphs/GraphNeuralNetworks.jl.git");
Cloning into '/tmp/jl_rYE54V'...
remote: Enumerating objects: 30296, done.
remote: Counting objects: 100% (6593/6593), done.
remote: Compressing objects: 100% (1701/1701), done.
remote: Total 30296 (delta 3130), reused 6239 (delta 2906), pack-reused 23703 (from 1)
Receiving objects: 100% (30296/30296), 47.65 MiB | 16.86 MiB/s, done.
Resolving deltas: 100% (15870/15870), done.
GNNlib: v0.1.0 found
GNNlib: v0.2.0 found
GNNlib: v0.2.1 found
GNNlib: v0.2.2 found

julia> check_package_versions("GNNGraphs", "https://github.com/JuliaGraphs/GraphNeuralNetworks.jl.git");
Cloning into '/tmp/jl_yxwsT2'...
remote: Enumerating objects: 30296, done.
remote: Counting objects: 100% (6593/6593), done.
remote: Compressing objects: 100% (1701/1701), done.
remote: Total 30296 (delta 3130), reused 6239 (delta 2906), pack-reused 23703 (from 1)
Receiving objects: 100% (30296/30296), 47.65 MiB | 16.02 MiB/s, done.
Resolving deltas: 100% (15865/15865), done.
GNNGraphs: v0.1.0 found
GNNGraphs: v1.0.0 found
GNNGraphs: v1.0.1 found
GNNGraphs: v1.1.0 found
GNNGraphs: v1.2.0 found
GNNGraphs: v1.2.1 found
```

**Review by ericphanson — APPROVED** [review]

**Comment by ericphanson** [comment]
Ok, great! All 3 are merged. I wanted to double check since when moving a pkg into a subdir, sometimes the history isn’t transferred properly, but all good here.

**Pull request merged**
