### PR TITLE
New version: MUMPS_seq_jll v500.500.102+0

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package MUMPS_seq_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl
* Version: v500.500.102+0
* Commit: 65f88231cb3cfb2b8e1d5eb228b26333332bb702
* Revision on Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/commit/f6cab3f2dbb293c9a1ed531f8f997011d0069222
* Created by: @amontoison

### CODE REVIEW

**Comment by amontoison** [comment]
@staticfloat As an expert of LBT, do you have an idea of what is the problem with it here?

**Comment by staticfloat** [comment]
The issue is that `MUMPS_seq_jll v500.500.102` requires Julia v1.9+, but AutoMerge here is running with Julia v1.8.5, so it doesn't match the right LBT version.  @DilumAluthge should there be some kind of notice here from AutoMerge that it's trying to install an incompatible version?

**Comment by amontoison** [comment]
It's probably for the same reason that a PR for a new version of `PROPACK_jll` was never opened here. :thinking: 
Capture d’écran du 2023-03-28 19-36-44

**Comment by staticfloat** [comment]
No. that's a totally separate issue; that's [a problem with PROPACK's jll](https://buildkite.com/julialang/yggdrasil/builds/1758#01872492-ec98-4f57-a377-3c510cc2a6c7/541-1375) that I don't fully understand.

**Comment by DilumAluthge** [comment]
> should there be some kind of notice here from AutoMerge that it's trying to install an incompatible version?

PkgEval has a nifty feature where they parse the logs and try to figure out the reason for a failure. So we could e.g. parse the output from the "Pkg.add" guideline, and categorize it as e.g.
- "Julia version incompatible with latest stable Julia release"
- "Other unsatisfiable requirements"
- ... [other categories] ...
- "Other"

**Comment by staticfloat** [comment]
Shouldn't we just detect that there's no overlap between the declared compat bounds on Julia and the currently-running Julia?

**Comment by DilumAluthge** [comment]
Oh yeah that's easier

**Comment by amontoison** [comment]
@DilumAluthge 
Is it possible to manually merge this PR with #80576 and #80622.
The issue is related to LBT for the three PRs.

**Comment by DilumAluthge** [comment]
@amontoison @staticfloat Looks like there are merge conflicts here. Probably we should close this PR and then trigger Yggdrasil/`@jlbuild` to open a new PR.

**Comment by amontoison** [comment]
We can close this PR.
#84583 fixed this issue.

**Pull request closed without merging**
