### PR TITLE
Register Cliquing.jl

### PR DESCRIPTION
**Pull request by iamed2**
This package was previously registered in Invenia's private registry. Versions before 2 depended on a private package which is not being open-sourced, so those have been removed, but otherwise this is copied from Invenia's registry with the URL changed.

### CODE REVIEW

**Comment by iamed2** [comment]
Closing for now as there are some unanswered questions around splitting registry history.

**Comment by iamed2** [comment]
Questions have been answered; looks like history splitting will work.

**Comment by DilumAluthge** [comment]
@iamed2 Can I merge this?

**Comment by iamed2** [comment]
@DilumAluthge Yes, please! :)

**Pull request merged**
