### PR TITLE
New version: Sundials_jll v6.7.0+0

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package Sundials_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/Sundials_jll.jl
* Version: v6.7.0+0
* Commit: c9be19e45cb3af4f4a5ef4f160c6e41ba9d7f484
* Revision on Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/commit/7ca1142489cd4bb1cf745645c8a8c09104919056
* Created by: @staticfloat

### CODE REVIEW

**Comment by DilumAluthge** [comment]
[noblock]

Looks like there is a merge conflict.

@staticfloat  Can you re-trigger a registration in Ygg? This will fix the merge conflict.

**Comment by staticfloat** [comment]
[noblock]

It's not so easy: https://buildkite.com/julialang/yggdrasil/builds/8277#018d8ac9-3c6f-42aa-9668-e945d5931a7f

**Comment by DilumAluthge** [comment]
[noblock]

Can you delete the old release assets?

**Comment by staticfloat** [comment]
That seems quite drastic, why not just resolve the conflicts here?

**Pull request closed without merging**
