### PR TITLE
Move JLLs to own folder

### LINKED ISSUE #78672: Time to start subdividing within letters `S/o/SomePackage.jl` etc
We now have [over 1000 packages starting with `S`](https://github.com/JuliaRegistries/General/tree/master/S)
so github will not display the full list.
So we might want to introduce another level into to the folder tree.

### PR DESCRIPTION
**Pull request by oxinabox**
This implements @KristofferC 's idea from https://github.com/JuliaRegistries/General/issues/78672#issuecomment-1448652097
and should (for now at least) close #78672

the script i used to do this is:
```julia
using Pkg: @pkg_str
pkg"activate --temp"
pkg"add Glob@1.3"

using Glob

mkpath.(joinpath.("jll", string.('A':'Z')))
paths = glob(glob"*/*_jll/") 
mv.(paths, joinpath.("jll", paths))

reg_file = read("Registry.toml", String)
new_reg_file = replace(reg_file, 
    r"path = \"(.*_jll)\""=> s"path = \"jll/\1\""
)
write("Registry.toml", new_reg_file)


run(`git add jll`)
run(`git commit -m "Move JLLs to own folder" -a`)
run(`git push --force-with-lease`)
```

### CODE REVIEW

**Comment by KristofferC** [comment]
Nice, we'll have to ensure Registrator doesn't freak out by this (and it should also be updated to register new jlls in this subdir) but I think this is a good idea.

**Review by staticfloat — APPROVED** [review]
Sounds good to me!

**Comment by DilumAluthge** [comment]
> Nice, we'll have to ensure Registrator doesn't freak out by this (and it should also be updated to register new jlls in this subdir) but I think this is a good idea.

IIRC, Ygg uses RegistryTools to create the registration PRs (not Registrator), so we'd need to apply the changes there.

**Review by DilumAluthge — APPROVED** [review]
SGTM!

Let's make the necessary changes to RegistryTools before we merge this PR?

**Comment by oxinabox** [comment]
Can we merge this, or do we need to rebuild a manifest on some Yggdrasil bot?

**Comment by DilumAluthge** [comment]
I think we need https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1267

**Comment by oxinabox** [comment]
that was merged and then reverted.

Meanwhile this PR has gained conflicts.
I will again reset it to HEAD then rerun the script to make the changes and force push back here. Easy enough

**Comment by GunnarFarneback** [comment]
AutoMerge will be unhappy about new jll registrations unless RegistryCI is updated with the new RegistryTools version. But that's not compatible with Julia < 1.6 so https://github.com/JuliaRegistries/RegistryTools.jl/pull/85 might need to be backported to a new RegistryTools 1.x release as well.

**Comment by DilumAluthge** [comment]
I've released a new RegistryTools 2.2 that restores compatibility with Julia 1.1+.

We need to merge https://github.com/JuliaRegistries/RegistryCI.jl/pull/500 and register RegistryCI 8.3.

Then we need to update the CI manifest in the General registry to use RegistryCI 8.3.

**Comment by oxinabox** [comment]
So current blocker is yggdrasil to the new registry tools?

**Comment by DilumAluthge** [comment]
https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1269

Someone need to review and merge that PR.

**Comment by oxinabox** [comment]
OK, I believe there should no longer be any blockers. 
Is that correct?
and I have rebased

**Review by DilumAluthge — APPROVED** [review]
SGTM. Can you run the script again? And then we can quickly merge before more conflicts arise.

**Pull request merged**
