### PR TITLE
New version: MPFR_jll v4.1.0+2

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package MPFR_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/MPFR_jll.jl
* Version: v4.1.0+2

### CODE REVIEW

**Comment by staticfloat** [comment]
@DilumAluthge I think something broke here.  This PR came from Registrator just like all the other JLLs.

**Comment by staticfloat** [comment]
pause

**Comment by DilumAluthge** [comment]
This seems to be the issue:

2020-10-22T06:53:00.7465334Z ┌ Warning: Overlapping ranges for julia in "/home/runner/work/General/General/M/MPFR_jll/Compat.toml" for version 4.1.0+0.
2020-10-22T06:53:00.7467953Z └ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:190
2020-10-22T06:53:00.7470212Z ┌ Warning: Overlapping ranges for julia in "/home/runner/work/General/General/M/MPFR_jll/Compat.toml" for version 4.1.0+1.
2020-10-22T06:53:00.7472396Z └ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:190
2020-10-22T06:53:00.7474585Z ┌ Warning: Overlapping ranges for julia in "/home/runner/work/General/General/M/MPFR_jll/Compat.toml" for version 4.1.0+2.

**Comment by DilumAluthge** [comment]
Is jlbuild using the latest version of Registrator.jl?

**Comment by DilumAluthge** [comment]
[noblock]

https://github.com/JuliaRegistries/General/blob/cc9c336814607c63afd3a670e9c06bb35fffc6f6/M/MPFR_jll/Compat.toml#L1-L6

**Comment by fingolfin** [comment]
To clarify: MPFR_jll 4.0.2 is supposed to be used with Julia <= 1.5.0 ; while 4.1.0 is for use with Julia >= 1.5.1. Therefore it is unsurprising that this PR fails in Julia 1.3. But in Julia 1.5.2 it should work. So I believe something more like this would be correct (modulo the fact that I am not familiar with the precise semantics used for `Compat.toml`; I was already bitten by those differing from the ones in `Project.toml` before, so I hope somebody who knows this stuff better will check this over):
```
[4] 
 JLLWrappers = "1.1.0-1" 
  
["4.0"]
 julia = "1.0-1.5.0" 
  
 ["4.1-4"] 
 julia = "1.5.1-1" 
```

To further the confusion, we also never set the Julia compat bounds in the `Project.toml` of MPFR_jll (no `julia_compat` field was specified)...

**Comment by DilumAluthge** [comment]
[noblock]

That looks right. But I'd rather not do it manually - jlbuild and Registrator.jl should do it correctly automatically.

Is jlbuild using the latest version of Registrator.jl? If not, upgrade and let's see if the bug persists.

But if jlbuild is already using the latest version of Registrator.jl, we should open an issue on Registrator.jl.

**Pull request closed without merging**
