### PR TITLE
Copulas.jl - retroactive compat bound tightening on TaylorSeries.jl

### PR DESCRIPTION
**Pull request by lrnv**
Hey, 

Following guidance from @BioTurboNick on slack and while #104849 is still pending, I try in this PR to retroactively tighten the lower bound on `TaylorSeries.jl` on recent versions of `Copulas.jl` : at the time, I did use a feature that was only available in `TaylorSeries > 0.15` but kept the old compat bound... 

These days, it results in issues such as https://github.com/lrnv/Copulas.jl/issues/207 and https://github.com/lrnv/Copulas.jl/issues/217. If these issues are usually solved by `]up` or even `]up TaylorSeries`, it is still anoying.

**Warning:** Although I have respected [these docs of the compat file](https://pkgdocs.julialang.org/v1/registries/#Registry-Compat.toml), I am **not sure** the fix I applied will be working correctly, and would appreciate some human taking the time to check it up before merging :)

### CODE REVIEW

**Comment by lrnv** [comment]
As explained in the PR, I would like this to be manually merged (its a correction of a mistakeon compat bounds). [noblock]

**Comment by BioTurboNick** [comment]
I suggest pinging a maintainer specifically, possibly this is lost in the swamp of PRs.

**Comment by BioTurboNick** [comment]
> @BioTurboNick Do you have commit access to this repo?

Nope, just being helpful :-)

**Comment by lrnv** [comment]
@ViralBShah Okay this time should be good if CI does pass.

**Pull request merged**
