### PR TITLE
remove IIF v0.5.5,

### LINKED ISSUE #1169: "AssertionError: p0 ≠ p1" with large list of packages
Maybe not something reasonable to do, but...

```julia
julia> Pkg.add(["ACME",
       "AbbrvKW",
       "ActiveAppearanceModels",
       "AdaptiveRejectionSampling",
       "ApproxBayes",
       "Augur",
       "AverageShiftedHistograms",
       "ANOVA",
       "ApproximateBayesianComputing",
       "AugmentedGaussianProcesses",
       "ArraysOfArrays",
       "ARCHModels",
       "AdvancedHMC",
       "Agents",
       "BayesNets",
       "BioEnergeticFoodWebs",
       "BlackBoxOptim",
       "Boltzmann",
       "Bootstrap",
       "Brim",
       "Brownian",
       "BooSTjl",
       "BeliefUpdaters",
       "BAT",
       "ChaosCommunications",
       "ChaosTools",
       "ClassImbalance",
       "Clustering",
       "CoDa",
       "ColorVectorSpace",
       "CombineML",
       "CoupledFields",
       "CovarianceMatrices",
       "Crispulator",
       "CrossDecomposition",
       "CumulantsUpdates",
       "CumulantsFeatures",
       "CancerSeqSim",
       "Coulter",
       "CrossMappings",
       "ChemometricsTools",
       "DSGE",
       "Dagger",
       "DataArrays",
       "DataFrames",
       "DataTables",
       "DatagenCopulaBased",
       "DependentBootstrap",
       "DirectGaussianSimulation",
       "Discreet",
       "Discretizers",
       "Distributions",
       "DynamicalSystems",
       "DynamicalSystemsBase",
       "DIVAnd",
       "DPMeansClustering",
       "DelayEmbeddings",
       "DynamicHMCModels",
       "ECharts",
       "EcologicalNetwork",
       "EventHistory",
       "ExprOptimization",
       "ExprRules",
       "EcologicalNetworks",
       "FixedEffectModels",
       "Flux",
       "ForecastEval",
       "FinEtools",
       "FlashWeave",
       "FixedEffects",
       "GLM",
       "GLMNet",
       "Gadfly",
       "GaussianMixtureTest",
       "GaussianMixtures",
       "GeoStats",
       "GeoStatsBase",
       "GeoStatsDevTools",
       "Gillespie",
       "Gnuplot",
       "Graph500",
       "GraphCentrality",
       "GraphGLRM",
       "GraphicalModelLearning",
       "GroupedErrors",
       "HypothesisTests",
       "HurdleDMR",
       "ImageQuilting",
       "ImageView",
       "Images",
       "IncrementalInference",
       "IndexedTables",
       "InteractiveFixedEffectModels",
       "InverseDistanceWeighting",
       "InvariantCausal",
       "InteractiveChaos",
       "JointMoments",
       "JuliaDB",
       "KernelDensity",
       "KernelEstimator",
       "Klara",
       "Kpax3",
       "Lasso",
       "LatinHypercubeSampling",
       "LearnBase",
       "LightGraphs",
       "LocallyWeightedRegression",
       "Lora",
       "LossFunctions",
       "LowRankModels",
       "LsqFit",
       "LyapunovExponents",
       "MCMCDiagnostics",
       "MIToS",
       "MLBase",
       "MLDataPattern",
       "MLDataUtils",
       "MLLabelUtils",
       "MachineLearning",
       "Mads",
       "Mamba",
       "MarketTechnicals",
       "Microbiome",
       "Microeconometrics",
       "Mimi",
       "MixedModels",
       "MultipleTesting",
       "MultivariateStats",
       "MotifSequenceGenerator",
       "MusicManipulations",
       "MCMCChain",
       "MRIReco",
       "MonteCarloObservable",
       "MambaModels",
       "MCMCChains",
       "MLJBase",
       "MonteCarloMeasurements",
       "NHST",
       "NLreg",
       "NMF",
       "NaiveBayes",
       "NetalignMeasures",
       "NetalignUtils",
       "NullableArrays",
       "NextGenSeqUtils",
       "OnlineStats",
       "OnlineStatsBase",
       "Optim",
       "Orchestra",
       "PDSampler",
       "PGFPlots",
       "PGFPlotsX",
       "POMDPModels",
       "POMDPToolbox",
       "ParticleFilters",
       "PhyloNetworks",
       "Plots",
       "PowerLaws",
       "POMDPPolicies",
       "Pathogen",
       "PorousMaterials",
       "PhaseSpaceIO",
       "PiecewiseDeterministicMarkovProcesses",
       "QuantEcon",
       "QuantumInformation",
       "RLEVectors",
       "RandomQuantum",
       "RecurrenceAnalysis",
       "RegERMs",
       "RegressionTables",
       "Reinforce",
       "Rifraf",
       "Robotlib",
       "RobustLeastSquares",
       "RobustStats",
       "RollingFunctions",
       "ReinforcementLearning",
       "ReinforcementLearningEnvironmentDiscrete",
       "RadiationSpectra",
       "RandomBooleanMatrices",
       "SALSA",
       "SOM",
       "ScHoLP",
       "ScikitLearn",
       "Shannon",
       "SmoothingSplines",
       "SortingLab",
       "SparseRegression",
       "SpatialEcology",
       "Spectra",
       "StackedNets",
       "Stan",
       "StatPlots",
       "Stats",
       "StatsBase",
       "StatsModels",
       "StreamStats",
       "SymmetricTensors",
       "SumProductNetworks",
       "SortMerge",
       "StatisticalRethinking",
       "StatsKit",
       "StatsMakie",
       "StatsPlots",
       "StanModels",
       "SpectralGaussianSimulation",
       "StratiGraphics",
       "TensorDecompositions",
       "TimeModels",
       "TimeSeries",
       "TimeseriesPrediction",
       "ToeplitzMatrices",
       "TexTables",
       "TimeseriesSurrogates",
       "TransferEntropy",
       "TuringModels",
       "TSML",
       "UnicodePlots",
       "UncertainData",
       "Variography",
       "Vega",
       "Wallace",
       "Watershed",
       "Whippet",
       "Winston",
       "WeightedArrays",
       "WeightedOnlineStats",
       "Yao",
       "YaoArrayRegister"])
 Resolving package versions...
ERROR: AssertionError: p0 ≠ p1
Stacktrace:
 [1] Pkg.GraphType.Graph(::Dict{Base.UUID,Set{VersionNumber}}, ::Dict{Base.UUID,Dict{Pkg.Types.VersionRange,Dict{String,Base.UUID}}}, ::Dict{Base.UUID,Dict{Pkg.Types.VersionRange,Dict{String,Pkg.Types.VersionSpec}}}, ::Dict{Base.UUID,String}, ::Dict{Base.UUID,Pkg.Types.VersionSpec}, ::Dict{Base.UUID,Pkg.Types.Fixed}, ::Bool) at /home/milan/Dev/julia/usr/share/julia/stdlib/v1.3/Pkg/src/GraphType.jl:315
 [2] deps_graph(::Pkg.Types.Context, ::Dict{Base.UUID,String}, ::Dict{Base.UUID,Pkg.Types.VersionSpec}, ::Dict{Base.UUID,Pkg.Types.Fixed}) at /home/milan/Dev/julia/usr/share/julia/stdlib/v1.3/Pkg/src/Operations.jl:431
 [3] resolve_versions!(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /home/milan/Dev/julia/usr/share/julia/stdlib/v1.3/Pkg/src/Operations.jl:316
 [4] #add#96(::Bool, ::typeof(Pkg.Operations.add), ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}, ::Array{Base.UUID,1}) at /home/milan/Dev/julia/usr/share/julia/stdlib/v1.3/Pkg/src/Operations.jl:962
 [5] #add at ./none:0 [inlined]
 [6] #add#25(::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(Pkg.API.add), ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /home/milan/Dev/julia/usr/share/julia/stdlib/v1.3/Pkg/src/API.jl:99
 [7] add at /home/milan/Dev/julia/usr/share/julia/stdlib/v1.3/Pkg/src/API.jl:69 [inlined]
 [8] #add#24 at /home/milan/Dev/julia/usr/share/julia/stdlib/v1.3/Pkg/src/API.jl:67 [inlined]
 [9] add at /home/milan/Dev/julia/usr/share/julia/stdlib/v1.3/Pkg/src/API.jl:67 [inlined]
 [10] #add#21 at /home/milan/Dev/julia/usr/share/julia/stdlib/v1.3/Pkg/src/API.jl:65 [inlined]
 [11] add(::Array{String,1}) at /home/milan/Dev/julia/usr/share/julia/stdlib/v1.3/Pkg/src/API.jl:65
 [12] top-level scope at REPL[2]:1
```

### PR DESCRIPTION
**Pull request by dehann**
Trying to fix JuliaLang/Pkg.jl#1169,  from a [suggestion](https://github.com/JuliaLang/Pkg.jl/issues/1169#issuecomment-485810282) -- cc @KristofferC (Thanks!)

follows:
- JuliaRegistries/General#49,  (v0.5.5)
- also see JuliaRegistries/General#138 (v0.5.6)

### CODE REVIEW

**Comment by fredrikekre** [comment]
Does this fix your problem? Can we just add compatibility constraints on this version instead (if that's the problem)?

**Comment by dehann** [comment]
V0.5.5 is equivalent to v0.5.6, which just adds the compatibility constraints — so as long as we can skip v0.5.5 and go to 0.5.6 it should be good to go.

**Comment by dehann** [comment]
Now I'm not sure if removing v0.5.5 does fix the assertion error.  I'm trying to manually change the registry at `~/.julia/registries/General` and think the assertion error is still there.

Can I just change the  `~/.julia/registries/General` -- what I mean is, will Pkg override any changes I make in `~/.julia/registries/General` based on github upstream?

**Comment by StefanKarpinski** [comment]
> will Pkg override any changes I make in `~/.julia/registries/General` based on github upstream?

No, this is the source of truth now.

**Comment by dehann** [comment]
Alright thanks, let me fuss with my local `~/.julia/registries/General` a bit more and will update here as needed  (this is my first adventure into the registry).  Will only get to it this afternoon though.  Thanks again.

**Comment by dehann** [comment]
cc @tonioteran for status updates on installing IncrementalInference

**Comment by fredrikekre** [comment]
How can this error be reproduced?

**Comment by dehann** [comment]
Just try installing IIF in a new environment.
```julia
]add IncrementalInference
```

**Comment by fredrikekre** [comment]
That works for me though.

**Comment by dehann** [comment]
Oh wow, okay.  Two people tried it yesterday and failed.  Are you perhaps on Pkg#master?

**Comment by fredrikekre** [comment]
Oh, I was on https://github.com/JuliaLang/julia/pull/30954

Does this PR actually fix the issue? It doesn't for me.

**Comment by dehann** [comment]
At first it wasn't clear to me whether this PR fixed the issue (just removed all traces of v0.5.5).  Now that I am able to test with local Registry, I don't think the PR is quite right yet.  I'll fix it soon -- been unusually busy the last couple days, sorry!

Thanks again for the info and help!

**Comment by dehann** [comment]
Hi, @fredrikekre, I need some more help if possible please.  I finally got back to this:  trying to fix the registry regarding a p0 != p1 error.  I tried modifying the `General` registry by either removing all references to v0.5.5, or trying to specify a compat for v0.5.6. both result in this p0 != p1 error.

My suggested solution now is to completely scrap v0.5.5 and v0.5.6 from the registry, and redo a new registration with compat requirements defined.  Is that a workable solution?  Please double check my suggested changes here.

**Comment by fredrikekre** [comment]
I think it is better to try to impose bounds on the existing releases. I'll have a look later.

**Comment by dehann** [comment]
okay, thanks -- sorry to keep bothering you with this!

**Comment by dehann** [comment]
Here is my latest attempt to fix the compat requirements:
- on a separate [new branch of my General fork -- see diff here](https://github.com/JuliaRegistries/General/compare/master...dehann:fix/iif055compat)
```
dehann@mrg-galago-01:-.julia/registries/General
[git] General:fix/iif055compat
$ git status 
On branch fix/iif055compat
nothing to commit, working directory clean

dehann@mrg-galago-01:-.julia/registries/General
[git] General:fix/iif055compat
$ git log | head -n5
commit bf99871a60b80e92c9a6a3988db0757d5f501241
Author: dehann <dehann.fourie@gmail.com>
Date:   Mon Apr 29 14:52:26 2019 -0400

    update compat
```

and the resulting output on my computer:
```
dehann@mrg-galago-01:-.julia/environments/fix1169
$ ls

dehann@mrg-galago-01:-.julia/environments/fix1169
$ julia -O3
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.3 (2018-12-18)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(v1.0) pkg> activate .

(fix1169) pkg> add IncrementalInference
  Updating registry at `~/.julia/registries/General`
┌ Warning: Some registries failed to update:
│     — `~/.julia/registries/General` — registry dirty
└ @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:157
 Resolving package versions...
ERROR: AssertionError: p0 ≠ p1
Stacktrace:
 [1] Pkg.GraphType.Graph(::Dict{Base.UUID,Set{VersionNumber}}, ::Dict{Base.UUID,Dict{Pkg.Types.VersionRange,Dict{String,Base.UUID}}}, ::Dict{Base.UUID,Dict{Pkg.Types.VersionRange,Dict{String,Pkg.Types.VersionSpec}}}, ::Dict{Base.UUID,String}, ::Dict{Base.UUID,Pkg.Types.VersionSpec}, ::Dict{Base.UUID,Pkg.Types.Fixed}, ::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/GraphType.jl:315
 [2] deps_graph(::Pkg.Types.Context, ::Dict{Base.UUID,String}, ::Dict{Base.UUID,Pkg.Types.VersionSpec}, ::Dict{Base.UUID,Pkg.Types.Fixed}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:307
 [3] resolve_versions!(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}, ::Nothing) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:371
 [4] resolve_versions! at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:316 [inlined]
 [5] #add_or_develop#62(::Array{Base.UUID,1}, ::Symbol, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1201
 [6] #add_or_develop at ./none:0 [inlined]
 [7] #add_or_develop#13(::Symbol, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:64
 [8] (::getfield(Pkg.API, Symbol("#kw##add_or_develop")))(::NamedTuple{(:mode,),Tuple{Symbol}}, ::typeof(Pkg.API.add_or_develop), ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at ./none:0
 [9] do_add!(::Dict{Symbol,Any}, ::Array{Pkg.Types.PackageSpec,1}, ::Dict{Symbol,Any}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/REPLMode.jl:709
 [10] #invokelatest#1(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Any, ::Any, ::Vararg{Any,N} where N) at ./essentials.jl:697
 [11] invokelatest(::Any, ::Any, ::Vararg{Any,N} where N) at ./essentials.jl:696
 [12] do_cmd!(::Pkg.REPLMode.PkgCommand, ::REPL.LineEditREPL) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/REPLMode.jl:603
 [13] #do_cmd#33(::Bool, ::Function, ::REPL.LineEditREPL, ::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/REPLMode.jl:577
 [14] do_cmd at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/REPLMode.jl:573 [inlined]
 [15] (::getfield(Pkg.REPLMode, Symbol("##50#53")){REPL.LineEditREPL,REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/REPLMode.jl:923
 [16] #invokelatest#1 at ./essentials.jl:697 [inlined]
 [17] invokelatest at ./essentials.jl:696 [inlined]
 [18] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/REPL/src/LineEdit.jl:2273
 [19] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:1034
 [20] run_repl(::REPL.AbstractREPL, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:191
 [21] (::getfield(Base, Symbol("##718#720")){Bool,Bool,Bool,Bool})(::Module) at ./client.jl:355
 [22] #invokelatest#1 at ./essentials.jl:697 [inlined]
 [23] invokelatest at ./essentials.jl:696 [inlined]
 [24] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:339
 [25] exec_options(::Base.JLOptions) at ./client.jl:277
 [26] _start() at ./client.jl:425

(fix1169) pkg> 
```

**Comment by dehann** [comment]
Hi @fredrikekre , thank you very much!  Sorry I didn't get there by myself, but things make more sense to me now.  I was working on the assumption that pre-existing versions should have still worked -- but see now that the new Registrator method requires all versions relating to Julia 0.7+ to have `compat` defined.  Also, I did see the self dependence issue too, but figured it had not been a problem thus far and seemed unrelated.  

Either way, thank you again!  I should be able to figure the tomls in registry out better in the future.

**Comment by dehann** [comment]
In case anybody else arrives here due to `ERROR: AssertionError: p0 ≠ p1`...

I think this IncrementalInference package would have failed in a similar way based on existing version `v0.4 - v0.5.4` even if I had changed nothing.  This retroactive issue was masked under an new tag of `v0.5.5` that coincided with the change over from METADATA.jl to Registries.  I was missing the compat requirements for Julia for all versions supporting Julia 0.7 and beyond.  The tag IIF v0.5.5 had little to do with it, other than the same issue for all versions `v0.4-v0.5.4`.

Thanks again for the Julia guys' help!  I was a little lost at first, and the fix turned out to be easy, as long as you know what had happened.

**Pull request closed without merging**
