### PR TITLE
New version: Cbc_jll v2.10.5+2

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package Cbc_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/Cbc_jll.jl
* Version: v2.10.5+2
* Revision on Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/commit/adaac1c3d733beacacaf59988bdf52e44242f92c

### CODE REVIEW

**Comment by odow** [comment]
[noblock] Weird. I was under the impression that if it passed Yggdrasil, it was okay to load. I'll take a look

**Comment by giordano** [comment]
That's not _always_ the case.  I'm also a bit confused by the error because it works locally, but I'd tend to trust CI run here, it's a more minimal system than my computer

[noblock]

**Comment by odow** [comment]
[noblock]

It seems like we built 2.10.5 initially https://github.com/JuliaPackaging/Yggdrasil/issues/509#issuecomment-609483971, but for some reason changed that to 2.10.3 https://github.com/jump-dev/Cbc.jl/pull/133#issuecomment-611011549. (I can't find/don't remember why. @ViralBShah has probably also forgotten.)

I'm confused by the error because `getRowNames` has been in Clp forever, and there were only minor changes between Cbc 2.10.3 and 2.10.5: https://github.com/coin-or/Cbc/compare/releases/2.10.3...releases/2.10.5

**Comment by giordano** [comment]
Yeah, I don't know why we had older versions of 2.10.5.  If you want we can try to merge this PR and see what happens.  It works for me as well locally, so it isn't straightforward for me to debug (would need to log into a GitHub Actions runner....)

**Comment by odow** [comment]
Cbc.jl uses Cbc_jll pinned at 2.10.3, so nothing should break if we merge this. I wonder if we should just remove the patch and release as 2.10.5+3, since it's unlikely that anyone is actually using Cbc_jll instead of Cbc.jl.

**Comment by giordano** [comment]
Still same error.  I don't understand it and frankly and I don't have much time to debug it while it works locally (tried again just now).  I'm going to merge it, but please report to Yggdrasil if you know of issues

**Comment by odow** [comment]
Thanks for the time you spend on this. I'll have a go with the JLL.

**Pull request merged**
