### PR TITLE
Fix SPIRV_LLVM_Translator_jll compat bounds.

### PR DESCRIPTION
**Pull request by maleadt**
Fixes the current CI failure on master. Will merge this quickly so that new PRs aren't blocked on this.

### CODE REVIEW

**Comment by maleadt** [comment]
FWIW, this failure was not present in the individual PRs: https://github.com/JuliaRegistries/General/pull/36095 https://github.com/JuliaRegistries/General/pull/36096 https://github.com/JuliaRegistries/General/pull/36097. Another case of 'CI should run on the merge commit'.

**Comment by maleadt** [comment]
I had already run into this in the past, but decided to de-duplicate the bounds again in the above PRs, e.g. https://github.com/JuliaRegistries/General/compare/a4b790edc6f894b250741316cb03a2d29188987a..4a918e56b6b3db6a404fa6d9a12991919fa35ff1. This because package registration otherwise introduces overlapping compat bounds for some reason. But I forgot that CI currently requires the bounds to be compressed...

**Comment by giordano** [comment]
> Another case of 'CI should run on the merge commit'.

Doesn't GHA run on the merge commit?

**Comment by maleadt** [comment]
Ah, maybe it does, but it didn't re-run (or 'require' a re-run like `bors r+`) after merging one of those PRs, and it was the combination of all three that caused the issue.

**Comment by giordano** [comment]
Right, no, it doesn't rerun if the target branch moves because the merge commit associated to the pull request isn't automatically updated.

**Pull request merged**
