### PR TITLE
Change location of RedPitayaDAQServer

### PR DESCRIPTION
**Pull request by tknopp**
Hi, I am not sure if this is correct what I am trying here. I want to move this package into its main repository into a subfolder. So there is RedPitayaDAQServer and there is RedPitayaDAQServer.jl, which is only a language binding to the former.

### CODE REVIEW

**Comment by tknopp** [comment]
@DilumAluthge @KristofferC: Hi, I am not sure what the CI error means. Do I need to change the version when I change the URL? If yes, I do not know how to do that manually (i.e. how to get the UUID in the version file). Any help is much appreciated.

**Comment by fredrikekre** [comment]
Looks good but are the old tree shas available in the new repo?

**Comment by tknopp** [comment]
I don't think so. What I have done is to import the source code into another repository. A simple rename of the repo is in this case not possible since I want the registered package to move into a subfolder of the new package.
Was it wrong what I did?

**Comment by fredrikekre** [comment]
> Was it wrong what I did?

Not but not enough I think. Can you add older versions of this package with this branch? I don't think so since the old trees are not available. You should be able to import the old trees in (perhaps orphan) branches and tag them, I think that is the easiest way.

**Comment by tknopp** [comment]
Hm, I kind of see the issue, but do not have a clou how to do that. My git foo seems to be not good enough. @timholy: am I right that you did with snoopcompile what I am aiming to do? I.e. move a package into a subfolder of another gitrepo. There seems to be no documentation on this yet so any advice on the „moving“ part including these tree hashes would be nice.

**Comment by tknopp** [comment]
So this is on hold until I figure out how to move the git trees.

**Comment by timholy** [comment]
No, I split one package into pieces. All the pieces started in the same repo.

**Comment by tknopp** [comment]
Ah thanks Tim, so then I need to pioneer this ;-)

**Comment by fredrikekre** [comment]
I think this might be sufficient:
```
$ git clone https://github.com/fredrikekre/RedPitayaDAQServer
Cloning into 'RedPitayaDAQServer'...
remote: Enumerating objects: 505, done.
remote: Counting objects: 100% (505/505), done.
remote: Compressing objects: 100% (298/298), done.
remote: Total 2400 (delta 272), reused 396 (delta 181), pack-reused 1895
Receiving objects: 100% (2400/2400), 12.70 MiB | 2.09 MiB/s, done.
Resolving deltas: 100% (1388/1388), done.
Checking connectivity... done.

$ cd RedPitayaDAQServer/

$ git remote add oldrepo https://github.com/tknopp/RedPitayaDAQServer.jl

$ git fetch oldrepo 
warning: no common commits
remote: Enumerating objects: 321, done.
remote: Counting objects: 100% (321/321), done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 1228 (delta 228), reused 266 (delta 184), pack-reused 907
Receiving objects: 100% (1228/1228), 1.59 MiB | 502.00 KiB/s, done.
Resolving deltas: 100% (808/808), done.
From https://github.com/tknopp/RedPitayaDAQServer.jl
 * [new branch]      changesOfProtocol -> oldrepo/changesOfProtocol
 * [new branch]      gh-pages   -> oldrepo/gh-pages
 * [new branch]      master     -> oldrepo/master
 * [new branch]      nh/daq     -> oldrepo/nh/daq
 * [new branch]      release-julia-0.6 -> oldrepo/release-julia-0.6
 * [new branch]      test-branch -> oldrepo/test-branch
 * [new tag]         v0.1.0     -> v0.1.0
 * [new tag]         v0.1.1     -> v0.1.1

$ git push origin v0.1.0
Username for 'https://github.com': fredrikekre
Password for 'https://fredrikekre@github.com': 
Counting objects: 552, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (201/201), done.
Writing objects: 100% (552/552), 1.18 MiB | 1.86 MiB/s, done.
Total 552 (delta 332), reused 552 (delta 332)
remote: Resolving deltas: 100% (332/332), done.
To https://github.com/fredrikekre/RedPitayaDAQServer
 * [new tag]         v0.1.0 -> v0.1.0

$ git push origin v0.1.1
Counting objects: 37, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (22/22), done.
Writing objects: 100% (37/37), 212.54 KiB | 0 bytes/s, done.
Total 37 (delta 24), reused 27 (delta 15)
remote: Resolving deltas: 100% (24/24), completed with 10 local objects.
To https://github.com/fredrikekre/RedPitayaDAQServer
 * [new tag]         v0.1.1 -> v0.1.1
```

**Comment by fredrikekre** [comment]
Which resulted in https://github.com/fredrikekre/RedPitayaDAQServer/tags which are checkout-able now.

**Comment by tknopp** [comment]
https://github.com/tknopp/RedPitayaDAQServer/tags

**Comment by tknopp** [comment]
thank you @fredrikekre!

So then this seems ready to go?

**Pull request merged**
