### PR TITLE
Update CONTRIBUTING.md for new triage-level powers

### PR DESCRIPTION
**Pull request by ericphanson**
To be merged once https://github.com/JuliaRegistries/RegistryCI.jl/pull/536 is operational on General

Created by: @ericphanson
extra line

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Might as well use this PR to do a quick test.

[merge approved]

**Comment by ericphanson** [comment]
Nice, looks like that run successfully and correctly decided not to apply the label. Now I've edited myself in to the OP, let's try the other path:

[merge approved]

**Comment by ericphanson** [comment]
uh oh, looks like maybe the regex didn't match? https://github.com/JuliaRegistries/General/actions/runs/7703098268/job/20992809499

**Comment by ericphanson** [comment]
I think I was missing a newline after the "Created by" in the OP.

[merge approved]

**Comment by ericphanson** [comment]
Had an extra space before the newline....

[merge approved]

**Comment by DilumAluthge** [comment]
@ericphanson Can we add some unit tests for this regex to the RegistryCI.jl test suite?

**Comment by DilumAluthge** [comment]
Can you use the GitHub API locally to pull the contents of the PR description? So we can see exactly what the characters are.

**Comment by ericphanson** [comment]
I think it's something to do with the newline at the end. I think we should just go back to the regex I had before, I had tested that one thoroughly on another repo and it was working well.

**Comment by DilumAluthge** [comment]
GitHub is giving `\r\n` instead of `\n` for the newline.

**Comment by ericphanson** [comment]
https://github.com/JuliaRegistries/General/pull/99796

**Comment by ericphanson** [comment]
[merge approved]

**Comment by ericphanson** [comment]
Progress!

```
GraphQL: Your token has not been granted the required scopes to execute this query. The 'login' field requires one of the following scopes: ['read:org'], but your token has only been granted the: ['delete_repo', 'read:user', 'repo', 'workflow'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens., Your token has not been granted the required scopes to execute this query. The 'name' field requires one of the following scopes: ['read:org', 'read:discussion'], but your token has only been granted the: ['delete_repo', 'read:user', 'repo', 'workflow'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens., Your token has not been granted the required scopes to execute this query. The 'slug' field requires one of the following scopes: ['read:org', 'read:discussion'], but your token has only been granted the: ['delete_repo', 'read:user', 'repo', 'workflow'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
```
https://github.com/JuliaRegistries/General/actions/runs/7703569853/job/20994230574

**Comment by ericphanson** [comment]
can you update the token @DilumAluthge ? It sounds like it additionally just needs `read:org` and that would fix the 3 errors it's reporting

**Comment by ericphanson** [comment]
ok let's try again

[merge approved]

**Comment by DilumAluthge** [comment]
Nice!

And just to check it doesn't work for me:

[merge approved]

**Pull request merged**
