### PR TITLE
fix compat for Plots

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
ref: https://github.com/JuliaPlots/Plots.jl/pull/2727
Can someone confirm, that this is a valid correction?

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
Should be correct now, checked with RegistryTools

**Comment by giordano** [comment]
I'm not an expert of compat bounds, but Travis doesn't seem to agree that the new bounds are correct

**Comment by BeastyBlacksmith** [comment]
Is fixed

**Comment by BeastyBlacksmith** [comment]
@DilumAluthge anything missing to get this merged?

**Pull request merged**
