### PR TITLE
JLL Registration: JuliaBinaryWrappers/HDF5_jll.jl-v1.10.5+2

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package HDF5_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/HDF5_jll.jl
* Version: v1.10.5+2

### CODE REVIEW

**Comment by musm** [comment]
@giordano sigh, seems like we do indeed have a merge conflict

**Comment by giordano** [comment]
I think I've been too fast merging and the repo didn't have the time to got updated :disappointed:

Either someone (with write permissions here) should merge master onto this branch and fix the conflict, or someone (no write permissions required) just opens a new PR

**Comment by musm** [comment]
That didn't' seem to work. We'll need some manual intervention here.

**Comment by musm** [comment]
@ararslan  sorry to bother, but do you think you could help us out here?

**Comment by giordano** [comment]
I've opened #6268.  @staticfloat the parent commit of https://github.com/JuliaRegistries/General/commit/33138844325ff355f98585a47c69f08a25800eaf is https://github.com/JuliaRegistries/General/commit/448864e0dd53a825269666fb9e5712d7bb9969a3, which is about 12 hours older.  Did syncing of the repo stop working?

**Comment by musm** [comment]
merge?

**Pull request merged**
