### PR TITLE
Convert `0.7-1` to `["0.7", "1"]`, et cetera

### PR DESCRIPTION
**Pull request by DilumAluthge**
cc: @fredrikekre 

Currently, the General registry has many Julia compat entries of the form `0.7-1` or something similar.

But there are no versions of Julia after 0.7 but before 1.0. So these compat entries don't really make sense.

This pull request converts entries of the form `0.7-1` to `["0.7", "1"]`, `0.7-1.0` to `["0.7", "1.0"]`, et cetera.

Here is the script that I used to generate this pull request:
```julia
import Pkg

for (root, dirs, files) in walkdir(".")
    old_to_new = Dict{String, Vector{String}}()

    old_to_new["0.7-1"] = ["0.7", "1"]
    old_to_new["0.7-1.0"] = ["0.7", "1.0"]
    old_to_new["0.7-1.0.0"] = ["0.7", "1.0.0"]
    old_to_new["0.7.0-1"] = ["0.7.0", "1"]
    old_to_new["0.7.0-1.0"] = ["0.7.0", "1.0"]
    old_to_new["0.7.0-1.0.0"] = ["0.7.0", "1.0.0"]

    old_to_new["0.7-1.1"] = ["0.7", "1.1"]
    old_to_new["0.7-1.1.0"] = ["0.7", "1.1.0"]
    old_to_new["0.7.0-1.1"] = ["0.7.0", "1.1"]
    old_to_new["0.7.0-1.1.0"] = ["0.7.0", "1.1.0"]

    old_to_new["0.7-1.2"] = ["0.7", "1.2"]
    old_to_new["0.7-1.2.0"] = ["0.7", "1.2.0"]
    old_to_new["0.7.0-1.2"] = ["0.7.0", "1.2"]
    old_to_new["0.7.0-1.2.0"] = ["0.7.0", "1.2.0"]

    for file in files
        filename = joinpath(root, file)
        if endswith(filename, "Compat.toml")
            i_modified_this_compat_file = false
            compat = Pkg.TOML.parsefile(filename)
            for pair in compat
                compat_entries = pair[2]
                for entry in compat_entries
                    name = entry[1]
                    value = entry[2]
                    if lowercase(strip(name)) == "julia"
                        value_nowhitespace = replace(value, r"\s"=>"")
                        if haskey(old_to_new, value_nowhitespace)
                            compat[pair[1]][name] = old_to_new[value_nowhitespace]
                            i_modified_this_compat_file = true
                        end
                    end
                end
            end
            if i_modified_this_compat_file
                rm(filename; force = true, recursive = true)
                open(filename, "w") do io
                    Pkg.TOML.print(io, compat; sorted = true, by = key -> (Pkg.Types.project_key_order(key), key))
                end
            end
        end
    end
end
```

### CODE REVIEW

**Comment by fredrikekre** [comment]
Rerun and rebase now that I have merged stuff?

**Comment by DilumAluthge** [comment]
> Rerun and rebase now that I have merged stuff?

Done.

**Comment by DilumAluthge** [comment]
@fredrikekre I gave you push access to my fork of General. I think this PR becomes outdated as soon as automerge merges anything. So I think you will have to do this:
1. Wait for an automerge cron job to complete.
2. As soon as the automerge cron job has finished, rerun this script and force-push.
3. Merge immediately before it's too late.

**Comment by tlnagy** [comment]
I'm pretty sure that this would resolve some issues I've run into updating old `REQUIRES` code to `Project.toml` ones, e.g. https://github.com/JuliaRegistries/General/pull/6638 is hung up for this reason since the automerger thinks I'm restricting the versions going from `0.7-1` to `["0.7", "1"]`

**Comment by DilumAluthge** [comment]
See https://github.com/JuliaRegistries/General/pull/7500

**Pull request closed without merging**
