### PR TITLE
Move Twitter workflow to upon PR merge instead of PR open

### PR DESCRIPTION
**Pull request by ericphanson**
using https://stackoverflow.com/a/59588725/12486544 and https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges

I'm not 100% sure this will work correctly... hard to test these things.

### CODE REVIEW

**Review by logankilpatrick — APPROVED** [review]

**Comment by ericphanson** [comment]
Let's give it a try

**Review by giordano — APPROVED** [review]
Looks good as far as I can tell 👍

**Comment by ericphanson** [comment]
Sorry @logankilpatrick looks like I didn't copy over the formatting change from https://github.com/JuliaRegistries/General/pull/60880 - want to a make a PR against the new workflow?

**Comment by logankilpatrick** [comment]
I update it in #4818af2

**Comment by ericphanson** [comment]
Ah just saw that, alright! Now we wait for a package to be merged :)

**Comment by logankilpatrick** [comment]
Yes, looks like #60696 is close

**Pull request merged**
