### PR TITLE
Fix CuArray compatibility with NNlib

### LINKED ISSUE #327: Wrong NNlib bounds wiith CuArrays 1.0.2
**Describe the bug**
`using CuArrays` fails during precompilation with `LoadError: UndefVarError: DenseConvDims not defined`

**To Reproduce**
```
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0
 _/ |\__'_|_|_|\__'_|  |
|__/                   |

julia> using CuArrays
[ Info: Precompiling CuArrays [3a865a2d-5b23-5a0f-bc46-62713ec82fae]
WARNING: could not import NNlib.spatial_dims into CUDNN
ERROR: LoadError: LoadError: LoadError: UndefVarError: DenseConvDims not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] include at ./boot.jl:326 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /home/jschnaitter/.julia/packages/CuArrays/PwSdF/src/dnn/CUDNN.jl:1
 [6] top-level scope at none:0
 [7] include at ./boot.jl:326 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include at ./sysimg.jl:29 [inlined]
 [10] include(::String) at /home/jschnaitter/.julia/packages/CuArrays/PwSdF/src/CuArrays.jl:3
 [11] top-level scope at none:0
 [12] include at ./boot.jl:326 [inlined]
 [13] include_relative(::Module, ::String) at ./loading.jl:1038
 [14] include(::Module, ::String) at ./sysimg.jl:29
 [15] top-level scope at none:2
 [16] eval at ./boot.jl:328 [inlined]
 [17] eval(::Expr) at ./client.jl:404
 [18] top-level scope at ./none:3
in expression starting at /home/jschnaitter/.julia/packages/CuArrays/PwSdF/src/dnn/libcudnn.jl:265
in expression starting at /home/jschnaitter/.julia/packages/CuArrays/PwSdF/src/dnn/CUDNN.jl:35
in expression starting at /home/jschnaitter/.julia/packages/CuArrays/PwSdF/src/CuArrays.jl:52
ERROR: Failed to precompile CuArrays [3a865a2d-5b23-5a0f-bc46-62713ec82fae] to /home/jschnaitter/.julia/compiled/v1.1/CuArrays/7YFE0.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853
```

**Expected behavior**
Expected the package to load

**Build log**
```
(v1.1) pkg> build
  Building ZipFile ─────────→ `~/.julia/packages/ZipFile/YHTbb/deps/build.log`
  Building CodecZlib ───────→ `~/.julia/packages/CodecZlib/9jDi1/deps/build.log`
  Building MbedTLS ─────────→ `~/.julia/packages/MbedTLS/X4xar/deps/build.log`
  Building CUDAdrv ─────────→ `~/.julia/packages/CUDAdrv/3cR2F/deps/build.log`
  Building LLVM ────────────→ `~/.julia/packages/LLVM/tg8MX/deps/build.log`
  Building CUDAnative ──────→ `~/.julia/packages/CUDAnative/wU0tS/deps/build.log`
  Building Conda ───────────→ `~/.julia/packages/Conda/CpuvI/deps/build.log`
  Building FFTW ────────────→ `~/.julia/packages/FFTW/p7sLQ/deps/build.log`
  Building CuArrays ────────→ `~/.julia/packages/CuArrays/PwSdF/deps/build.log`
  Building ZMQ ─────────────→ `~/.julia/packages/ZMQ/ABGOx/deps/build.log`
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/fvheQ/deps/build.log`
  Building IJulia ──────────→ `~/.julia/packages/IJulia/gI2uA/deps/build.log`
```

**Environment details (please complete this section)**
Details on Julia:

Julia 1.1.0 running on CentOS 7.4 x86_64
```
julia> versioninfo()
Julia Version 1.1.0
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  LMOD_FAMILY_JULIA_VERSION = julia-1.1.0
  LMOD_FAMILY_JULIA = julia

```

CUDA: CUDA 10.0 Driver Version: 410.79

**Additional context**
contents of `~/.julia/packages/CuArrays/deps/ext.jl`:

```
# autogenerated file, do not edit
const libcufft = "/apps/cuda/cuda-10.0/lib64/libcufft.so"
const libcublas = "/apps/cuda/cuda-10.0/lib64/libcublas.so"
const configured = true
const libcusparse = "/apps/cuda/cuda-10.0/lib64/libcusparse.so"
const libcusolver = "/apps/cuda/cuda-10.0/lib64/libcusolver.so"
const libcurand = "/apps/cuda/cuda-10.0/lib64/libcurand.so"
const libcudnn = "/apps/cuda/cuda-10.0/lib64/libcudnn.so"
```

### PR DESCRIPTION
**Pull request by maleadt**
ref https://github.com/JuliaGPU/CuArrays.jl/commit/da7107bb2f20d8ed8147b1b148e0db93b5d59bc7
fix https://github.com/JuliaGPU/CuArrays.jl/issues/327

OT: what does the `-0` mean? CuArrays `1-1.0.1` just has `NNlib = "0.5"`.

### CODE REVIEW

**Comment by KristofferC** [comment]
> OT: what does the -0 

Compatible up to 1.0  (exclusive).

**Comment by KristofferC** [comment]
It should be:

> OT: what does the -0 mean

Compatible up to 1.0 (exclusive)

> `NNlib = "0.5".`

Compatible 0.5 - 0.6 (exclusive). This is "semver notation" for pre 1.0.

**Comment by maleadt** [comment]
> This is "semver notation" for pre 1.0.

Right; then why did JuliaRegistrator convert the `NNlib = "0.5, 0.6"` compatibility line in Project.toml to a non semver-compatible `0.5-0`? I had expected it to be just `0.5-0.6` is why I was confused by the `-0`.

https://github.com/JuliaGPU/CuArrays.jl/blob/v1.0.2/Project.toml#L34
https://github.com/JuliaRegistries/General/pull/288/files#diff-19dac3c8014f2b183d8c7bac1804f85eR94

**Comment by KristofferC** [comment]
There was some normalization that ran but I thought that was a one time thing. This looks wrong, yes. cc @StefanKarpinski

**Comment by StefanKarpinski** [comment]
Because when I wanted to follow semver strictly, people didn't like that it would require people to change their version bounds when new 0.x versions were released. So for now normalization is done considering all 0.x versions to be compatible. Unless there's a 0.7 version to be incompatible with, `0.5-0.6` is equivalent to `0.5-0`.

**Comment by maleadt** [comment]
Is this good to go? Users are running into this.

**Pull request merged**
