### PR TITLE
normalize the version info in the registry

### PR DESCRIPTION
**Pull request by KristofferC**
This PR "normalizes" the version info in the registry by simply `Compress.load`-ing it and then immediately `Compress.save` it. Other changes to the registry will then be less noisy.

The script used:

```jl
using UUIDs
using Pkg

struct Package
    name::String
    path::String
    max_version::VersionNumber
end

function normalizeit(regpath)
    stdlibs = readdir(Sys.STDLIB)
    packages = Dict{UUID, Package}()
    reg = Pkg.TOML.parsefile(joinpath(regpath, "Registry.toml"))
    for (uuid, data) in reg["packages"]
        pkgpath = joinpath(regpath, data["path"])
        name = data["name"]
        versions = Pkg.Operations.load_versions(pkgpath)
        max_version = maximum(keys(versions))
        packages[UUID(uuid)] = Package(name, pkgpath, max_version)
    end

    for (uuid, pkg) in packages
        pkgpath = joinpath(regpath, pkg.path)
        compatfile = joinpath(pkgpath, "Compat.toml")
        depfile = joinpath(pkgpath, "Deps.toml")

        for file in (compatfile, depfile)
            if isfile(file)
                data = Pkg.Compress.load(file)
                Pkg.Compress.save(file, data)
            end
        end
    end
end
```

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
This is going to pick up merge conflicts pretty quickly. So you’ll need to merge it as soon as you rerun it.

**Comment by KristofferC** [comment]
Yep, will do!

**Comment by DilumAluthge** [comment]
Bump @KristofferC do you want to rerun your script and merge this PR?

**Comment by KristofferC** [comment]
Yes, I will do that,

**Pull request merged**
