### PR TITLE
Yank DirectSum 0.5.11

### PR DESCRIPTION
**Pull request by DilumAluthge**
Closes https://github.com/JuliaRegistries/General/pull/17272

### CODE REVIEW

**Comment by chakravala** [comment]
I dont quite understand what this does, could you explain?

**Comment by DilumAluthge** [comment]
Yep. Yanking is how we "remove" a version from the registry.

**Comment by DilumAluthge** [comment]
Pkg will never try to install a yanked version.

**Comment by chakravala** [comment]
Does that mean I need to re-register as v0.5.12?

**Comment by DilumAluthge** [comment]
> Does that mean I need to re-register as v0.5.12?

Correct. The SemVer spec says you can modify or delete a version once it has been released.

So just make your next registration as v0.5.12.

**Comment by DilumAluthge** [comment]
cc me in your registration for v0.5.12, and I will merge it manually so you can get it released ASAP.

**Pull request merged**
