### PR TITLE
Fix Deps due to compat override on DiffEqBase DataStructures

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Fixes deps to match https://github.com/JuliaRegistries/General/pull/20415

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@StefanKarpinski ?

**Comment by DilumAluthge** [comment]
It looks right to me.

**Comment by DilumAluthge** [comment]
You never do know though, sometimes these changes can break subtly. To be safe, you can check this registry branch out locally and make sure that you can Pkg.add the relevant packages without error.

**Comment by DilumAluthge** [comment]
My dream is a CI specifically for this kind of PR (compat related PRs) that automatically checks that Pkg.add works for all the relevant packages.

I haven't figured out how to do this in a performant way. CI that Pkg.adds all of the packages in the registry is far too slow. So we need a CI step that looks at the diff of a PR, figures out which packages are impacted, and then only tests the Pkg.add (and maybe also the import) of just the packages impacted by the PR.

**Review by DilumAluthge — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
```julia
(@v1.5) pkg> activate Tester
 Activating new environment at `C:\Users\accou\.julia\dev\DiffEqGPU\Tester\Project.toml`

(Tester) pkg> add DiffEqBase
  Resolving package versions...
  Installed DiffEqBase ─ v6.46.1
Updating `C:\Users\accou\.julia\dev\DiffEqGPU\Tester\Project.toml`
  [2b5f629d] + DiffEqBase v6.46.1
Updating `C:\Users\accou\.julia\dev\DiffEqGPU\Tester\Manifest.toml`
  [4fba245c] + ArrayInterface v2.12.0
  [d360d2e6] + ChainRulesCore v0.9.6
  [34da2185] + Compat v3.14.0
  [adafc99b] + CpuId v0.2.2
  [864edb3b] + DataStructures v0.18.2
  [2b5f629d] + DiffEqBase v6.46.1
  [ffbed154] + DocStringExtensions v0.8.3
  [069b7b12] + FunctionWrappers v1.1.1
  [42fd0dbc] + IterativeSolvers v0.8.4
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [2ee39098] + LabelledArrays v1.3.0
  [bdcacae8] + LoopVectorization v0.8.24
  [1914dd2f] + MacroTools v0.5.5
  [46d2c3a1] + MuladdMacro v0.2.2
  [6fe1bfb0] + OffsetArrays v1.1.2
  [bac558e1] + OrderedCollections v1.3.0
  [d96e819e] + Parameters v0.12.1
  [3cdcf5f2] + RecipesBase v1.0.2
  [731186ca] + RecursiveArrayTools v2.6.0
  [f2c3362d] + RecursiveFactorization v0.1.4
  [ae029012] + Requires v1.0.1
  [f2b01f46] + Roots v1.0.5
  [21efa798] + SIMDPirates v0.8.24
  [476501e8] + SLEEFPirates v0.5.5
  [90137ffa] + StaticArrays v0.12.4
  [3783bdb8] + TableTraits v1.0.0
  [a2a6695c] + TreeViews v0.3.0
  [3a884ed6] + UnPack v1.0.2
  [3d5dd08c] + VectorizationBase v0.12.32
  [700de1a5] + ZygoteRules v0.2.0
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8bb1440f] + DelimitedFiles
  [8ba89e20] + Distributed
  [b77e0a4c] + InteractiveUtils
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [1a1011a3] + SharedArrays
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [4607b0f0] + SuiteSparse
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode

(Tester) pkg> add OrdinaryDiffEq
  Resolving package versions...
Updating `C:\Users\accou\.julia\dev\DiffEqGPU\Tester\Project.toml`
  [1dea7af3] + OrdinaryDiffEq v5.42.4
Updating `C:\Users\accou\.julia\dev\DiffEqGPU\Tester\Manifest.toml`
  [79e6a3ab] + Adapt v2.0.2
  [ec485272] + ArnoldiMethod v0.0.4
  [bbf7d656] + CommonSubexpressions v0.3.0
  [e66e0078] + CompilerSupportLibraries_jll v0.3.3+0
  [163ba53b] + DiffResults v1.0.2
  [b552c78f] + DiffRules v1.0.1
  [b4f34e82] + Distances v0.9.0
  [d4d017d3] + ExponentialUtilities v1.8.0
  [9aa1b823] + FastClosures v0.3.2
  [6a86dc24] + FiniteDiff v2.6.0
  [f6369f11] + ForwardDiff v0.10.12
  [01680d73] + GenericSVD v0.3.0
  [d25df0c9] + Inflate v0.1.2
  [093fc24a] + LightGraphs v1.3.0
  [d3d80556] + LineSearches v7.1.0
  [d41bc354] + NLSolversBase v7.7.0
  [2774e3e8] + NLsolve v4.4.1
  [77ba4419] + NaNMath v0.3.4
  [efe28fd5] + OpenSpecFun_jll v0.5.3+3
  [1dea7af3] + OrdinaryDiffEq v5.42.4
  [189a3867] + Reexport v0.2.0
  [699a6c99] + SimpleTraits v0.9.3
  [47a9eef4] + SparseDiffTools v1.10.0
  [276daf66] + SpecialFunctions v0.10.3
  [19fa3120] + VertexSafeGraphs v0.1.2

(Tester) pkg> add StochasticDiffEq
  Resolving package versions...
  Installed FillArrays ──── v0.9.5
  Installed Distributions ─ v0.23.10
Updating `C:\Users\accou\.julia\dev\DiffEqGPU\Tester\Project.toml`
  [789caeaf] + StochasticDiffEq v6.25.1
Updating `C:\Users\accou\.julia\dev\DiffEqGPU\Tester\Manifest.toml`
  [9a962f9c] + DataAPI v1.3.0
  [c894b116] + DiffEqJump v6.10.1
  [77a26b50] + DiffEqNoiseProcess v5.3.0
  [31c24e10] + Distributions v0.23.10
  [1a297f60] + FillArrays v0.9.5
  [e1d29d7a] + Missings v0.4.4
  [90014a1f] + PDMats v0.10.0
  [e409e4f3] + PoissonRandom v0.4.0
  [1fd47b50] + QuadGK v2.4.1
  [e6cf234a] + RandomNumbers v1.4.0
  [ae5879a3] + ResettableStacks v1.0.0
  [79098fc4] + Rmath v0.6.1
  [f50d1b31] + Rmath_jll v0.2.2+1
  [a2af1166] + SortingAlgorithms v0.3.1
  [2913bbd2] + StatsBase v0.33.1
  [4c63d2b9] + StatsFuns v0.9.5
  [789caeaf] + StochasticDiffEq v6.25.1

(Tester) pkg> add DataStructures
  Resolving package versions...
Updating `C:\Users\accou\.julia\dev\DiffEqGPU\Tester\Project.toml`
  [864edb3b] + DataStructures v0.18.2
No Changes to `C:\Users\accou\.julia\dev\DiffEqGPU\Tester\Manifest.toml`

(Tester) pkg> add DataStructures@0.17
  Resolving package versions...
Updating `C:\Users\accou\.julia\dev\DiffEqGPU\Tester\Project.toml`
  [864edb3b] ↓ DataStructures v0.18.2 ⇒ v0.17.20
  [2b5f629d] ↓ DiffEqBase v6.46.1 ⇒ v6.44.3
  [1dea7af3] ↓ OrdinaryDiffEq v5.42.4 ⇒ v5.42.3
  [789caeaf] ↓ StochasticDiffEq v6.25.1 ⇒ v6.25.0
Updating `C:\Users\accou\.julia\dev\DiffEqGPU\Tester\Manifest.toml`
  [1520ce14] + AbstractTrees v0.3.3
  [88cd18e8] + ConsoleProgressMonitor v0.1.2
  [864edb3b] ↓ DataStructures v0.18.2 ⇒ v0.17.20
  [2b5f629d] ↓ DiffEqBase v6.46.1 ⇒ v6.44.3
  [c894b116] ↓ DiffEqJump v6.10.1 ⇒ v6.10.0
  [31c24e10] ↓ Distributions v0.23.10 ⇒ v0.23.8
  [1a297f60] ↓ FillArrays v0.9.5 ⇒ v0.8.14
  [1d6d02ad] + LeftChildRightSiblingTrees v0.1.2
  [093fc24a] ↑ LightGraphs v1.3.0 ⇒ v1.3.3
  [e6f89c97] + LoggingExtras v0.4.2
  [1dea7af3] ↓ OrdinaryDiffEq v5.42.4 ⇒ v5.42.3
  [33c8b6b6] + ProgressLogging v0.1.3
  [92933f4c] + ProgressMeter v1.3.2
  [789caeaf] ↓ StochasticDiffEq v6.25.1 ⇒ v6.25.0
  [5d786b92] + TerminalLoggers v0.1.2

(Tester) pkg> free DataStructures
ERROR: expected package `DataStructures [864edb3b]` to be pinned, tracking a path, or tracking a repository

(Tester) pkg> free DataStructures
ERROR: expected package `DataStructures [864edb3b]` to be pinned, tracking a path, or tracking a repository

(Tester) pkg> add DataStructures@0.18
  Resolving package versions...
Updating `C:\Users\accou\.julia\dev\DiffEqGPU\Tester\Project.toml`
  [864edb3b] ↑ DataStructures v0.17.20 ⇒ v0.18.2
  [2b5f629d] ↑ DiffEqBase v6.44.3 ⇒ v6.46.1
  [1dea7af3] ↑ OrdinaryDiffEq v5.42.3 ⇒ v5.42.4
  [789caeaf] ↑ StochasticDiffEq v6.25.0 ⇒ v6.25.1
Updating `C:\Users\accou\.julia\dev\DiffEqGPU\Tester\Manifest.toml`
  [1520ce14] - AbstractTrees v0.3.3
  [88cd18e8] - ConsoleProgressMonitor v0.1.2
  [864edb3b] ↑ DataStructures v0.17.20 ⇒ v0.18.2
  [2b5f629d] ↑ DiffEqBase v6.44.3 ⇒ v6.46.1
  [c894b116] ↑ DiffEqJump v6.10.0 ⇒ v6.10.1
  [31c24e10] ↑ Distributions v0.23.8 ⇒ v0.23.10
  [1a297f60] ↑ FillArrays v0.8.14 ⇒ v0.9.5
  [1d6d02ad] - LeftChildRightSiblingTrees v0.1.2
  [093fc24a] ↓ LightGraphs v1.3.3 ⇒ v1.3.0
  [e6f89c97] - LoggingExtras v0.4.2
  [1dea7af3] ↑ OrdinaryDiffEq v5.42.3 ⇒ v5.42.4
  [33c8b6b6] - ProgressLogging v0.1.3
  [92933f4c] - ProgressMeter v1.3.2
  [789caeaf] ↑ StochasticDiffEq v6.25.0 ⇒ v6.25.1
  [5d786b92] - TerminalLoggers v0.1.2

(Tester) pkg> add CUDA
  Resolving package versions...
Updating `C:\Users\accou\.julia\dev\DiffEqGPU\Tester\Project.toml`
  [052768ef] + CUDA v1.3.3
  [864edb3b] ↓ DataStructures v0.18.2 ⇒ v0.17.20
  [2b5f629d] ↓ DiffEqBase v6.46.1 ⇒ v6.44.3
  [1dea7af3] ↓ OrdinaryDiffEq v5.42.4 ⇒ v5.42.3
  [789caeaf] ↓ StochasticDiffEq v6.25.1 ⇒ v6.25.0
Updating `C:\Users\accou\.julia\dev\DiffEqGPU\Tester\Manifest.toml`
  [621f4979] + AbstractFFTs v0.5.0
  [1520ce14] + AbstractTrees v0.3.3
  [b99e7846] + BinaryProvider v0.5.10
  [fa961155] + CEnum v0.4.1
  [052768ef] + CUDA v1.3.3
  [88cd18e8] + ConsoleProgressMonitor v0.1.2
  [864edb3b] ↓ DataStructures v0.18.2 ⇒ v0.17.20
  [2b5f629d] ↓ DiffEqBase v6.46.1 ⇒ v6.44.3
  [c894b116] ↓ DiffEqJump v6.10.1 ⇒ v6.10.0
  [31c24e10] ↓ Distributions v0.23.10 ⇒ v0.23.8
  [e2ba6199] + ExprTools v0.1.1
  [1a297f60] ↓ FillArrays v0.9.5 ⇒ v0.8.14
  [0c68f7d7] + GPUArrays v5.1.0
  [61eb1bfa] + GPUCompiler v0.6.0
  [929cbde3] + LLVM v2.0.0
  [1d6d02ad] + LeftChildRightSiblingTrees v0.1.2
  [093fc24a] ↑ LightGraphs v1.3.0 ⇒ v1.3.3
  [e6f89c97] + LoggingExtras v0.4.2
  [872c559c] + NNlib v0.7.4
  [1dea7af3] ↓ OrdinaryDiffEq v5.42.4 ⇒ v5.42.3
  [33c8b6b6] + ProgressLogging v0.1.3
  [92933f4c] + ProgressMeter v1.3.2
  [789caeaf] ↓ StochasticDiffEq v6.25.1 ⇒ v6.25.0
  [5d786b92] + TerminalLoggers v0.1.2
  [a759f4b9] + TimerOutputs v0.5.6
```

That seems to be acting right. Is that kind of thing a sufficient test?

**Comment by DilumAluthge** [comment]
Yeah that's pretty much all you can do.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaRegistries/General/pull/20415 is actually great example of why we need better CI for compat PRs. It looks perfectly fine to human eyes, but sufficiently thorough CI would have caught it.

**Pull request merged**
