### PR TITLE
Update package naming guidelines link in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by LilithHafner**
The new link is unstable, but at least it's not broken.

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
@ericphanson @LilithHafner Can we add a linkcheck CI job or something? Maybe just as a cron job that runs once a week and makes sure that no links (in our Markdown files) are dead?

**Comment by LilithHafner** [comment]
I don't have the bandwidth RN, but I started making a little link checker a bit ago and got as far as https://github.com/LilithHafner/ExtractLinks.jl. My goal was to support broken fragments, something that most link checkers don't have. Any reasonable link checker should be able to spot this kind of breakage, though.

**Comment by LilithHafner** [comment]
Bump

**Comment by fredrikekre** [comment]
I think these docs are on their way back to Pkg. Why not link to the v1.10 Pkg docs here instead of dev?

**Comment by LilithHafner** [comment]
> I think these docs are on their way back to Pkg.

Do you have a link for that PR/issue/plan?

**Comment by DilumAluthge** [comment]
Maybe @fredrikekre was referring to this part of the pkgdocs? https://pkgdocs.julialang.org/v1/creating-packages/#Package-naming-guidelines

**Review by DilumAluthge — APPROVED** [review]

**Comment by fredrikekre** [comment]
I was referring to https://github.com/JuliaLang/Pkg.jl/pull/3818 and https://github.com/JuliaLang/julia/pull/53509.

**Pull request merged**
