### PR TITLE
New version: CompilerSupportLibraries_jll v0.3.7+0

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package CompilerSupportLibraries_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl
* Version: v0.3.7+0

### CODE REVIEW

**Comment by giordano** [comment]
```
ERROR: Unsatisfiable requirements detected for package CompilerSupportLibraries_jll [e66e0078]:
 CompilerSupportLibraries_jll [e66e0078] log:
 ├─possible versions are: 0.3.6 or uninstalled
 └─restricted to versions 0.3.7 by an explicit requirement — no versions left
```
I'm confused, doesn't this run on Julia v1.6 now?  CC: @DilumAluthge

**Comment by DilumAluthge** [comment]
[noblock]

AutoMerge is running on the 1.6 beta.

**Comment by DilumAluthge** [comment]
Not sure why it's failing.

[noblock]

**Comment by giordano** [comment]
It has the same julia compat as 0.3.6, I don't understand why only 0.3.6 is ok

**Comment by DilumAluthge** [comment]
Can you add this registry branch locally and try it out?

[noblock]

**Comment by giordano** [comment]
```
(@v1.6) pkg> activate --temp
  Activating new environment at `/tmp/jl_XS5K0w/Project.toml`

(jl_XS5K0w) pkg> add CompilerSupportLibraries_jll
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
   Installed CompilerSupportLibraries_jll ─ v0.3.7+0
  Downloaded artifact: CompilerSupportLibraries
Updating `/tmp/jl_XS5K0w/Project.toml`
  [e66e0078] + CompilerSupportLibraries_jll v0.3.7+0
Updating `/tmp/jl_XS5K0w/Manifest.toml`
  [692b3bcd] + JLLWrappers v1.2.0
  [e66e0078] + CompilerSupportLibraries_jll v0.3.7+0
  [0dad84c5] + ArgTools
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [f43a241f] + Downloads
  [b77e0a4c] + InteractiveUtils
  [b27032c2] + LibCURL
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [ca575930] + NetworkOptions
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [fa267f1f] + TOML
  [a4e569a6] + Tar
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [deac9b47] + LibCURL_jll
  [14a3606d] + MozillaCACerts_jll
Precompiling project...
  Progress [========================================>]  2/2
2 dependencies successfully precompiled in 3 seconds
```

**Comment by DilumAluthge** [comment]
> It has the same julia compat as 0.3.6, I don't understand why only 0.3.6 is ok
> 
> [noblock]

In fact, all of the possible versions of CompilerSupportLibraries should be available, since all of them are compatible with Julia 1.6.

[noblock]

**Comment by DilumAluthge** [comment]
Wait. Is CompilerSupportLibraries a stdlib in Julia 1.6?

[noblock]

**Comment by giordano** [comment]
> Wait. Is CompilerSupportLibraries_jll a stdlib in Julia 1.6?

It is.  I'm running locally a version older than the JLLpocalypse.  Ok, this probably explains the issue

**Comment by giordano** [comment]
Hold on, there is something wrong in the tarball

**Comment by DilumAluthge** [comment]
@giordano Good to merge this?

**Comment by giordano** [comment]
Yeah, I think so

**Comment by DilumAluthge** [comment]
Feel free to revert if something breaks

**Pull request merged**
