### PR TITLE
Fix DiskArrays compat

### PR DESCRIPTION
**Pull request by meggart**
Update compat instead of yanking release, replaces #102850

### CODE REVIEW

**Comment by giordano** [comment]
https://github.com/JuliaRegistries/General/blob/00dfc2edb0c9ac583ef81d47954445adc1101e54/D/DiskArrays/Compat.toml#L7 has to change to something like
```toml
["0.3"]
```
otherwise you have conflicting specifications.

**Comment by rafaqz** [comment]
What is happening here... the yank was such an obvious quick fix to just merge, and now we have chaos instead:

https://github.com/yeesian/ArchGDAL.jl/actions/runs/8969588301/job/24631262216?pr=423

**Comment by giordano** [comment]
> is the idea that instead we just cut out 0.4.0 completely from any julia compatability?

No.

**Comment by rafaqz** [comment]
But isn't that what your change does? wont there be no version if julia where 0.4.0 works?

If so, what version will it work on?

**Comment by giordano** [comment]
> But isn't that what your change does?

No.

> wont there be no version of julia where 0.4.0 can be added?

Julia v1.9+

**Comment by rafaqz** [comment]
Ahh right there always needs to be a version change in two places, not just the one, or there is a conflict.

The example link goes to the file without the current PR changes so skimming it looks like you meant "instead of", but I guess thats just github UI not letting you link the PR file.

**Comment by meggart** [comment]
Sorry to all for losing attention on this one. I hope this will fix it now.

**Pull request merged**
