### PR TITLE
[CI] Symlink registry to current directory

### PR DESCRIPTION
**Pull request by giordano**
We already cloned the repository in the checkout step, avoid it cloning
over and over again.

### CODE REVIEW

**Review by DilumAluthge — CHANGES_REQUESTED** [review]
I don't think we should do this. We don't know that the PR's copy of the registry is internally valid, or even trustworthy.

**Comment by giordano** [comment]
Agreed, although it's unfortunate that we have already 99.999% of the repo locally and we need to du a full-blown clone once again.  Also, what's the rational of doing `add` + `update`?  Do you ever expect to be there any difference?  Today there are jobs getting stuck on the update step...

**Comment by giordano** [comment]
Also, shouldn't the CI job for Julia v1.6 be required?  It's failing here, but this PR can be merged anyway

**Comment by DilumAluthge** [comment]
> Also, shouldn't the CI job for Julia v1.6 be required? It's failing here, but this PR can be merged anyway

Yeah we should update the branch protection settings to make it required.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaRegistries/General/issues/51321

**Pull request closed without merging**
