### PR TITLE
Update IndividualDisplacements URL to post-rename repo

### PR DESCRIPTION
**Pull request by gaelforget**

### CODE REVIEW

**Comment by gaelforget** [comment]
See https://github.com/JuliaRegistries/General/pull/119126

**Comment by gaelforget** [comment]
I do not understand why `Merging is blocked`.

**Comment by gaelforget** [comment]
I opened this PR because https://github.com/JuliaRegistries/General#readme says 

`if you rename the repository so it has a new URL, make a PR to edit the URL stored in the registry for the old package name to point to the new URL ([example](https://github.com/JuliaRegistries/General/pull/40190/files)). This allows the old versions of the package under the previous name to continue to work.`

and it seems desirable that previous name continues to work.

Did I do something wrong?

**Comment by GunnarFarneback** [comment]
> I do not understand why Merging is blocked.

That's the same for all PRs to General unless you happen to have merge authorization.

> Did I do something wrong?

This PR looks fine to me but since it is a manual PR, automerge doesn't handle it and it needs to be merged by someone who does have merge authorization.

**Comment by gaelforget** [comment]
> > I do not understand why Merging is blocked.
> 
> That's the same for all PRs to General unless you happen to have merge authorization.
> 
> > Did I do something wrong?
> 
> This PR looks fine to me but since it is a manual PR, automerge doesn't handle it and it needs to be merged by someone who does have merge authorization.

Makes sense now. Thanks for the clarification

**Comment by gaelforget** [comment]
Hi. Could this get merged?

**Pull request merged**
