### PR TITLE
Manual update compat for LazyWAVFiles

### PR DESCRIPTION
**Pull request by baggepinnen**
A bug appeared when used with LazyArrays v0.16 so I think it's best to remove that compatability declaration.

### CODE REVIEW

**Comment by baggepinnen** [comment]
Would someone be willing to take a look at this?

**Comment by giordano** [comment]
Note that there is a merge conflict

**Comment by DilumAluthge** [comment]
@baggepinnen Can you rebase on master and fix the merge conflict?

**Comment by DilumAluthge** [comment]
This isn't quite right, which is why Travis is failing.

**Comment by baggepinnen** [comment]
Hmm, then I'll just close this PR, it has been a month now so hopefully all related packages are updated and users will not end up with the incompatible versions

**Pull request closed without merging**
