### PR TITLE
Update git-tree-sha1 for GenomicFeatures v1.0.1

### PR DESCRIPTION
**Pull request by CiaranOMara**
In our haste, we introduced a few extra commits to our master branch. We want to modify our SHA so that it points to a commit on a straightened branch that will become our new master branch.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Once a version is registered, we don’t allow you to modify it.

If you like, you can yank this version. But you can’t modify its `git-tree-sha1`.

**Comment by DilumAluthge** [comment]
Let me know if you’d like me to help you yank this version.

**Comment by CiaranOMara** [comment]
@DilumAluthge, how does one go about yanking a version?

**Comment by DilumAluthge** [comment]
@CiaranOMara https://github.com/JuliaRegistries/General/pull/7594

**Pull request closed without merging**
