### PR TITLE
Update compat for LazyArtifacts

### PR DESCRIPTION
**Pull request by vchuravy**
- Update LazyArtifacts compat
- register new version

### CODE REVIEW

**Comment by vchuravy** [comment]
@DilumAluthge My preferred plan of action is to run the CompatStdlibUpdater for all stdlibs and then register the stdlibs one by one.
I think one of the challenges is what do we want to use as the commit for the 1.11.0 registration.

**Comment by giordano** [comment]
I think this should have just used "1" everywhere.

**Comment by DilumAluthge** [comment]
Tbh it probably should have used `<0.0.1, 1` everywhere.

**Comment by giordano** [comment]
There's no version 0.0.0 in the registry, only 1.3 and 1.11

**Comment by DilumAluthge** [comment]
When you do e.g. `Pkg.test()` in Julia 1.3, Pkg will set the version numbers of all stdlibs to 0.0.0.

**Comment by giordano** [comment]
But LazyArtifacts isn't a stdlib in Julia v1.3, is it?

**Comment by DilumAluthge** [comment]
The bug can still show up in later Julia versions. In e.g. Julia 1.8 and 1.9, if you do Pkg operations during your test suite, then you (and all of your recursive dependencies) need to have `<0.0.1` in the stdlib compat.

**Pull request merged**
