### PR TITLE
New package: rocSOLVER_jll v4.2.0+0

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package rocSOLVER_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/rocSOLVER_jll.jl
* Version: v4.2.0+0
* Commit: be992388eee341e3e774f86142b711fa2fed5ea8
* Revision on Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/commit/b82dd0493851f363b36cb2c57f610500148ba7fa
* Created by: @jpsamaroo

### CODE REVIEW

**Comment by jpsamaroo** [comment]
This loads fine on 1.7; a different version will become available for 1.8 in the near future.

**Comment by jpsamaroo** [comment]
@pxl-th does this seem right, or should we be removing the Julia compat instead?

**Comment by pxl-th** [comment]
> @pxl-th does this seem right, or should we be removing the Julia compat instead?

I see that it used incorrect versions of dependencies, like ROCmOpenCLRuntime 5.2.3.
I'm thinking maybe we should really add back Julua 1.9 compats to ROCm 5.2.3?

**Comment by jpsamaroo** [comment]
I think this should be fine to merge, since we've resolved the above issues with compat bounds on dependencies.

**Pull request closed without merging**
