### PR TITLE
Update links to my repos

### PR DESCRIPTION
**Pull request by zlatanvasovic**

### CODE REVIEW

**Comment by zlatanvasovic** [comment]
@giordano When you follow the links, it points to https://travis-ci.com/github/JuliaRegistries/General/builds/183714094 which is already green.

**Comment by giordano** [comment]
Yeah, that's the same job as when you link on other button.  The problem is: if there is a required job that hasn't completed successfully yet, there is no "merge" button at all.

**Comment by giordano** [comment]
Well, if someone has super powers maybe can merge anyway.

**Comment by fredrikekre** [comment]
> there is no "merge" button at all

image

**Pull request merged**
