### PR TITLE
add `feed` workflow

### PR DESCRIPTION
**Pull request by ericphanson**
This adds a workflow that runs whenever a PR is labelled. If the label is "new package", then it uses a Slack endpoint kindly supplied by @logankilpatrick to update the `#new-packages-feed` channel (currently I believe the endpoint is pointed at `#stackoverflow-feed` but it's being updated). I want to also add a Zulip feed as a second job to this workflow (in a future PR).

I think this is useful for two reasons:

1. It provides a simple way for users on Slack/Zulip to keep up with all the awesome new packages being registered
2. It might help more folks get involved with the registry, to help chime in with ideas about names, contribute when they think a name-distance clash is OK or not, and help point new package devs towards [best practices](https://github.com/JuliaRegistries/General#should-i-register-my-package). This is why I want to trigger the update when the PR is created, not when it is merged.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
You could also add "opened" to the `types`, just to be safe. I'm not sure if `labeled` gets called when the label is part of the original PR creation.

It would be good for @logankilpatrick to review the specifics, as I'm not too familiar with the Slack bots.

**Comment by DilumAluthge** [comment]
Also, I don't think it worked.

**Comment by ericphanson** [comment]
Wow, Slack replied with a whole webpage: https://github.com/JuliaRegistries/General/pull/43737/checks?check_run_id=3455592925#step:3:77

**Comment by DilumAluthge** [comment]
Can you add code that prepends `/` to the endpoint environment variable? I don't think I included a leading `/` when I input the secret.

**Comment by ericphanson** [comment]
This is the webpage it returned, rendered:

[Slack API _ Slack.pdf](https://github.com/JuliaRegistries/General/files/7072920/Slack.API._.Slack.pdf)

So just a generic page, not saying anything about our request.

**Comment by DilumAluthge** [comment]
I think this PR doesn't have access to secrets, because it was made from a fork. So the secret is empty, and we are just hitting hooks.slack.com.

**Comment by DilumAluthge** [comment]
@ericphanson Can you make a new PR that is not from a fork?

**Comment by ericphanson** [comment]
> You could also add "opened" to the types, just to be safe. I'm not sure if labeled gets called when the label is part of the original PR creation.

Hm, good point. I'd rather keep it to just `labeled` for now and see if it works, and then update it if it doesn't. The reason is that if it's not triggered by a `labeled` event, I don't know if there's an easy way to get the label name.

**Comment by logankilpatrick** [comment]
I also think the secret is wrong right now, still trying to workout what it should be

**Comment by DilumAluthge** [comment]
> > You could also add "opened" to the types, just to be safe. I'm not sure if labeled gets called when the label is part of the original PR creation.
> 
> Hm, good point. I'd rather keep it to just `labeled` for now and see if it works, and then update it if it doesn't. The reason is that if it's not triggered by a `labeled` event, I don't know if there's an easy way to get the label name.

Sounds good to me.

**Comment by ericphanson** [comment]
> @ericphanson Can you make a new PR that is not from a fork?

Ohh, maybe the fork doesn't get the secret, right. Oops, will do that

**Comment by DilumAluthge** [comment]
From the log:

```
env:
24
    SLACK_ENDPOINT: 
25
    PR_NAME: add `feed` workflow
26
    PR_NUMBER: 43737
    ```

If we were getting the secret, it would have three asterisks next to `SLACK_ENDPOINT`. We're not getting the secret because the PR is from a fork.

We should add a conditional that only runs this workflow if the PR is not from a fork. That still includes all Registrator.jl PRs, which is what we want.

**Pull request closed without merging**
