### PR TITLE
Update links to my repos

### PR DESCRIPTION
**Pull request by zlatanvasovic**
I changed my GitHub username. Is this the right way to update repos, or there's something else to do?

### CODE REVIEW

**Comment by giordano** [comment]
Can you please open a new pull request that does the same?  I have no idea what's wrong with travis here

**Comment by fredrikekre** [comment]
Seems to be running though? https://travis-ci.com/github/JuliaRegistries/General/builds/183726360

**Comment by giordano** [comment]
That job wasn't even created 17 minutes ago when I couldn't find any trace of it and closed the PR.  According to https://travis-ci.com/github/JuliaRegistries/General/requests it was received 8 minutes ago

**Comment by giordano** [comment]
Well, that's another PR

**Pull request closed without merging**
