### PR TITLE
Update registry-consistency-ci.yml for Julia 1.11

### PR DESCRIPTION
**Pull request by ViralBShah**
Add 1.11 to registry consistency check

### CODE REVIEW

**Comment by ViralBShah** [comment]
How does one mark 1.11 to be `Required` like the others?

**Comment by maleadt** [comment]
> How does one mark 1.11 to be `Required` like the others?

That's a setting in the branch protection rules of the `master` branch.

**Review by DilumAluthge — APPROVED** [review]

**Comment by ViralBShah** [comment]
Would it be ok to remove some of the older ones (like pre 1.6) to save CI time?

**Comment by DilumAluthge** [comment]
How about we keep 1.3, but we drop 1.4 and 1.5? That way, the only bugs we miss would be bugs introduced in 1.4 but fixed by 1.6.

**Comment by ViralBShah** [comment]
Seems reasonable.

**Comment by ViralBShah** [comment]
I wonder if we can also get rid of a few other versions like 1.7 and 1.8. Or would that be too aggressive?

**Pull request merged**
