### PR TITLE
Limit DiffEqBase >=6.21 to >=1.3

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by GunnarFarneback** [comment]
This change isn't effective. It's also necessary to modify
```
["4.22-6.23"]
julia = "1"
```

**Comment by fredrikekre** [comment]
Indeed, see #11397 posted the same minute as you commented :stuck_out_tongue:

**Comment by GunnarFarneback** [comment]
Convergent analysis.

**Comment by fredrikekre** [comment]
Please don't merge changes like this without testing them.

**Comment by ChrisRackauckas** [comment]
It was tested and it worked. It was just reversed by Registrator....

**Comment by GunnarFarneback** [comment]
What Registrator does with conflicting ranges depends on Dict iteration order. I can't really follow the Pkg code but I wouldn't be surprised if the same holds there.

**Pull request merged**
