### PR TITLE
Move YaoToEinsum and YaoPlots to Yao's repo

### PR DESCRIPTION
**Pull request by GiggleLiu**

### CODE REVIEW

**Comment by GiggleLiu** [comment]
We moved YaoPlots and YaoToEinsum to Yao's main repo recently, could you please help me merge this PR?
@giordano

**Comment by giordano** [comment]
Did you verify old versions of the packages would still be installable?  When you move stuff to subdirs of another existing repository you have to recreate the history.

**Comment by GiggleLiu** [comment]
> Did you verify old versions of the packages would still be installable? When you move stuff to subdirs of another existing repository you have to recreate the history.

Yes. I did not remove the old repository. These repos will be archived after the relocations.

**Comment by giordano** [comment]
No, that's not how it works. With this PR you're changing the repository from where the packages are retrieved, so the already registered versions of those packages will have to be installable from the new repository.

**Comment by GiggleLiu** [comment]
@giordano I have merged the git subtree with the following PR:
https://github.com/QuantumBFS/Yao.jl/pull/504

Now I can use the tree-hash for extracting the correct version of YaoToEinsum and YaoPlots. Is there any way to test if the older version packages should be resovled correctly?

**Comment by giordano** [comment]
You can use https://github.com/JuliaRegistries/General/pull/35965#issuecomment-832721704

**Comment by GiggleLiu** [comment]
Thank you! @giordano 

All package are found. The output is as follows.

```bash
YaoToEinsum
0.1.0 found
0.1.1 found
0.1.2 found
0.1.3 found
0.1.4 found
0.1.5 found
0.2.0 found
0.2.1 found
0.2.2 found
YaoPlots
0.1.0 found
0.2.0 found
0.3.0 found
0.4.0 found
0.4.1 found
0.5.0 found
0.6.0 found
0.6.1 found
0.7.0 found
0.7.1 found
0.7.2 found
0.7.3 found
0.7.4 found
0.7.5 found
0.8.0 found
0.8.1 found
0.9.0 found
```

**Pull request merged**
