### PR TITLE
Change package URL for Arrow.jl

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by fredrikekre** [comment]
Any reason this isn't a transfer? Are the old trees available in the new repo?

**Comment by quinnj** [comment]
I'd didn't realize a transfer would have been easier, but I did replay all my new commits onto the existing package tree and then force pushed master to the new repo. That should ensure all the old trees are still intact, right?

**Comment by giordano** [comment]
As a check, are you able to install old versions of the package using this branch of the registry?

**Comment by quinnj** [comment]
Yes, I am able to

**Comment by giordano** [comment]
Ok, then let's go

**Pull request merged**
