### PR TITLE
Rename MixedAnova to AnovaBase

### PR DESCRIPTION
**Pull request by yufongpeng**

### CODE REVIEW

**Comment by giordano** [comment]
Did you see https://github.com/JuliaRegistries/General/blob/23a73c732e6a74a1b81d6c4f2603066ae132866c/README.md#how-do-i-rename-an-existing-registered-package?

**Comment by yufongpeng** [comment]
Yes, I did. I forgot to leave a comment in the new PR. Is there still anything wrong?

**Comment by giordano** [comment]
Ok, just double checking you're following those steps :slightly_smiling_face:

**Comment by yufongpeng** [comment]
Thanks!

**Pull request merged**
