### PR TITLE
Migrate BioFetch to BioJulia org

### PR DESCRIPTION
**Pull request by BioTurboNick**

### CODE REVIEW

**Comment by giordano** [comment]
Why didn't you simply move the repository?

**Comment by BioTurboNick** [comment]
I did. JuliaRegistrator said I needed to do this.

**Comment by BioTurboNick** [comment]
Unless I misunderstood the problem: https://github.com/BioJulia/BioFetch.jl/commit/e3a12a02dcf0e9f69b519800f9776ae93e68f272#commitcomment-51391189

**Comment by giordano** [comment]
But then you forked that repo to your own account breaking the redirect

**Comment by giordano** [comment]
Your repository already diverged from upstream

**Comment by BioTurboNick** [comment]
Yes? The point is to keep doing development in mine and then PR into BioJulia.

**Comment by giordano** [comment]
You use different branches for that, not the same default branch in a fork.  In general, it's a bad idea to do a pull request from the same branch in a fork

**Comment by BioTurboNick** [comment]
Alright. Not understanding why that's a problem here.

**Comment by giordano** [comment]
Because at the moment the package is being served from your fork instead from BioJulia and since I saw the two `main` branches diverged (your `main` branch is 11 commits ahead, 1 commit behind `BioJulia:main`) I had to check you actually didn't break previous versions.

It looks like previously registered versions are still there so I'm going to merge this

**Comment by BioTurboNick** [comment]
Alright, noted for the future. Thanks!

**Pull request merged**
