### PR TITLE
Add TagBot token to automerge

### PR DESCRIPTION
**Pull request by christopher-dG**
Needs RegistryCI 4.3.3 (https://github.com/JuliaRegistries/RegistryCI.jl/pull/289).

I also bumped the Julia version to a supported one, but really we could just get rid of the `setup-julia` step.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
The `import PkgName` is broken on 1.5.2 for some packages. But it's fixed in nightly, so let's use that instead.

**Comment by christopher-dG** [comment]
That seems... unwise. But it's your call. This should now wait for https://github.com/JuliaRegistries/RegistryCI.jl/pull/290 too.

**Comment by DilumAluthge** [comment]
We can use 1.5.1 instead.

**Comment by DilumAluthge** [comment]
I haven't been able to figure out what changed in 1.5.1 to 1.5.2 that made `import PkgName` break for some packages.

And since the breakage does not happen on Julia nightly, I'm not particularly motivated to investigate it further.

**Comment by christopher-dG** [comment]
Hm, that is really odd. But yeah, hopefully 1.6 will come soon ™️

**Comment by DilumAluthge** [comment]
Alright should be all set now.

**Pull request merged**
