### PR TITLE
New package: Couenne_jll v0.5.8+0

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package Couenne_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/Couenne_jll.jl
* Version: v0.5.8+0
* Revision on Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/commit/8be19820afa24ff817185f3c53c4d20786a8add3

### CODE REVIEW

**Comment by giordano** [comment]
@odow  https://github.com/JuliaRegistries/General/pull/33796/checks?check_run_id=2292099385#step:6:191
```
ERROR: InitError: could not load library "/tmp/jl_lYVjlJ/artifacts/ecc837f417130ef88b6288424541354733c387b1/lib/libCouenne.so"
libbonminampl.so.4: cannot open shared object file: No such file or directory
```

[noblock]

**Comment by odow** [comment]
I continue to display a terrible naivety with BinaryBuilder.  I guess if a JLL uses a library from another JLL, that library must be declared as one of the products? 
```Julia
julia> using Ipopt_jll, Bonmin_jll, Libdl

julia> Libdl.dlopen(joinpath(dirname(Ipopt_jll.libipopt_path), "libipoptamplinterface.dylib"))
Ptr{Nothing} @0x00007fac8c749850

julia> Libdl.dlopen(joinpath(dirname(Bonmin_jll.libbonmin_path), "libbonminampl.dylib"))
Ptr{Nothing} @0x00007fac8c572190

julia> using Couenne_jll

julia> Couenne_jll.amplexe() do path
       run(`$(path) -v`)
       end
Couenne 0.5.8 -- an Open-Source solver for Mixed Integer Nonlinear Optimization
Mailing list: couenne@list.coin-or.org
Instructions: http://www.coin-or.org/Couenne
couenne (Linux x86_64), ASL(20210327)

Process(`/Users/oscar/.julia/artifacts/2a977e2bc37cb7d4c751b647ffe19671a1e097a8/bin/couenne -v`, ProcessExited(0))
```

So I guess I need to add `LibraryProduct("libipoptamplinterface", :libipoptamplinterface),` to
https://github.com/JuliaPackaging/Yggdrasil/blob/e93b3b95a9e8a2704fc095ce2cb788fe38a6af6d/I/Ipopt/build_tarballs.jl#L41-L44
and
`LibraryProduct("libbonminampl", :libbonminampl),` to
https://github.com/JuliaPackaging/Yggdrasil/blob/b19036c32fc5d00ea4cc7fc5a1b35131d44a5403/C/Coin-OR/Bonmin/build_tarballs.jl#L58-L61?

**Comment by giordano** [comment]
> I guess if a JLL uses a library from another JLL, that library must be declared as one of the products?

Yes, that's correct :slightly_smiling_face: 

[noblock]

**Comment by giordano** [comment]
Rejoice, [new error](https://github.com/JuliaRegistries/General/pull/33796/checks?check_run_id=2300504160#step:6:191)!
```
ERROR: InitError: could not load library "/tmp/jl_KKxJ1h/artifacts/ecc837f417130ef88b6288424541354733c387b1/lib/libCouenne.so"
/tmp/jl_KKxJ1h/artifacts/ecc837f417130ef88b6288424541354733c387b1/lib/libCouenne.so: undefined symbol: _ZTv0_n720_NK21OsiClpSolverInterface10getRowNameEij
```
```console
% echo _ZTv0_n720_NK21OsiClpSolverInterface10getRowNameEij|c++filt 
virtual thunk to OsiClpSolverInterface::getRowName(int, unsigned int) const
```

[noblock]

**Comment by giordano** [comment]
Seems to be the same function that caused a failure in https://github.com/JuliaRegistries/General/pull/31558#issuecomment-796257733

[noblock]

**Comment by odow** [comment]
Now I'm very very confused, because Pkg claims to have pulled in `Clp@1.17.6` (https://github.com/JuliaRegistries/General/pull/33796/checks?check_run_id=2300504160#step:6:100), which is the one Cbc_jll needed to fix the problem (https://github.com/JuliaRegistries/General/pull/31977).

[noblock]

**Pull request merged**
