### PR TITLE
upper bound all previous versions of packages in JuliaDiffEq

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Script:

```julia
# github
import GitHub

auth = GitHub.authenticate("ENV["GITHUB_AUTH"]") # you need to set this in your ENV

drepos = GitHub.repos("JuliaDiffEq", auth = auth)[1]

#run(`git clone https://github.com/JuliaRegistries/General.git`)
cd(raw"C:\Users\accou\.julia\external\General")
using RetroCap

pkgs = [RetroCap.Package(r.name[1:end-3]) for r in drepos]
pkg_to_path, pkg_to_num_versions, pkg_to_latest_version = RetroCap.parse_registry(pwd())

for pkg in pkgs
    try
        add_caps(NoUpperBound(),pwd(),
                 pkg_to_latest_version,
                 pkg,
                 pkg_to_path[pkg])
    catch
        println("Package $pkg not affected")
    end
end
```

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@DilumAluthge double check this worked. If it did, you may want to add this to the README RetroCap?

**Comment by fredrikekre** [comment]
Can we get a way to test for https://github.com/JuliaRegistries/RegistryCI.jl/issues/99 ?

**Comment by ChrisRackauckas** [comment]
I'm not sure what that is.

**Comment by ChrisRackauckas** [comment]
Is testing for that blocking?

**Comment by fredrikekre** [comment]
It was mostly directed to @DilumAluthge . Does the script make sure that does not happen? It is just a bit difficult to review that particular failure mode, and I assume you want your users to be able to add your packages :)

**Comment by DilumAluthge** [comment]
Hmm, so IIUC, https://github.com/JuliaRegistries/RegistryCI.jl/issues/99 was caused by
```
ERROR: Unknown package ZygoteRules found in the compatibility requirements of Zygote
```

Basically Mike  accidentally added ZygoteRules to the compat sections of versions of Zygote that did not depend on ZygoteRules.

I think the issue here is that Mike directly manipulated the compressed version of Compat.toml, instead of uncompressing it, modifying it, and recompressing it.

In theory, this should not happen with RetroCap because we first uncompress all versions with Pkg.Compress, then we do the caps, then we recompress with Pkg.Compress. So assuming that Pkg.Compress has no bugs, in theory RetroCap should not be able to add a compat entry to a version that doesn’t have it as a dependency.

That being said I don’t have any tests to make sure that’s the case. So probably would be good for @ChrisRackauckas to do some manual testing, I.e. check out this branch of the registry locally and make sure he can add packages without a problem.

**Comment by ChrisRackauckas** [comment]
LGTM

```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.2.0 (2019-08-20)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(v1.2) pkg> up
  Updating registry at `C:\Users\accou\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
┌ Warning: Some registries failed to update:
│     — C:\Users\accou\.julia\registries\General — branch origin/bounds not found
└ @ Pkg.Types C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\Types.jl:1171
 Resolving package versions...
  Updating `C:\Users\accou\.julia\environments\v1.2\Project.toml`
 [no changes]
  Updating `C:\Users\accou\.julia\environments\v1.2\Manifest.toml`
 [no changes]

(v1.2) pkg> add DifferentialEquations
 Resolving package versions...
  Updating `C:\Users\accou\.julia\environments\v1.2\Project.toml`
  [0c46a032] + DifferentialEquations v6.8.0
  Updating `C:\Users\accou\.julia\environments\v1.2\Manifest.toml`
  [79e6a3ab] + Adapt v1.0.0
  [ec485272] + ArnoldiMethod v0.0.4
  [4fba245c] + ArrayInterface v1.2.1
  [aae01518] + BandedMatrices v0.13.0
  [9e28174c] + BinDeps v0.8.10
  [b99e7846] + BinaryProvider v0.5.8
  [764a87c0] + BoundaryValueDiffEq v2.3.0
  [49dc2e85] + Calculus v0.5.1
  [bbf7d656] + CommonSubexpressions v0.2.0
  [34da2185] + Compat v2.2.0
  [864edb3b] + DataStructures v0.17.5
  [bcd4f6db] + DelayDiffEq v5.18.0
  [2b5f629d] + DiffEqBase v6.5.0
  [459566f4] + DiffEqCallbacks v2.9.0
  [01453d9d] + DiffEqDiffTools v1.4.0
  [5a0ffddc] + DiffEqFinancial v2.2.1
  [c894b116] + DiffEqJump v6.2.2
  [77a26b50] + DiffEqNoiseProcess v3.3.1
  [055956cb] + DiffEqPhysics v3.2.0
  [163ba53b] + DiffResults v0.0.4
  [b552c78f] + DiffRules v0.1.0
  [0c46a032] + DifferentialEquations v6.8.0
  [c619ae07] + DimensionalPlotRecipes v1.0.0
  [b4f34e82] + Distances v0.8.2
  [ffbed154] + DocStringExtensions v0.8.1
  [d4d017d3] + ExponentialUtilities v1.5.1
  [1a297f60] + FillArrays v0.7.4
  [f6369f11] + ForwardDiff v0.10.6
  [069b7b12] + FunctionWrappers v1.0.0
  [01680d73] + GenericSVD v0.2.2
  [d25df0c9] + Inflate v0.1.1
  [42fd0dbc] + IterativeSolvers v0.8.1
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [5078a376] + LazyArrays v0.12.3
  [093fc24a] + LightGraphs v1.3.0
  [d3d80556] + LineSearches v7.0.1
  [1914dd2f] + MacroTools v0.5.2
  [a3b82374] + MatrixFactorizations v0.2.0
  [46d2c3a1] + MuladdMacro v0.2.1
  [f9640e96] + MultiScaleArrays v1.5.0
  [d41bc354] + NLSolversBase v7.5.0
  [2774e3e8] + NLsolve v4.2.0
  [77ba4419] + NaNMath v0.3.3
  [bac558e1] + OrderedCollections v1.1.0
  [1dea7af3] + OrdinaryDiffEq v5.23.0
  [d96e819e] + Parameters v0.12.0
  [e409e4f3] + PoissonRandom v0.4.0
  [e6cf234a] + RandomNumbers v1.3.0
  [3cdcf5f2] + RecipesBase v0.7.0
  [731186ca] + RecursiveArrayTools v1.0.2
  [f2c3362d] + RecursiveFactorization v0.1.0
  [189a3867] + Reexport v0.2.0
  [ae029012] + Requires v0.5.2
  [ae5879a3] + ResettableStacks v0.6.0
  [f2b01f46] + Roots v0.8.3
  [699a6c99] + SimpleTraits v0.9.1
  [47a9eef4] + SparseDiffTools v0.10.3
  [276daf66] + SpecialFunctions v0.8.0
  [90137ffa] + StaticArrays v0.11.1
  [9672c7b4] + SteadyStateDiffEq v1.5.0
  [789caeaf] + StochasticDiffEq v6.13.0
  [c3572dad] + Sundials v3.8.0
  [3783bdb8] + TableTraits v1.0.0
  [a2a6695c] + TreeViews v0.3.0
  [30578b45] + URIParser v0.4.0
  [19fa3120] + VertexSafeGraphs v0.1.0
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8bb1440f] + DelimitedFiles
  [8ba89e20] + Distributed
  [b77e0a4c] + InteractiveUtils
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [1a1011a3] + SharedArrays
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [4607b0f0] + SuiteSparse
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode

(v1.2) pkg> add OrdinaryDiffEq
 Resolving package versions...
  Updating `C:\Users\accou\.julia\environments\v1.2\Project.toml`
  [1dea7af3] + OrdinaryDiffEq v5.23.0
  Updating `C:\Users\accou\.julia\environments\v1.2\Manifest.toml`
 [no changes]

(v1.2) pkg> add DiffEqFlux
 Resolving package versions...
 Installed InvertedIndices ───── v1.0.0
 Installed Missings ──────────── v0.4.3
 Installed PooledArrays ──────── v0.5.2
 Installed PDMats ────────────── v0.9.10
 Installed CodecZlib ─────────── v0.6.0
 Installed StatsFuns ─────────── v0.9.0
 Installed DiffEqFlux ────────── v0.8.0
 Installed CUDAdrv ───────────── v3.1.0
 Installed DataValueInterfaces ─ v1.0.0
 Installed SortingAlgorithms ─── v0.3.1
 Installed ZipFile ───────────── v0.8.3
 Installed FFTW ──────────────── v1.1.0
 Installed GLM ───────────────── v1.3.4
 Installed Colors ────────────── v0.9.6
 Installed Tracker ───────────── v0.2.5
 Installed LLVM ──────────────── v1.3.2
 Installed Juno ──────────────── v0.7.2
 Installed Arpack ────────────── v0.3.1
 Installed TimerOutputs ──────── v0.5.3
 Installed ShiftedArrays ─────── v1.0.0
 Installed Conda ─────────────── v1.3.0
 Installed Distributions ─────── v0.21.8
 Installed ColorTypes ────────── v0.8.0
 Installed Flux ──────────────── v0.9.0
 Installed StatsBase ─────────── v0.32.0
 Installed CUDAapi ───────────── v1.2.0
 Installed NNlib ─────────────── v0.6.0
 Installed AbstractFFTs ──────── v0.5.0
 Installed Parsers ───────────── v0.3.10
 Installed JSON ──────────────── v0.21.0
 Installed CUDAnative ────────── v2.4.0
 Installed CuArrays ──────────── v1.2.1
 Installed Media ─────────────── v0.5.0
 Installed QuadGK ────────────── v2.1.1
 Installed AbstractTrees ─────── v0.2.1
 Installed GPUArrays ─────────── v1.0.4
 Installed DataFrames ────────── v0.19.4
 Installed FixedPointNumbers ─── v0.6.1
 Installed StatsModels ───────── v0.6.7
 Installed Rmath ─────────────── v0.5.1
 Installed Tables ────────────── v0.2.11
 Installed VersionParsing ────── v1.1.3
 Installed TranscodingStreams ── v0.9.5
 Installed CategoricalArrays ─── v0.7.2
 Installed DataAPI ───────────── v1.1.0
 Installed DiffEqSensitivity ─── v4.3.0
 Installed CEnum ─────────────── v0.2.0
  Updating `C:\Users\accou\.julia\environments\v1.2\Project.toml`
  [aae7a2af] + DiffEqFlux v0.8.0
  Updating `C:\Users\accou\.julia\environments\v1.2\Manifest.toml`
  [621f4979] + AbstractFFTs v0.5.0
  [1520ce14] + AbstractTrees v0.2.1
  [7d9fca2a] + Arpack v0.3.1
  [fa961155] + CEnum v0.2.0
  [3895d2a7] + CUDAapi v1.2.0
  [c5f51814] + CUDAdrv v3.1.0
  [be33ccc6] + CUDAnative v2.4.0
  [324d7699] + CategoricalArrays v0.7.2
  [944b1d66] + CodecZlib v0.6.0
  [3da002f7] + ColorTypes v0.8.0
  [5ae59095] + Colors v0.9.6
  [8f4d0f93] + Conda v1.3.0
  [3a865a2d] + CuArrays v1.2.1
  [9a962f9c] + DataAPI v1.1.0
  [a93c6f00] + DataFrames v0.19.4
  [e2d170a0] + DataValueInterfaces v1.0.0
  [aae7a2af] + DiffEqFlux v0.8.0
  [41bf760c] + DiffEqSensitivity v4.3.0
  [31c24e10] + Distributions v0.21.8
  [7a1cc6ca] + FFTW v1.1.0
  [53c48c17] + FixedPointNumbers v0.6.1
  [587475ba] + Flux v0.9.0
  [38e38edf] + GLM v1.3.4
  [0c68f7d7] + GPUArrays v1.0.4
  [41ab1584] + InvertedIndices v1.0.0
  [682c06a0] + JSON v0.21.0
  [e5e0dc1b] + Juno v0.7.2
  [929cbde3] + LLVM v1.3.2
  [e89f7d12] + Media v0.5.0
  [e1d29d7a] + Missings v0.4.3
  [872c559c] + NNlib v0.6.0
  [90014a1f] + PDMats v0.9.10
  [69de0a69] + Parsers v0.3.10
  [2dfb63ee] + PooledArrays v0.5.2
  [1fd47b50] + QuadGK v2.1.1
  [79098fc4] + Rmath v0.5.1
  [1277b4bf] + ShiftedArrays v1.0.0
  [a2af1166] + SortingAlgorithms v0.3.1
  [2913bbd2] + StatsBase v0.32.0
  [4c63d2b9] + StatsFuns v0.9.0
  [3eaba693] + StatsModels v0.6.7
  [bd369af6] + Tables v0.2.11
  [a759f4b9] + TimerOutputs v0.5.3
  [9f7883ad] + Tracker v0.2.5
  [3bb67fe8] + TranscodingStreams v0.9.5
  [81def892] + VersionParsing v1.1.3
  [a5390f91] + ZipFile v0.8.3
  [9fa8497b] + Future
  [9abbd945] + Profile
  Building CodecZlib → `C:\Users\accou\.julia\packages\CodecZlib\5t9zO\deps\build.log`
  Building ZipFile ──→ `C:\Users\accou\.julia\packages\ZipFile\oD4uG\deps\build.log`
  Building Conda ────→ `C:\Users\accou\.julia\packages\Conda\kLXeC\deps\build.log`
  Building FFTW ─────→ `C:\Users\accou\.julia\packages\FFTW\loJ3F\deps\build.log`
  Building Arpack ───→ `C:\Users\accou\.julia\packages\Arpack\cu5By\deps\build.log`
  Building Rmath ────→ `C:\Users\accou\.julia\packages\Rmath\4wt82\deps\build.log`

(v1.2) pkg> add LSODA
 Resolving package versions...
 Installed LSODA ─ v0.6.1
  Updating `C:\Users\accou\.julia\environments\v1.2\Project.toml`
  [7f56f5a3] + LSODA v0.6.1
  Updating `C:\Users\accou\.julia\environments\v1.2\Manifest.toml`
  [7f56f5a3] + LSODA v0.6.1
  Building LSODA → `C:\Users\accou\.julia\packages\LSODA\uaBH4\deps\build.log`

(v1.2) pkg> add DiffEqGPU
 Resolving package versions...
 Installed GPUifyLoops ─ v0.2.9
 Installed Cassette ──── v0.2.6
 Installed DiffEqGPU ─── v0.4.0
  Updating `C:\Users\accou\.julia\environments\v1.2\Project.toml`
  [071ae1c0] + DiffEqGPU v0.4.0
  Updating `C:\Users\accou\.julia\environments\v1.2\Manifest.toml`
  [7057c7e9] + Cassette v0.2.6
  [071ae1c0] + DiffEqGPU v0.4.0
  [ba82f77b] + GPUifyLoops v0.2.9

(v1.2) pkg> add Sundials
 Resolving package versions...
  Updating `C:\Users\accou\.julia\environments\v1.2\Project.toml`
  [c3572dad] + Sundials v3.8.0
  Updating `C:\Users\accou\.julia\environments\v1.2\Manifest.toml`
 [no changes]

julia> using DiffEqFlux
[ Info: Precompiling DiffEqFlux [aae7a2af-3d4f-5e19-a356-7da93b79d9d0]

julia>

julia> using DifferentialEquations
[ Info: Precompiling DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa]
```

**Comment by DilumAluthge** [comment]
If anyone is reading this and wants the URL for RetroCap: https://github.com/bcbi/RetroCap.jl

**Comment by ChrisRackauckas** [comment]
@DilumAluthge @MikeInnes pointed out an issue where there seems to still be a package that's unbounded:

https://github.com/JuliaRegistries/General/blob/697ed8734543666895b70c02a2f65f79812a7669/D/DiffEqFlux/Compat.toml#L8

**Comment by fredrikekre** [comment]
It's technically bounded though.

**Comment by DilumAluthge** [comment]
Yeah, I mean it’s not a good bound certainly. But technically it is upper bounded.

**Comment by DilumAluthge** [comment]
But I agree that we probably shouldn’t allow that kind of bound.

Let me try something to see if we can catch those bounds.

**Pull request merged**
