### PR TITLE
New package: libjulia_jll v1.5.1+0

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package libjulia_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/libjulia_jll.jl
* Version: v1.5.1+0

### CODE REVIEW

**Comment by DilumAluthge** [comment]
[noblock]

Is this okay to manually merge?

@staticfloat @giordano

**Comment by giordano** [comment]
It's weird that it can't be installed. This runs on julia v1.5, right?

**Comment by DilumAluthge** [comment]
[noblock]

Seems like an unsatisfiability error involving MPFR_jll.

Yeah, AutoMerge runs on Julia 1.5.

**Comment by DilumAluthge** [comment]
[noblock]

Okay, now it can be installed, but not loaded. Seems to be a segfault?

**Comment by giordano** [comment]
Not loadable is fine

**Pull request merged**
