### PR TITLE
New version: SPIRV_LLVM_Translator_jll v10.0.0+2

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package SPIRV_LLVM_Translator_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl
* Version: v10.0.0+2

### CODE REVIEW

**Comment by vchuravy** [comment]
[no-block]

Summoning @maleadt @giordano

**Comment by giordano** [comment]
Oh wow

**Comment by maleadt** [comment]
Uhm, not sure what happened here. We don't really need this version of the translator though, as 1.6 has moved to LLVM 11. But just ignoring whatever happened here because of that doesn't seem very responsible either :smile:

**Comment by giordano** [comment]
I think we can simply remove the lines https://github.com/JuliaRegistries/General/blob/32151f143be884ea1f9fa7f93b509f5c19593973/S/SPIRV_LLVM_Translator_jll/Compat.toml#L1-L3?

**Comment by giordano** [comment]
Ok, this failure should be fine because CI runs with Julia v1.5.1 but this new versions is for Julia v1.6

**Comment by vchuravy** [comment]
Can confirm.

**Pull request merged**
