### PR TITLE
Increase upper bound of some StatsBase dependencies to 0.30

### PR DESCRIPTION
**Pull request by nalimilan**
These are dependencies for which tests passed with StatsBase 0.30.0 under Julia 1.1. Some false negatives might still need manual fixing.

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]
Looks good to me. @fredrikekre, @KristofferC do you want to look it over for sanity? If either of you thinks it looks ok, just merge.

**Comment by nalimilan** [comment]
Thanks. It would be great to automate this. :-)

**Comment by fredrikekre** [comment]
You could also stop releasing non-breaking breaking releases of StatsBase! :smile:

**Comment by nalimilan** [comment]
Yes, we're going to try moving things to Statistics or other packages. But in general, major releases will continue to happen, and (hopefully) they won't always break all packages.

**Comment by nalimilan** [comment]
For reference, here's the list of packages that failed tests. Still quite a lot of porting to do (probably most of these failures are spurious).
``["AbbrvKW", "ActiveAppearanceModels", "ApproxBayes", "Augur", "AverageShiftedHistograms", "ApproximateBayesianComputing", "ARCHModels", "Agents", "BayesNets", "Boltzmann", "Brim", "Brownian", "BooSTjl", "BeliefUpdaters", "ChaosCommunications", "CombineML", "CoupledFields", "Crispulator", "CrossDecomposition", "CrossMappings", "ChemometricsTools", "DSGE", "DataArrays", "DataTables", "DirectGaussianSimulation", "DPMeansClustering", "DynamicHMCModels", "EcologicalNetwork", "EventHistory", "ForecastEval", "GLM", "GaussianMixtures", "GeoStats", "GeoStatsDevTools", "Gillespie", "Graph500", "GraphCentrality", "GraphGLRM", "HurdleDMR", "ImageQuilting", "ImageView", "IncrementalInference", "InverseDistanceWeighting", "InvariantCausal", "InteractiveChaos", "JointMoments", "Klara", "Kpax3", "LocallyWeightedRegression", "Lora", "LowRankModels", "LyapunovExponents", "MachineLearning", "Mads", "MarketTechnicals", "Microbiome", "Mimi", "MixedModels", "MultipleTesting", "MCMCChain", "MRIReco", "MambaModels", "MCMCChains", "MonteCarloMeasurements", "NHST", "NLreg", "NMF", "NetalignMeasures", "NetalignUtils", "NullableArrays", "NextGenSeqUtils", "Orchestra", "PGFPlots", "PGFPlotsX", "ParticleFilters", "PowerLaws", "PiecewiseDeterministicMarkovProcesses", "RandomQuantum", "RegERMs", "RegressionTables", "Rifraf", "RobustLeastSquares", "RobustStats", "ReinforcementLearning", "SALSA", "SOM", "ScikitLearn", "Shannon", "SortingLab", "SpatialEcology", "Spectra", "StackedNets", "StatPlots", "Stats", "StreamStats", "StatisticalRethinking", "StatsKit", "StatsMakie", "StatsPlots", "StanModels", "SpectralGaussianSimulation", "StratiGraphics", "TensorDecompositions", "TimeModels", "TimeseriesSurrogates","TuringModels", "TSML", "Variography", "Vega", "Wallace", "Whippet", "Winston", "YaoArrayRegister"]``

**Comment by StefanKarpinski** [comment]
I'm sorry about the transition pains. We'll get these things sorted out soon.

**Pull request merged**
