### PR TITLE
Add upper bound for Unitful version to UnitfulAtomic

### PR DESCRIPTION
**Pull request by sostock**
There was no upper bound for Unitful in UnitfulAtomic 0.3.0, so I added one.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Can you confirm that when using your branch of the registry, you can do things like `] add UnitfulAtomic` and everything still works correctly?

**Comment by sostock** [comment]
How do I add a custom branch of a registry? I tried
```julia
pkg> registry add https://github.com/sostock/General#unitfulatomic_upper_bound
   Cloning registry from "https://github.com/sostock/General#unitfulatomic_upper_bound"
ERROR: failed to clone from https://github.com/sostock/General#unitfulatomic_upper_bound, error: GitError(Code:ERROR, Class:Net, unexpected HTTP status code: 400)

pkg> registry add https://github.com/sostock/General@unitfulatomic_upper_bound
   Cloning registry from "https://github.com/sostock/General@unitfulatomic_upper_bound"
ERROR: failed to clone from https://github.com/sostock/General@unitfulatomic_upper_bound, error: GitError(Code:ERROR, Class:Net, unexpected HTTP status code: 400)

pkg> registry add https://github.com/sostock/General unitfulatomic_upper_bound
   Cloning registry from "https://github.com/sostock/General"
     Added registry `General` to `~/.julia/registries/General`
ERROR: no path or url specified for registry
```

**Comment by DilumAluthge** [comment]
In Bash:
```bash
git clone https://github.com/sostock/General General # clone your fork
cd General
git checkout unitfulatomic_upper_bound # checkout your branch
rm -rf ~/.julia # make sure you have a clean setup
julia # start a Julia REPL
```

Now, in the Julia REPL:
```julia
julia> import Pkg
julia> Pkg.Registry.add(Pkg.RegistrySpec(path = pwd()))
```

**Review by fredrikekre — APPROVED** [review]
Looks correct.

**Comment by sostock** [comment]
> Can you confirm that when using your branch of the registry, you can do things like `] add UnitfulAtomic` and everything still works correctly?

It works on my machine.

**Comment by DilumAluthge** [comment]
@fredrikekre Can you double-check that the updated PR still looks correct?

**Comment by DilumAluthge** [comment]
I’ll merge this since @sostock tested it and it seems to work.

@fredrikekre revert if I’m mistaken.

**Pull request merged**
