### PR TITLE
New version: NeuroAnalyzer v0.24.2

### PR DESCRIPTION
**Pull request by AdamWysokinski**
UUID: b40dcafa-b65c-47ad-a230-3174ba5cadd1
Repo:
Tree: 39eb97b47746535e3e0a13ab4334e531627f0d57

### CODE REVIEW

**Comment by fredrikekre** [comment]
Missing `[compat]` for the new dependency.

**Comment by AdamWysokinski** [comment]
> Missing `[compat]` for the new dependency.

Hm. Any idea why it's missing? All changes were generated by LocalRegistry.jl

**Comment by GunnarFarneback** [comment]
The first registered version had 58 dependencies and only Julia compat, so it wouldn't have passed automerge, if that could have been run.

https://github.com/GunnarFarneback/PackageCompatUI.jl can help you with adding to the Compat section.

**Comment by AdamWysokinski** [comment]
Ok, I'll do another PR.

**Comment by AdamWysokinski** [comment]
Ok, I think Ive managed to correct the missing [compat] issue. Could you please take a look at https://github.com/JuliaRegistries/General/pull/99987 and merge it manually?

**Pull request closed without merging**
