### PR TITLE
Yank JLD 0.12.4

### PR DESCRIPTION
**Pull request by mkitti**
JLD 0.12.4 prematurely added support for HDF5 0.16 without also re-adding Blosc compression support by not adding a dependency on the upcoming package H5Zblosc. Please yank JLD version 0.12.4

See https://github.com/JuliaIO/JLD.jl/pull/305#issuecomment-994410288

cc: @musm

### CODE REVIEW

**Comment by musm** [comment]
Didn't know this was a thing. Documented anywhere?

**Comment by mkitti** [comment]
This might be the best documentation at the moment:
https://github.com/JuliaLang/Pkg.jl/pull/726

**Comment by musm** [comment]
@giordano  any chance we could get this merged?

**Comment by giordano** [comment]
There is a merge conflict

**Comment by mkitti** [comment]
I resolved the merge conflict.

**Pull request merged**
