### PR TITLE
Transfer from kimmolinna to duckdb

### PR DESCRIPTION
**Pull request by jeremiahpslewis**
@kimmolinna Just trying to clean up loose ends here, think this is necessary for the 'handover' of the package to duckdb.

### CODE REVIEW

**Comment by kimmolinna** [comment]
It would be great to have an officially supported version of DuckDB wrapper for Julia.

**Comment by jeremiahpslewis** [comment]
Just to be clear about what this PR does (afaik):

It redirects 'ownership' of DuckDB.jl in the General package registry to the duckdb upstream. Following this, the duckdb team can use the [Registrator](https://github.com/JuliaRegistries/Registrator.jl) bot to tag the latest release. Subsequently, anyone installing the package via Pkg.add("DuckDB") or updating their package environment will get the package as provided at github.com/duckdb/duckdb.

@kimmolinna Just so everything is super explicit, can you comment and confirm that this is what you would like to happen?

**Comment by kimmolinna** [comment]
I can confirm that. This is what I have proposed to DuckDB team.

**Comment by fredrikekre** [comment]
Are the previous releases available in the new repo?

**Comment by kimmolinna** [comment]
No. The structure is totally different in the new repo because it includes the whole DuckDB code base. I have planned to archive my package.

**Comment by jeremiahpslewis** [comment]
Closing, think we will need a new package name

**Comment by fredrikekre** [comment]
No that shouldn't be necessary I think. Something similar was done for Arrow.jl when it was moved to another repo in a subdir, I can't dig up the details right now though.

**Comment by jeremiahpslewis** [comment]
Ok, but the difference here is it's not just a subdir move, but a rewrite. In order to make the previous package versions available, they need to be added and git-tagged in the new repo, right?

**Comment by kimmolinna** [comment]
From my point of view It should be like DuckDB.jl is used for an official package in the future.

**Comment by Mytherin** [comment]
Is this about archiving previous versions in the [`Versions.toml`](https://github.com/JuliaRegistries/General/blob/3cce0ada63c54ace5b10f02c53d1cfcfc741f22a/D/DuckDB/Versions.toml)? Perhaps we could add all the previous versions to the main DuckDB repository in the subdirectory, and update the git hashes in the `Versions.toml` to the newly-added previous versions.

**Comment by Mytherin** [comment]
On that note it seems that the [Deps.toml](https://github.com/JuliaRegistries/General/blob/3cce0ada63c54ace5b10f02c53d1cfcfc741f22a/D/DuckDB/Deps.toml) might also need to be updated, as we have introduced a few more dependencies (`FixedPointDecimals`, `UUIDs` and `WeakRefStrings`, with `CSV` removed):

```
[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DuckDB_jll = "2cbbab25-fc8b-58cf-88d4-687a02676033"
FixedPointDecimals = "fb4d412d-6eee-574d-9565-ede6634db7b0"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
WeakRefStrings = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"
```

**Comment by kimmolinna** [comment]
@fredrikekre How should we proceed with this? The most convenient solution would be to use DuckDB.jl package name and the source would be in `duckdb/tools/juliapkg` structure. And as @Mytherin said It's possible to save old packages so that those are available too but as an implementor of those I would say that the new package has so many requested features that I don't see value for the old packages anymore. The biggest thing has been achieved. We have the official DuckDB package for Julia.👍

**Comment by Mytherin** [comment]
@fredrikekre Any pointers on how we can move forward on this?

**Comment by fredrikekre** [comment]
@quinnj you did this type of move for Arrow.jl, right? Did you just check in all the old releases in the new repo?

**Comment by kimmolinna** [comment]
@StefanKarpinski and @Mytherin - for me all options are ok. I just wanted to have an integration between two great tools. My goal is achieved. ;)

**Comment by Mytherin** [comment]
@StefanKarpinski thanks for the super detailed answer! Both option 2 and 3 are fine by me, with a preference for option 3. We are not particularly picky about our git history. It would be fantastic if you could make a PR that implements this - otherwise I can have a look at doing this in two weeks as I am on holiday for the next week.

**Comment by StefanKarpinski** [comment]
Ok, I'm happy to take a crack at option 3 soonish. Will let you know how it goes.

**Comment by Mytherin** [comment]
@StefanKarpinski is there anything I can do to help with this? Should I just look at the [versions here](https://github.com/jeremiahpslewis/General/blob/jpsl/duckdb/D/DuckDB/Versions.toml), copy the contents of the corresponding tags into the `tools/juliapkg` directory each as a separate commit, then submit a PR with those separate commits to the main DuckDB repository? Or is there more involved git-fuu required?

Also a question about this, the hashes don't appear to match the git hashes, e.g. in the `Versions.toml` for v0.2.3 the sha1 hash is `fe91662c7669e317ffaa9c9c84d3f7c7f53c68ac`, but the commit hash for the tag is `b841037e4c8bd51793555cccc9bd6d8af4d7bdec`. Is the hash in the `Versions.toml` something else than a commit hash (e.g. a sha hash of all the files)? If so, how does the version manager know which version corresponds to which commit hash?

**Comment by StefanKarpinski** [comment]
Oops, this fell of my todo list rada. Sorry about that, I will take a crack at it as promised. The commit hashes definitely won't match, but it's the tree hashes that need to match, not commits.

**Comment by Mytherin** [comment]
Awesome, thanks!

**Comment by zsz00** [comment]
@StefanKarpinski What is the status of this now?

**Comment by Mytherin** [comment]
I have created a PR that copies the history of the tagged versions of DuckDB.jl in duckdb/duckdb#3782. Could you have a look to see if that is correct/sufficient for this to work?

**Comment by StefanKarpinski** [comment]
Unfortunately that doesn't look right. Here's a Julia script that should reproduce the versions file:
```jl
start = "eb42b9c978c70af3484081672003deae88eb81be"
stop  = "bc57e97826d6176b89b132bddf76f1956e90a551"

for commit in eachline(`git log --reverse --format=%H $start^..$stop`)
    msg = strip(read(`git log --format=%B -n 1 $commit`, String))
    ver = chopprefix(msg, "Julia Package History: ")
    println("[$ver]")
    tree = chomp(read(`git rev-parse $commit:tools/juliapkg`, String))
    println("git-tree-sha1 = $(repr(tree))")
    println()
end
```
The last four entries are correct, but the first three are not:
```toml
[v0.2.3]
git-tree-sha1 = "ade8d41f0dfc62b068ebd26613d84a7b75e33a1e"

[v0.2.4]
git-tree-sha1 = "b306ca650ad14d7a33e3cf9b48ffb9adf8b40ba7"

[v0.2.5]
git-tree-sha1 = "f7985531e3a52c99981a7e7a1582558d6f727762"

[v0.2.6]
git-tree-sha1 = "45c28d7b240ed6c69352a3f3a44cda6816e6aa3d"

[v0.2.7]
git-tree-sha1 = "365b17fc8e7d4bcde263ad113067b5133718288c"

[v0.2.8]
git-tree-sha1 = "d8f40363be48fc902f8076b9c4093ec674f6f841"

[v0.2.9]
git-tree-sha1 = "e958e20c6a0b303f2eec8ba2f654d304d94125a6"
```

**Comment by StefanKarpinski** [comment]
Yes, that branch looks good to me—the tree hashes all match 👍🏻

**Comment by Mytherin** [comment]
Alright, excellent! It has been merged. What else needs to happen to move this PR forward?

**Comment by StefanKarpinski** [comment]
I can test this branch of General out and see that it works.

**Comment by StefanKarpinski** [comment]
Everything works. For future reference of anyone interested, here's what I did:

0. Prewarm all dependencies by installing each registered version of DuckDB
1. Delete my installed registries with `rm -rf ~/.julia/registries/General*`
2. Clone this git repo at this branch into `~/.julia/registries/General`
3. Disable using the package server with `export JULIA_PKG_SERVER=localhost`
4. Started `julia` and do `pkg> activate --temp` to create an temporary environment
5. Install each version of DuckDB with `pkg> add DuckDB@0.2.3` and so on.

This sequence forces installing each version of DuckDB via git tree checkout.

**Pull request merged**
