### PR TITLE
BitemporalPostgres repo transfer

### PR DESCRIPTION
**Pull request by michaelfliegner**

### CODE REVIEW

**Comment by michaelfliegner** [comment]
Thanks. Sorry for hassle.

**Comment by michaelfliegner** [comment]
Not quite sure: is there anything left to do for me?

Regards Michael

Mosè Giordano ***@***.***> schrieb am Di., 12. Juli 2022,
00:22:

**Comment by giordano** [comment]
No

**Comment by michaelfliegner** [comment]
Hello!
Registrator did not answer yet. Still an issue with this transfer?

regards Michael

**Comment by giordano** [comment]
Did you activate it in the new repository? If it's under a new organisation which didn't have the app already enabled you may have to re-enable it. This is how github apps work

**Comment by michaelfliegner** [comment]
I succeeded in activating BitemporalPostgres and LifeInsuranceDataModel.

For BitemporalReactive I got this message

Changing package repo URL not allowed, please submit a pull request with
the URL change to the target registry and retry.

Can You help?

Regards Michael

Mosè Giordano ***@***.***> schrieb am Di., 12. Juli 2022,
09:23:

**Comment by michaelfliegner** [comment]
Now everything's fine

Michael Fliegner ***@***.***> schrieb am Di., 12. Juli
2022, 13:53:

**Pull request merged**
