### PR TITLE
Update compat of DiffEqBase

### LINKED ISSUE #462: Incorrect compatibility bounds on DiffEqBase 6.22.2 and 6.23
Recently we've been getting some errors in `Manifolds.jl` tests on Julia 1.0, like this (with DiffEqBase 6.22.2): https://travis-ci.org/github/JuliaNLSolvers/Manifolds.jl/jobs/663616477?utm_medium=notification&utm_source=github_status or this (with DiffEqBase 6.23): https://travis-ci.org/github/JuliaNLSolvers/Manifolds.jl/jobs/663588022?utm_medium=notification&utm_source=github_status . Both versions are clearly not compatible with Julia 1.0 but in the registry they are advertise as compatible. Could you fix this?

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Fixes https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/462

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@DilumAluthge could you double check this?

**Comment by DilumAluthge** [comment]
Did you make these edits manually?

I mean, it looks correct to me, but it is very hard to tell just by looking. Sometimes manual edits will look correct but will actually break something.

Can you, in a fresh environment, use your branch of the registry and confirm that you can successfully add all the relevant versions of the package. Some instructions here: https://github.com/JuliaRegistries/General/pull/10946#issuecomment-599071217

I particularly want to make sure that you can Pkg.add every version of DiffEqBase from e.g. 6.22 through 6.24.

It might also be worth double-checking that you can Pkg.add some packages that depend on DiffEqBase.

**Comment by DilumAluthge** [comment]
@ChrisRackauckas Any particular reason for closing?

**Comment by ChrisRackauckas** [comment]
I made a different PR because there were permissions issues with pushing to the same branch.

**Pull request closed without merging**
