### PR TITLE
New URL for OteraEngine.jl

### PR DESCRIPTION
**Pull request by MommaWatasu**
I changed url of my repository because of my username.
And I saw this issue: [https://github.com/JuliaRegistries/Registrator.jl/issues/181](https://github.com/JuliaRegistries/Registrator.jl/issues/181)

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
I think we'll need some proof that you are the same user as @QGMW22. Did you delete the old account rather than changing your user name?

**Comment by MommaWatasu** [comment]
I changed my username. I registered [LearningHorse](https://github.com/JuliaRegistries/General/tree/master/L/LearningHorse) as QGMW22. Please see this [issue](https://github.com/MommaWatasu/LearningHorse.jl/issues/1), you can recognize that I(MommaWatasu) commented and Julia Registrator made PR as QGMW22.

If this is not enough. Please let me know what proof is needed.

**Comment by MommaWatasu** [comment]
@StefanKarpinski 
I’ve been waiting for 2 days. Please merge this PR.
If the proof I suggested is not enough, examine old url. This url is redirected new url.

**Comment by korilium** [comment]
You have to at least wait three days before the auto-merge happens.  [noblock]

**Pull request merged**
