### PR TITLE
Draft contribution guidelines

### PR DESCRIPTION
**Pull request by ericphanson**
As suggested by @loganpatrick on `#new-package-registration`, I wrote up some contribution guidelines for how anyone can get involved in helping out in maintaining General.

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Awesome first pass, this looks great.

**Comment by storopoli** [comment]
Why the file lives inside the `.github/` folder? I often find `CONTRIBUTING.md` in the root project folder.

**Comment by ericphanson** [comment]
Good point, it’s probably more visible there. Moved

**Comment by DilumAluthge** [comment]
Can you add a link in the README that links to the CONTRIBUTING file?

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
@ericphanson Good to merge this as a first pass?

**Comment by ericphanson** [comment]
Sure, probably better than nothing 😄.

I think it would be great to get buy-in from other long-time registry maintainers like @StefanKarpinski @fredrikekre @KristofferC and Mosè (won't tag him since he's on vacay!) but also I can address any followups in post-merge review, and I'd rather not let this dangle forever.

**Comment by ericphanson** [comment]
Argh, meant to squash and merge, sorry.

**Pull request merged**
