### PR TITLE
[CI] Update GitHub Actions workflows

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Review by ericphanson — APPROVED** [review]

**Comment by giordano** [comment]
Uhm, we also need to get rid of ours uses of `set-output`.

**Review by DilumAluthge — APPROVED** [review]

**Comment by giordano** [comment]
Last commit which replaces the use of the deprecated command `set-output` seems to be working as expected, see for example
* https://github.com/JuliaRegistries/General/actions/runs/3869005248/jobs/6594830076 for v1.6
* https://github.com/JuliaRegistries/General/actions/runs/3869005248/jobs/6594830180 for v1.8
* https://github.com/JuliaRegistries/General/actions/runs/3869005248/jobs/6594830221 for v1.10

**Review by DilumAluthge — APPROVED** [review]
Thanks!!

**Comment by DilumAluthge** [comment]
Thanks @giordano!

**Pull request merged**
