### PR TITLE
remove packages and versions of packages that do not support Julia 1.0

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by KristofferC** [comment]
This is the result of running https://gist.github.com/KristofferC/a0c56b731a55e071ccf58da682cc1e40

**Comment by fredrikekre** [comment]
yolo

**Comment by nickrobinson251** [comment]
guess we should revert this for now?

**Comment by fredrikekre** [comment]
> It appears this messes up private registries...

How?

**Comment by StefanKarpinski** [comment]
Can you elaborate?

**Comment by omus** [comment]
Error message we are seeing. I'm doing some investigating
```
pkg> up
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Updating registry at `~/.julia/registries/Invenia`
  Updating git-repo `https://gitlab.invenia.ca/invenia/PackageRegistry`
 Resolving package versions...
ERROR: MethodError: Cannot `convert` an object of type Nothing to an object of type String
Closest candidates are:
  convert(::Type{T<:AbstractString}, ::T<:AbstractString) where T<:AbstractString at strings/basic.jl:207
  convert(::Type{T<:AbstractString}, ::AbstractString) where T<:AbstractString at strings/basic.jl:208
  convert(::Type{T}, ::T) where T at essentials.jl:154
Stacktrace:
 [1] setindex!(::Dict{Base.UUID,String}, ::Nothing, ::Base.UUID) at ./dict.jl:381
 [2] deps_graph(::Pkg.Types.Context, ::Dict{Base.UUID,String}, ::Dict{Base.UUID,Pkg.Types.VersionSpec}, ::Dict{Base.UUID,Pkg.Types.Fixed}) at /Users/omus/Development/Julia/1.1/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:299
 [3] resolve_versions!(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}, ::Nothing) at /Users/omus/Development/Julia/1.1/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:369
 [4] resolve_versions! at /Users/omus/Development/Julia/1.1/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:315 [inlined]
 [5] up(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /Users/omus/Development/Julia/1.1/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1215
 [6] #up#33(::Pkg.Types.UpgradeLevel, ::Pkg.Types.PackageMode, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /Users/omus/Development/Julia/1.1/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:123
 [7] up at /Users/omus/Development/Julia/1.1/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:95 [inlined]
 [8] do_up!(::Dict{Symbol,Any}, ::Array{Pkg.Types.PackageSpec,1}, ::Dict{Symbol,Any}) at /Users/omus/Development/Julia/1.1/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:649
 [9] #invokelatest#1(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Any, ::Any, ::Vararg{Any,N} where N) at ./essentials.jl:742
 [10] invokelatest(::Any, ::Any, ::Vararg{Any,N} where N) at ./essentials.jl:741
 [11] do_cmd!(::Pkg.REPLMode.PkgCommand, ::REPL.LineEditREPL) at /Users/omus/Development/Julia/1.1/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:563
 [12] #do_cmd#31(::Bool, ::Function, ::REPL.LineEditREPL, ::String) at /Users/omus/Development/Julia/1.1/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:538
 [13] do_cmd at /Users/omus/Development/Julia/1.1/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:534 [inlined]
 [14] (::getfield(Pkg.REPLMode, Symbol("##53#56")){REPL.LineEditREPL,REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool) at /Users/omus/Development/Julia/1.1/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:988
 [15] #invokelatest#1 at ./essentials.jl:742 [inlined]
 [16] invokelatest at ./essentials.jl:741 [inlined]
 [17] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /Users/omus/Development/Julia/1.1/usr/share/julia/stdlib/v1.1/REPL/src/LineEdit.jl:2273
 [18] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /Users/omus/Development/Julia/1.1/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:1035
 [19] run_repl(::REPL.AbstractREPL, ::Any) at /Users/omus/Development/Julia/1.1/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:192
 [20] (::getfield(Base, Symbol("##734#736")){Bool,Bool,Bool,Bool})(::Module) at ./client.jl:362
 [21] #invokelatest#1 at ./essentials.jl:742 [inlined]
 [22] invokelatest at ./essentials.jl:741 [inlined]
 [23] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:346
 [24] exec_options(::Base.JLOptions) at ./client.jl:284
 [25] _start() at ./client.jl:436
```

**Comment by nickrobinson251** [comment]
On Julia 1.1.1 and 1.2.0 the error looks like (as Curt wrote above)
```
ERROR: MethodError: Cannot `convert` an object of type Nothing to an object of type String
```
On Julia 1.3.0-rc3.0 the particular error i see is
```
ERROR: cannot find name corresponding to UUID df88083b-ffd0-5ec9-9f27-0a3b3d809c9f in a registry
```
which is/was Requests.jl

**Comment by fredrikekre** [comment]
I guess you then have private packages that reference now-deleted packages?

**Comment by StefanKarpinski** [comment]
Seems like a solution would be to remove everything that depends on Requests; or duplicate the old Requests info in the private registry. I would point out that if we'd moved everything to an Attic registry, then the solution would be "install the Attic registry".

**Comment by nickrobinson251** [comment]
Yeah, there is a Deps.toml like
```
["0-0.3"]
Requests = "df88083b-ffd0-5ec9-9f27-0a3b3d809c9f"

[0-2]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
URIParser = "30578b45-9adc-5946-b283-645ec420af67"
etc.
```
Any easy way to find all now-deleted packages?

**Comment by fredrikekre** [comment]
Maybe just run the script on your own registry too?

**Comment by omus** [comment]
> Maybe just run the script on your own registry too?

I just attempted this and it looks like some modifications to the script are required. It is unaware that our registry makes use of the General registry.

**Comment by KristofferC** [comment]
A month ago I posted the script we used, a branch of the registry where the script had been run as well as a detailed time plan of when this would happen.

You can also check out the commit of the registry before this change (we should make a branch as well) if you need more time.

**Comment by StefanKarpinski** [comment]
The simplest fix should be to put a copy of the Requires package directory in your private registry, so I recommend doing that first. Then get Kristoffer’s script working on the private registry.

**Comment by omus** [comment]
@StefanKarpinski thanks for mentioning that work around. Implementing that fix has addressed the immediate concern.

**Comment by KristofferC** [comment]
I can tweak the script tomorrow to remove versions in other registries that depen on something that doesn't exist in the General (or the custom registry itself).

**Comment by KristofferC** [comment]
https://gist.github.com/KristofferC/d7565da3139ea175278f6e7fe5089b16 should fixup a registry.

Note that I haven't got access to a custom registry to actually run it on. I ran it on https://github.com/HolyLab/HolyLabRegistry but no package there depends on a package that got deleted.

**Comment by sbromberger** [comment]
Is there a convenient list of packages that got deleted? I'm having some problems with LightGraphs but want to do some research before bringing it up as an issue.

**Comment by KristofferC** [comment]
Yes, https://gist.github.com/KristofferC/d7565da3139ea175278f6e7fe5089b16#file-packages_deleted.

**Pull request merged**
