### PR TITLE
Zygote bounds for older releases

### PR DESCRIPTION
**Pull request by MikeInnes**
This is an attempt to make Zygote's compatibility more correct; it's not critical but will hopefully make maintenance easier and avoid spurious downgrades etc. in future. Could use an audit from someone who knows what they're doing to make sure it's not going to go wrong in unexpected ways. If it looks good I'll try to follow up on other packages so that we can start to improve the compatibility situation a bit.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Ready?

**Comment by MikeInnes** [comment]
I'm happy with it if you are.

**Comment by MikeInnes** [comment]
The CI error is 

```julia
ArgumentError: invalid version range: "0.0, 0.1"
```

presumably caused by the line:

```toml
DiffRules = "0.0, 0.1"
```

I don't understand why this isn't working; I'm following the docs from Pkg.jl here. Any advice?

**Comment by MikeInnes** [comment]
Ok, I think I have the right syntax, it's just different to what's documented there.

**Comment by fredrikekre** [comment]
Whats documented in Pkg is just `Project.toml` syntax. The registry uses a slightly different format; see e.g. https://github.com/JuliaLang/Pkg.jl/issues/1190

**Comment by torfjelde** [comment]
Bump :heart:

**Pull request merged**
