### PR TITLE
redirect repos

### PR DESCRIPTION
**Pull request by jd-lara**
This PR redirects the repos after the recent re-brand of the tools

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Does GitHub not redirect changed user/org names? Just wondering, since as this stands we kind of have to trust that this new org is legit (although we know who you are, so I believe it, but we need to be careful).

**Comment by jd-lara** [comment]
> Does GitHub not redirect changed user/org names? Just wondering, since as this stands we kind of have to trust that this new org is legit (although we know who you are, so I believe it, but we need to be careful).

yes, GitHub redirects but I opened this PR based on the recommendation in the README. Here is a link to the organizational link https://www.nrel.gov/analysis/sienna.html

**Comment by jd-lara** [comment]
@StefanKarpinski it looks like the re-direct doesn't work anymore. 

image


I would appreciate merging to PR to be able to release the latests versions of all the packages please.

**Comment by jd-lara** [comment]
bump to @StefanKarpinski about this PR, we need to tag new package versions urgently and we can't at the moment. See message above.

**Pull request merged**
