### PR TITLE
limit JET's compatibilities to v1.6

### PR DESCRIPTION
**Pull request by aviatesk**
I'd like to limit Julia version compatibilities of currently released JET versions.
And future versions of JET will only support v1.7.

/cc @timholy does this look reasonable to you ?

### CODE REVIEW

**Comment by timholy** [comment]
LGTM, but I am not an expert on these matters so perhaps @KristofferC?

**Comment by KristofferC** [comment]
I think this should work. But it is always good to test these things out locally by checking out this branch and trying out the package manager to see that things behave as expected.

Also, is JET completely broken on 1.7? Otherwise, it might make sense to wait with this until the 1.7 release for JET is out.

**Comment by aviatesk** [comment]
JET 0.5.0 is ready and it should work with v1.7 and higher.
I will make a minor release and then update this branch.

**Comment by aviatesk** [comment]
@KristofferC can we move this forward ? I confirmed this worked locally.

**Pull request merged**
