### PR TITLE
Update multiple ImageCore compat from 0.7 to 0.8

### PR DESCRIPTION
**Pull request by IanButterworth**
@timholy Hopefully this reduces the pain.. Replaces and expands https://github.com/JuliaRegistries/General/pull/389

All add-able to a blank slate package environment, except `Caesar.jl` due to https://github.com/JuliaLang/Pkg.jl/issues/1169
```
Ians-MacBook-Pro:.julia ian$ JULIA_DEPOT_PATH=/tmp/pkgs julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(v1.1) pkg> add ImageCore
... etc.
(v1.1) pkg> st
    Status `/private/tmp/pkgs/environments/v1.1/Project.toml`
  [a09fc81d] ImageCore v0.8.2
  [d8c32880] ImageInTerminal v0.4.0
  [bc367c6b] ImageMetadata v0.7.0
  [787d08f9] ImageMorphology v0.2.0
  [02fcd773] ImageTransformations v0.7.2
  [e94cdb99] MosaicViews v0.1.0
  [dca85d43] QuartzImageIO v0.6.0
```
Passing local tests on MacOS 10.14.4 (except for `Caesar.jl` which is untested due to above)

- [x]   [a09fc81d] ImageCore v0.8.2
- [x]   [d8c32880] ImageInTerminal v0.4.0
- [x]   [bc367c6b] ImageMetadata v0.7.0
- [x]   [787d08f9] ImageMorphology v0.2.0
- [x]   [02fcd773] ImageTransformations v0.7.2
- [x]   [e94cdb99] MosaicViews v0.1.0
- [x]   [dca85d43] QuartzImageIO v0.6.0
- [ ] Caesar -> Not tested due to above

Should we leave `Caesar` unchanged, given not tested?

### CODE REVIEW

**Comment by ianshmean** [comment]
Things worth noting.. 

1. Where there were multiple `ImageCore` compat bounds per package, I just edited the last
2. I didn't look for upper bounds <0.7

**Comment by timholy** [comment]
This is probably the right way to do it. In retrospect I was being silly by not just nuking the upper bounds as soon as the bottlenecks started becoming apparent.

Looks like this will need a rebase.

**Comment by ianshmean** [comment]
Ok. I've rebased. Apologies, I shouldn't have brought the ImageMorphology changes in here without closing the other PR

**Comment by timholy** [comment]
Thanks for doing this!

**Comment by fredrikekre** [comment]
Can you rebase on the master branch @ianshmean?

**Comment by dehann** [comment]
Hi @ianshmean , I just noticed this thread now (I'm a maintainer of Caesar.jl) -- is this issue still a problem?  I'm a little worried if you are indeed seeing the `p0 != p1` assertion error?  Issue #1169 was resolved 2 days after your initial post in #455 so the issue should already be resolved.

> The p0 != p1 assertion issue was related to bad compat in IncrementalInference.jl tomls, which is a dependency used by Caesar.jl.

A new version of Caesar (v0.3.1) was tagged yesterday but it's compat only goes up to `ImageCore = "0.7"`.  I just tried to install `ImageCore` with regular package add and it seems to work fine:
```julia
(testimagecorecaesar) pkg> status
    Status `~/.julia/environments/testimagecorecaesar/Project.toml`
  [62eebf14] Caesar v0.3.0
  [a09fc81d] ImageCore v0.8.2
```

ASIDE: Tests are running for new Caesar.jl with `ImageCore 0.8` compat, if interested JuliaRobotics/Caesar.jl#326

**Pull request merged**
