### PR TITLE
Update TextParse bounds

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
This also looks ok to me.

@fredrikekre Any objections?

**Comment by fredrikekre** [comment]
I guess technically those should be 
```
TextParse = ["0.6-0.9", "1"]
```
but :man_shrugging:

**Comment by davidanthoff** [comment]
@fredrikekre I've seen that but never understood the difference. Is one preferred over the other?

**Comment by fredrikekre** [comment]
`"0.6-1"` includes e.g. `0.10`, `0.11`, ... which `["0.6-0.9", "1"]` doesn't.

**Comment by davidanthoff** [comment]
Ah, that makes sense!

**Pull request merged**
