### PR TITLE
New package: libclangex_jll v0.1.1+0

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package libclangex_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/libclangex_jll.jl
* Version: v0.1.1+0
* Commit: f4a23b67dc58ffe7b3e6260796fe7f252296242c
* Revision on Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/commit/4bf49005184fd94b2f6671d482a562868425bada
* Created by: @Gnimuc

### CODE REVIEW

**Comment by giordano** [comment]
@Gnimuc

**Comment by Gnimuc** [comment]
I think it's OK to merge both #40688 and this. Although this JLL package can not work out-of-box, it's trivial to work around the issue.

**Comment by giordano** [comment]
Can we just merge this one?  Any particular reason to have also #40688?

**Comment by Gnimuc** [comment]
`libclangex_jll`-v0.1.0 has some issues with rpath, which is patched in v0.1.1, so maybe it's better to close #40688. After https://github.com/JuliaPackaging/Yggdrasil/pull/3313 is landed, I will rebase https://github.com/JuliaPackaging/Yggdrasil/pull/3315 on top of v0.1.1+ and try again.

**Pull request merged**
