### PR TITLE
Add AbstractFFT compat for GPUArrays/ CUDA

### PR DESCRIPTION
**Pull request by DhairyaLGandhi**
Should be non-breaking. Adds the necessary compat to avoid resolver errors with Zygote on Julia 1.3

cc @DilumAluthge

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
Rebase on the latest master?

**Comment by DhairyaLGandhi** [comment]
fixed the conflicts, is that alright?

**Comment by DilumAluthge** [comment]
Oh boy, CI is not happy.

**Comment by DhairyaLGandhi** [comment]
let me rebase

**Comment by DilumAluthge** [comment]
I think you can remove the changes in CUDA/Compat.toml. The changes in GPUArrays should be sufficient here.

**Comment by DhairyaLGandhi** [comment]
Oops, found the issue. I had wanted these compat entries to also be available for some older versions of CUDA (incompatible with Julia 1.5), so would those be taken care of as well? I have opened https://github.com/JuliaGPU/CUDA.jl/pull/721 as well

**Comment by DilumAluthge** [comment]
Alright I think I have it working. Can you do take a look at the diff, and make sure that the changes are correct, I.e. it does what you want it to do?

**Comment by DilumAluthge** [comment]
In addition to this PR, you should open PRs to CUDA and GPUArrays to bump the compat entry on the master branch of each of those packages.

You've done that for CUDA (https://github.com/JuliaGPU/CUDA.jl/pull/721).

You should also do it for GPUArrays if you haven't already.

**Comment by DilumAluthge** [comment]
Whew, okay CI is green 😂 

Let me know if the diff looks like it's what you wanted, and then I'll merge this.

**Comment by DhairyaLGandhi** [comment]
yup looks right

**Comment by DhairyaLGandhi** [comment]
thanks

**Pull request merged**
