### PR TITLE
New version: LAPACK_jll v3.10.0+0

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package LAPACK_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl
* Version: v3.10.0+0
* Commit: 717ccd0327bde9e3e023b2b4ae360c7636c27158
* Revision on Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/commit/cf18dd53f396fed967eca6c52155d6824278e54e
* Created by: @ViralBShah

### CODE REVIEW

**Comment by ViralBShah** [comment]
:-(

**Comment by ViralBShah** [comment]
@giordano Any ideas what is going wrong here now?

**Comment by giordano** [comment]
Ok, this is expected because we're now requiring Julia v1.8, and CI here runs on v1.7. I think we can merge this one and hope libblastrampoline won't break ABI again in the future

**Comment by ViralBShah** [comment]
Ok - almost nothing uses LAPACK_jll anyways. The main reason is to have it so that it can work on M1 with Accelerate BLAS.

**Pull request merged**
