### PR TITLE
WIP: add compat for Statistics

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Just for reference, could you post the code used to generate this PR.

**Comment by nalimilan** [comment]
Can we merge this? It seems required to run Nanosoldier on https://github.com/JuliaStats/Statistics.jl/pull/128 and then merge it.

**Comment by KristofferC** [comment]
> 
Just for reference, could you post the code used to generate this PR?

Using https://github.com/KristofferC/StdlibRegistryCompatUpdater:

```
julia> pkg = (Base.UUID("10745b16-79ce-11e8-11f9-7d13ad32a3b2") => "Statistics")

julia> StdlibRegistryCompatUpdater.update_compat_for_stdlib(pkg)
```

> Can we merge this? It seems required to run Nanosoldier on https://github.com/JuliaStats/Statistics.jl/pull/128 and then merge it.

Should be fine now.,

**Comment by KristofferC** [comment]
I think it is fine to use `x` and `y` here. Using the `x1, y1, x2, y2` adds a fair bit of noise and the point here is just to talk about keywords, not about a particular `plot` function.

**Pull request closed without merging**
