### PR TITLE
Purge packages which had the source deleted

### PR DESCRIPTION
**Pull request by Nosferican**
These repositories have been deleted or made private for some time now.

Reference: https://github.com/JuliaLang/METADATA.jl/issues/15100

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Should you also remove those packages from `Registry.toml`?

**Comment by Nosferican** [comment]
I think the releases that depend on those packages should be yanked...

**Comment by Nosferican** [comment]
Were those merged?

**Comment by StefanKarpinski** [comment]
No, this PR was out of date and I think this needs to be done a bit more carefully.

**Comment by Nosferican** [comment]
I can probably draft something along those lines. Should those yank releases by compat or remove entirely? I am not sure how Pkg.jl behaves in those instances.

**Pull request closed without merging**
