### PR TITLE
Upper bound TimerOutputs for release NNlib

### PR DESCRIPTION
**Pull request by DhairyaLGandhi**
Ref: https://github.com/FluxML/NNlib.jl/issues/141

Also, just to confirm, will this guarantee version `0.5.0-0.5.0`?

cc. @MikeInnes

### CODE REVIEW

**Comment by MikeInnes** [comment]
This looks right to me, yeah. `0.5.1` should be considered incompatible here.

**Comment by fredrikekre** [comment]
If this is an issue with TimerOutputs, it would be better to just release a new version of that.

**Comment by MikeInnes** [comment]
We're opening an issue there too, but this fixes the immediate compatibility problem and makes things usable; we don't know how long it will take to debug TimerOutputs, discuss whether it can be fixed, and create and tag that fix, since we're not in control of that repo.

Presumably even with a new TimerOutputs tag, the bounds would have to be updated to something like `0.5.0, 0.5.2+`, since NNlib is still not in fact compatible with 0.5.1.

**Comment by dhairyagandhi96** [comment]
Relevant issue on Timer outputs https://github.com/KristofferC/TimerOutputs.jl/issues/65

**Comment by fredrikekre** [comment]
There is already a PR with a version bump (https://github.com/KristofferC/TimerOutputs.jl/pull/66), then we can yank TimerOutputs 0.5.1. It just becomes very complicated if all packages have to fix their compat bounds when a dependency screws up. cc @KristofferC

**Comment by MikeInnes** [comment]
Ok, if we can get that tagged and yank 0.5.1 in a reasonable time frame, then that does sound like a reasonable way to go.

**Comment by KristofferC** [comment]
https://github.com/JuliaRegistries/General/pull/5413

**Comment by dhairyagandhi96** [comment]
With #5413 merged, could we yank the breaking release?
Thanks for the quick fix, @KristofferC!

**Comment by KristofferC** [comment]
The breaking release will never be picked unless someone explicitly starts upper bounding just above it, or add that version specifically. Yanking has some problems now that I rather just leave the release in.

**Pull request closed without merging**
