### PR TITLE
SnoopCompileBot URL and git sha update

### PR DESCRIPTION
**Pull request by aminya**
Updated the URL and git sha

Based on @fredrikekre's suggestion in https://github.com/JuliaRegistries/General/pull/19557#issuecomment-674461349, I created branches resembling the original code: 
https://github.com/aminya/SnoopCompileBot.jl

### CODE REVIEW

**Review by fredrikekre — CHANGES_REQUESTED** [review]
The tree shas should not change.

**Comment by aminya** [comment]
So how can I do this then?

**Comment by fredrikekre** [comment]
If you check out the correct trees you shouldn't have to change anything here (except the URL)

**Comment by aminya** [comment]
If I understand correctly, you are suggesting that I rewrite the history of my master, so it is built from the @timholy's repository. 
What I did here was to just create branches for the old versions, which means the git sha would become different.

**Comment by fredrikekre** [comment]
The tree sha should not change (the commit sha will be different).

**Comment by aminya** [comment]
@fredrikekre I am not still clear what to do. Could you please give me a git command to try?

**Comment by aminya** [comment]
Closed in favor of #22253

**Pull request closed without merging**
