### PR TITLE
New package: MUMPS_seq_MKL_jll v5.3.5+0

### PR DESCRIPTION
**Pull request by jlbuild**
Autogenerated JLL package registration

* Registering JLL package MUMPS_seq_MKL_jll.jl
* Repository: https://github.com/JuliaBinaryWrappers/MUMPS_seq_MKL_jll.jl
* Version: v5.3.5+0

### CODE REVIEW

**Comment by ViralBShah** [comment]
@dpo Did you see this?

**Comment by dpo** [comment]
Yes. It's the same failure as for Ipopt_MKL. I don't know how to work around it.

**Comment by ViralBShah** [comment]
Look in Yggdrasil for other packages that use MKL?

**Comment by ViralBShah** [comment]
@giordano Do you have any insights into how to ensure that the MKL libraries are found?

**Comment by giordano** [comment]
Need to add all relevant libraries as products

**Comment by ViralBShah** [comment]
I think that is in fact being done in the mumps recipes. It is the dependent BLAS library that is not found after installing the package. Are you saying it may be a problem with MKL_jll?

**Comment by giordano** [comment]
> Are you saying it may be a problem with MKL_jll?

Yes

**Comment by dpo** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/1075

**Comment by giordano** [comment]
That was too much

**Comment by giordano** [comment]
Oh, but that was failing on the same library, `libmkl_intel_lp64`.  So I have no idea about what to do

**Pull request closed without merging**
