### PR TITLE
Update the Julia [compat] entry for SimplePolynomials.jl

### PR DESCRIPTION
**Pull request by DilumAluthge**
SimplePolynomials.jl version 0.1.1 requires Julia 1.4 or greater. 

This PR updates the appropriate compat entry to reflect this requirement.

cc: @scheinerman

### CODE REVIEW

**Comment by scheinerman** [comment]
Had trouble registering and got this message: "Under maintenence". I don't know if I need to try again.

**Comment by DilumAluthge** [comment]
Hmmm. Strange.

What method do you use to register?

**Comment by scheinerman** [comment]
> Hmmm. Strange.
> 
> What method do you use to register?

I use this page:  [https://juliahub.com/ui/Registrator](https://juliahub.com/ui/Registrator) and paste in the URL for the GitHub repository: [https://github.com/scheinerman/SimplePosets.jl.git](https://github.com/scheinerman/SimplePosets.jl.git). I suspect that "they" really are doing some sort of maintenance and it'll be up later.

**Comment by DilumAluthge** [comment]
If you want, you can try the GitHub comment bot.

You go to this page: https://github.com/apps/juliateam-registrator/installations/new

And install the app on your repo.

Then, to register, you post a comment on the appropriate commit.

**Comment by DilumAluthge** [comment]
@scheinerman Just FYI, I confirmed that JuliaHub is in fact under maintenance. It should be up again in a day or two!

**Comment by scheinerman** [comment]
> @scheinerman Just FYI, I confirmed that JuliaHub is in fact under maintenance. It should be up again in a day or two!

Thanks. I'll try again tomorrow using the method I'm used to. I read through the instructions on the GitHub app and got confused :-)

**Pull request merged**
