### PR TITLE
JuliaImages: retroactively put upper bounds on old package versions

### PR DESCRIPTION
**Pull request by timholy**
Is there a good way to test this? CC @johnnychen94

### CODE REVIEW

**Comment by DilumAluthge** [comment]
If the changes were made by RetroCap, then they are _probably_ safe.

The best way to test is to add this branch as a registry and make sure you can `Pkg.add` packages without error. E.g. something like this:
1. First either `rm -rf ~/.julia` or `mv ~/.julia ~/.julia.backup`.
2. Now clone your registry: `git clone https://github.com/timholy/General`.
3. `cd General`
4. `git checkout teh/juliaimages`
5. Start Julia and run:
```julia
import Pkg
Pkg.Registry.add(Pkg.RegistrySpec(path = pwd()))
Pkg.add("Images")
Pkg.rm("Images")
Pkg.gc()
Pkg.add(Pkg.PackageSpec(name = "Images", version = "0.18.0"))
Pkg.rm("Images")
Pkg.gc()
Pkg.add(Pkg.PackageSpec(name = "Images", version = "0.19.0"))
Pkg.rm("Images")
Pkg.gc()
```

And do that a whole bunch of times for a bunch of different packages and versions.

**Comment by timholy** [comment]
The checkout seems to work. One oddity: 
```julia
(MyProj) pkg> add Images@0.18.0
 Resolving package versions...
  Updating `/tmp/retrocap/MyProj/Project.toml`
  [916415d5] ↓ Images v0.19.1 ⇒ v0.18.0
  Updating `/tmp/retrocap/MyProj/Manifest.toml`
  [3da002f7] ↑ ColorTypes v0.8.1 ⇒ v0.9.0
  [c3611d14] ↑ ColorVectorSpace v0.7.1 ⇒ v0.8.2
  [5ae59095] ↑ Colors v0.9.6 ⇒ v0.11.1
  [53c48c17] ↑ FixedPointNumbers v0.6.1 ⇒ v0.7.0
  [a2bd30eb] ↓ Graphics v1.0.1 ⇒ v0.4.0
  [bc367c6b] ↑ ImageMetadata v0.7.2 ⇒ v0.8.0
  [916415d5] ↓ Images v0.19.1 ⇒ v0.18.0

(MyProj) pkg> add Images@0.19.0
 Resolving package versions...
  Updating `/tmp/retrocap/MyProj/Project.toml`
  [916415d5] ↑ Images v0.18.0 ⇒ v0.19.0
  Updating `/tmp/retrocap/MyProj/Manifest.toml`
  [3da002f7] ↓ ColorTypes v0.9.0 ⇒ v0.8.1
  [c3611d14] ↓ ColorVectorSpace v0.8.2 ⇒ v0.7.1
  [5ae59095] ↓ Colors v0.11.1 ⇒ v0.9.6
  [53c48c17] ↓ FixedPointNumbers v0.7.0 ⇒ v0.6.1
  [bc367c6b] ↓ ImageMetadata v0.8.0 ⇒ v0.7.2
  [916415d5] ↑ Images v0.18.0 ⇒ v0.19.0
```
It seems to propagate the current version backwards, not the minimum of the current version and whatever upper bound was in place for a more recent release.

**Comment by johnnychen94** [comment]
> It seems to propagate the current version backwards, not the minimum of the current version and whatever upper bound was in place for a more recent release.

It's not perfect, but I view it as an acceptable result. If we keep on our developments and rolling the versions, all these will be incompatible eventually.

**Comment by timholy** [comment]
Let me poke at RetroCap and see if I can come up with something better.

**Comment by timholy** [comment]
OK, this new version is based on https://github.com/bcbi/RetroCap.jl/pull/34. Looking through the difference between the two approaches, it seems likely to be better.

However, I'm still seeing weird behavior; I'm beginning to suspect the resolver.
```julia
(v1.3) pkg> add Images@0.19.0
 Resolving package versions...
  Updating `~/.julia/environments/v1.3/Project.toml`
  [916415d5] + Images v0.19.0
  Updating `~/.julia/environments/v1.3/Manifest.toml`
  [3da002f7] ↓ ColorTypes v0.9.0 ⇒ v0.8.1
  [c3611d14] ↓ ColorVectorSpace v0.8.2 ⇒ v0.7.1
  [5ae59095] ↓ Colors v0.11.1 ⇒ v0.9.6
  [53c48c17] ↓ FixedPointNumbers v0.7.0 ⇒ v0.6.1
  [a2bd30eb] ↓ Graphics v1.0.1 ⇒ v0.4.0
  [bc367c6b] ↓ ImageMetadata v0.8.0 ⇒ v0.7.2
  [916415d5] ↓ Images v0.19.3 ⇒ v0.19.0

(v1.3) pkg> add Images@0.18.0
 Resolving package versions...
  Updating `~/.julia/environments/v1.3/Project.toml`
  [916415d5] ↓ Images v0.19.0 ⇒ v0.18.0
  Updating `~/.julia/environments/v1.3/Manifest.toml`
  [3da002f7] ↑ ColorTypes v0.8.1 ⇒ v0.9.0
  [c3611d14] ↑ ColorVectorSpace v0.7.1 ⇒ v0.8.2
  [5ae59095] ↑ Colors v0.9.6 ⇒ v0.11.1
  [53c48c17] ↑ FixedPointNumbers v0.6.1 ⇒ v0.7.0
  [916415d5] ↓ Images v0.19.0 ⇒ v0.18.0
```
Note the upgrade to Colors 0.11.1, despite the fact that here's the `Compat.toml` for Images is this:
```toml
["0-0.17"]
ColorVectorSpace = "0.2-0.6"
FileIO = "0-1"
FixedPointNumbers = "0.3-0.5"
ImageCore = "0.6-0.7"
ImageDistances = "0.0.2-0.1"
ImageFiltering = "0-0.6"
ImageMetadata = "0-0.7"
ImageMorphology = "0.1.1-0.1"

["0-0.18"]
AxisArrays = "0.0.0 - 0.3"
ColorTypes = "0.7.4 - 0.8"
Colors = "0.7.0 - 0.9"
Graphics = "0.0.0 - 0.4"
ImageAxes = "0.0.0 - 0.6"
ImageShow = "0.1.1 - 0.2"
ImageTransformations = "0.2.2 - 0.8"
IndirectArrays = "0.0.0 - 0.5"
MappedArrays = "0.0.0 - 0.2"
OffsetArrays = "0.0.0 - 0.11"
Reexport = "0.0.0 - 0.2"
StaticArrays = "0.0.0 - 0.12"
StatsBase = "0.14.0 - 0.32"
TiledIteration = "0.0.0 - 0.2"
julia = "0.7-1"

["0.18"]
ColorVectorSpace = "0.2.0 - 0.7"
FileIO = "0.0.0 - 1"
FixedPointNumbers = "0.3.0 - 0.6"
ImageCore = "0.6.0 - 0.8"
ImageDistances = "0.0.2 - 0.2"
ImageFiltering = "0.0.0 - 0.6"
ImageMetadata = "0.0.0 - 0.7"
ImageMorphology = "0.1.1 - 0.2"

["0.19-0"]
AxisArrays = "0.3"
FileIO = "1"
ImageAxes = "0.5-0.6"
ImageDistances = "0.2.5-0.2"
ImageFiltering = "0.6"
ImageShow = "0.1-0.2"
ImageTransformations = "0.4-0.8"
IndirectArrays = "0.5"
MappedArrays = "0.1-0.2"
OffsetArrays = "0.8-0.11"
Reexport = "0.2"
StaticArrays = "0.8-0.12"
StatsBase = "0.24-0.32"
TiledIteration = "0.2"
julia = "1"

["0.19-0.19.1"]
ColorVectorSpace = "0.6-0.7"

["0.19-0.19.2"]
ColorTypes = "0.7.4-0.8"
Colors = "0.8-0.9"
FixedPointNumbers = "0.5-0.6"
ImageCore = "0.8"
ImageMetadata = "0.6-0.7"

["0.19.0"]
Graphics = "0.4"
ImageMorphology = "0.2"

["0.19.1-0"]
Graphics = ["0.4", "1"]
ImageMorphology = "0.2.2-0.2"

["0.19.2-0"]
ColorVectorSpace = "0.6-0.8"

["0.19.3-0"]
ImageCore = "0.8.1-0.8"
ImageMetadata = "0.6-0.8"
```

I am *so* confused.

**Comment by timholy** [comment]
This can probably be merged, given that it seems to be working for others. https://github.com/JuliaLang/Pkg.jl/issues/1575

**Comment by DilumAluthge** [comment]
> This can probably be merged, given that it seems to be working for others. [JuliaLang/Pkg.jl#1575](https://github.com/JuliaLang/Pkg.jl/issues/1575)

Sounds good. I'll merge this now. If we get reports that it causes problems for others, we can revert it.

**Pull request merged**
