### PR TITLE
Delete empty `Deps.toml`, `Compat.toml`, `WeakDeps.toml`, and `WeakCompat.toml` files

### PR DESCRIPTION
**Pull request by DilumAluthge**
Do not merge this PR until the following PR has been merged:
- [x] https://github.com/JuliaRegistries/RegistryCI.jl/pull/495

<details>

<summary>
Generated by the following script: (click to expand)
</summary>

```julia
mktempdir() do tmp_dir
    cd(tmp_dir) do
        run(`git clone git@github.com:JuliaRegistries/General.git`)
        cd("General") do
            my_branch = "dpa/delete-empty-toml-files"
            commit_msg = "Delete empty `Deps.toml`, `Compat.toml`, `WeakDeps.toml`, and `WeakCompat.toml` files"
            run(`git checkout -B $(my_branch)`)
            for (root, dirs, files) in walkdir(".")
                for file in files
                    path = joinpath(root, file)
                    if file in ("Deps.toml", "Compat.toml", "WeakDeps.toml", "WeakCompat.toml")
                        if isempty(strip(read(path, String)))
                            rm(path)
                        end
                    end
                end
            end
            run(`git add -A`)
            run(`git commit -m "$(commit_msg)"`)
            run(`git push -f origin $(my_branch)`)
        end
    end
end
```

</details>

### CODE REVIEW

**Review by KristofferC — APPROVED** [review]
Woho, less files.

**Comment by KristofferC** [comment]
Actually, can we wait a few days with this? I want to check that some stuff I know interact with the registry is OK with this or if it needs to update.

**Comment by DilumAluthge** [comment]
I've also posted in Slack (in both `#pkg-dev` and `#pkg-registration`) so that downstream consumers of the General registry are aware.

**Comment by DilumAluthge** [comment]
I converted to draft just so that I don't accidentally click the merge button.

**Comment by KristofferC** [comment]
It seems this is fine for the use case I wanted to check. So no objection from my pov.

**Comment by DilumAluthge** [comment]
Should we check that old Pkg clients (i.e. old Julia versions) work fine when these files are missing?

**Pull request closed without merging**
